<section class="">
    <div class="container" style="min-height: 800px">
        <br>
        <br>
        <?php if( isset( $this->session->msg )) : ?>
            <div class="row" style="padding-bottom: 10px;">
                <div class="col-lg-12 col-md-10 col-sm-12  " >
                    <p style="padding: 10px" class="alert-danger ">
                        <i class="fa fa-exclamation-triangle"> </i>
                        <?php echo $this->session->msg ?>
                    </p>
                </div>
            </div>
        <?php endif ?>
        <div class="row" >
            <div class="col-lg-12 col-md-12">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col_blogPost" >
                        <h2> BESOIN D'AIDE  <i class="fa fa-question-circle"> </i></h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aperiam cum
                            deleniti nihil non placeat quo tempore ut voluptatum. Animi consequatur earum enim et illum
                            nesciunt odio quas ratione totam?   deleniti nihil non placeat quo tempore ut
                            deleniti nihil non placeat quo tempore ut
                        </p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aperiam cum
                            deleniti nihil non placeat quo tempore ut voluptatum. Animi consequatur earum enim et illum
                            nesciunt odio quas ratione totam?
                        </p>
                    </div>
                </div>
                <!-- end row -->
                <br>

                <div class="col-lg-4 wrapper-etape ">
                    <div class="row etape">
                        <div class="col-lg-12 content-etape">

                            <div class="row title-wrapper">
                                <div class="col-lg-12 title">
                                    <h1 class="">ETAPE 1</h1>
                                    <i class="fa fa-stop"> </i> &nbsp;Le choix du materiel
                                </div>
                            </div>

                            <div class="row wrapper-etape-data">
                                <div class="col-lg-12 etape-data">
                                    <br><br>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa error fugit in inventore,
                                        iusto voluptate!
                                        Modi qui saepe similique!
                                    </p>
                                    <div class="row center">
                                        <div class="col-lg-6 center">
                                            <ul>
                                                <li> Thermique</li>
                                                <li> Laser</li>
                                                <li> Matricielle</li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-6">
                                            <ul>
                                                <li> Terminal mobile</li>
                                                <li> Douchette</li>
                                                <li> Client leger</li>
                                            </ul>
                                        </div>
                                    </div>

                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa error fugit in inventore,
                                        iusto labore laboriosam laborum nam officiis quia saepe sequi sunt suscipit unde voluptate!
                                        Modi qui saepe similique!
                                    </p>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>


                <div class="col-lg-4 wrapper-etape ">
                    <div class="row etape">
                        <div class="col-lg-12 content-etape">

                            <div class="row title-wrapper">
                                <div class="col-lg-12 title">
                                    <h1 class="">ETAPE 2</h1>
                                    <i class="fa fa-stop"> </i> &nbsp;Dans le vif - la configuration
                                </div>
                            </div>

                            <div class="row wrapper-etape-data">
                                <div class="col-lg-12 etape-data">
                                    <br><br>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa error fugit in inventore,
                                    </p>
                                    <br>
                                    <div class="row center">
                                        <div class="col-lg-6 center">
                                            <ul>
                                                <li> Thermique</li>
                                                <li> Laser</li>
                                                <li> Matricielle</li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-6">
                                            <ul>
                                                <li> Terminal mobile</li>
                                                <li> Douchette</li>
                                                <li> Client leger</li>
                                            </ul>
                                        </div>
                                    </div>
                                    <br>
                                    <p>
                                        <i class="fa fa-angle-right"> </i> &nbsp;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa error fugit in inventore,
                                    </p>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-lg-4 wrapper-etape ">
                    <div class="row etape">
                        <div class="col-lg-12 content-etape">

                            <div class="row title-wrapper">
                                <div class="col-lg-12 title">
                                    <h1 class="">ETAPE 3</h1>
                                    <i class="fa fa-stop"> </i> &nbsp;Le panier ?
                                </div>
                            </div>

                            <div class="row wrapper-etape-data">
                                <div class="col-lg-12 etape-data">
                                    <br>
                                    <div class="row">
                                        <div class="col-lg-4" style="font-size: 2em;">

                                                    <span class="fa-stack fa-lg">
                                                      <i class="fa fa-circle fa-stack-2x blue_pale"></i>
                                                      <i class="fa fa-send fa-stack-1x fa-inverse"></i>
                                                    </span>
                                            <p style="font-size: 0.4em;  text-align: center">Rapide</p>
                                        </div>
                                        <div class="col-lg-4 center" style="font-size: 2em;">
                                                    <span class="fa-stack fa-lg">
                                                      <i class="fa fa-circle fa-stack-2x blue_pale"></i>
                                                      <i class="fa fa-tags fa-stack-1x fa-inverse"></i>
                                                    </span>
                                            <p style="font-size: 0.4em;  text-align: center">Flexible</p>
                                        </div>
                                        <div class="col-lg-4" style="font-size: 2em;">
                                                    <span class="fa-stack fa-lg">
                                                      <i class="fa fa-circle fa-stack-2x blue_pale"></i>
                                                      <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                                                    </span>
                                            <p  style="font-size: 0.4em; text-align: center">Gratuit</p>
                                        </div>
                                    </div>
                                    <br>
                                    <p>
                                        <i class="fa fa-angle-right"> </i> &nbsp;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa error fugit in inventore,
                                    </p>
                                    <br>
                                    <p>
                                        <i class="fa fa-angle-right"> </i> &nbsp;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa error fugit in inventore,
                                    </p>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <!-- end col -->
        </div>
        <br>
        <div class="row">
            <div class="col-lg-12">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa cumque, earum eveniet hic inventore itaque iure non,
                    officiis placeat quos, repellat reprehenderit sapiente tempore voluptate voluptatum. Aspernatur praesentium, quidem!
                    Quaerat.</p>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</section>