<section class="">
    <div class="container" style="min-height: 800px">
        <?php if( isset( $this->session->msg )) : ?>
            <div class="row" style="padding-bottom: 10px;">
                <div class="col-lg-12 col-md-10 col-sm-12  " >
                    <p style="padding: 10px" class="alert-danger ">
                        <i class="fa fa-exclamation-triangle"> </i>
                        <?php echo $this->session->msg ?>
                    </p>
                </div>
            </div>
        <?php endif ?>
        <?php if( isset( $this->session->sucessMsg )) : ?>
            <div class="row" style="padding-bottom: 10px;">
                <div class="col-lg-12 col-md-10 col-sm-12  " >
                    <p style="padding: 10px" class="alert-success ">
                        <i class="fa fa-paper-plane fa-2x"> </i>
                        <?php echo $this->session->sucessMsg ?>
                    </p>
                </div>
            </div>
        <?php endif ?>
        <div class="row" >
            <div class="col-lg-12 col-md-12">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col_blogPost" >
                        <h2> BESOIN D'AIDE  <i class="fa fa-question-circle"> </i></h2>
                        <p>
                            Eurocomputer vous accompagne dans la <b>définition</b> de votre besoin.</p>
                        <p>
                            Nous avons élaboré un nouvel outil de <u>configuration</u> vous permettant de <b>dimensionner</b> votre matériel en fonction de votre activité.
                            Le configurateur vous fera aboutir à une demande de devis <b>gratuite</b> en seulement 3 <u>étapes</u> :
                        </p>
                    </div>
                </div>
                <!-- end row -->
                <br>

                <div class="col-lg-4 col-md-6 col-sm-12 wrapper-etape ">
                    <div class="row etape">
                        <div class="col-lg-12 content-etape">

                            <div class="row title-wrapper">
                                <div class="col-lg-12 title">
                                    <h1 class="">ETAPE 1</h1>
                                    <i class="fa fa-stop"> </i> &nbsp;Choix du type de matériel
                                </div>
                            </div>

                            <div class="row wrapper-etape-data">
                                <div class="col-lg-12 etape-data">
                                    <br>
                                    <p>
                                        Cette étape consiste à déterminer quel type de matériel vous désirez :
                                    </p>
                                    <div class="row center">
                                        <div class="col-lg-10 center">
                                            <ul>
                                                <li> Imprimantes </li>
                                                <li> Terminaux mobiles </li>
                                                <li> Lecteurs code-barres</li>
                                                <li> Postes de travail </li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-6">

                                        </div>
                                    </div>

                                    <p>
                                        Ensuite il faudra choisir une gamme de produit.
                                        Cette étape est simple et rapide elle ne vous prendre que 2 ou 3 clics.
                                    </p>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-12 wrapper-etape ">
                    <div class="row etape">
                        <div class="col-lg-12 content-etape">

                            <div class="row title-wrapper">
                                <div class="col-lg-12 title">
                                    <h1 class="">ETAPE 2</h1>
                                    <i class="fa fa-stop"> </i> &nbsp;Définition des caractéristiques
                                </div>
                            </div>

                            <div class="row wrapper-etape-data">
                                <div class="col-lg-12 etape-data">
                                    <br>
                                    <p>
                                        C’est l’étape la plus importante, grâce à un formulaire complet,
                                        simple et précis nous allons filtrer parmi toute notre base de données et
                                        ainsi vous propose le matériel le plus adapté à vos besoins.
                                    </p>
                                    <p>
                                        Cet étape vous fera gagner un temps précieux dans votre recherche.
                                        En effet il n’est pas toujours simple de s’y retrouver dans les références des produits de traçabilité.
                                    </p>
                                    <p>
                                        Après avoir choisi le ou les matériels correspondants à votre recherche en cliquant sur l’icône (logo demande de devis)
                                        vous accéderez à l’étape 3.
                                    </p>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-12 wrapper-etape ">
                    <div class="row etape">
                        <div class="col-lg-12 content-etape">

                            <div class="row title-wrapper">
                                <div class="col-lg-12 title">
                                    <h1 class="">ETAPE 3</h1>
                                    <i class="fa fa-stop"> </i> &nbsp;Demande de devis
                                </div>
                            </div>

                            <div class="row wrapper-etape-data">
                                <div class="col-lg-12 col-md-12 etape-data">
                                    <br>
                                    <div class="row">
                                        <div class="col-lg-4 col-md-4" style="font-size: 2em;">

                                                    <span class="fa-stack fa-lg">
                                                      <i class="fa fa-circle fa-stack-2x blue_pale"></i>
                                                      <i class="fa fa-send fa-stack-1x fa-inverse"></i>
                                                    </span>
                                            <p style="font-size: 0.4em;  text-align: center">Rapide</p>
                                        </div>
                                        <div class="col-lg-4 col-md-4 center" style="font-size: 2em;">
                                                    <span class="fa-stack fa-lg">
                                                      <i class="fa fa-circle fa-stack-2x blue_pale"></i>
                                                      <i class="fa fa-tags fa-stack-1x fa-inverse"></i>
                                                    </span>
                                            <p style="font-size: 0.4em;  text-align: center">Flexible</p>
                                        </div>
                                        <div class="col-lg-4 col-md-4" style="font-size: 2em;">
                                                    <span class="fa-stack fa-lg">
                                                      <i class="fa fa-circle fa-stack-2x blue_pale"></i>
                                                      <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                                                    </span>
                                            <p  style="font-size: 0.4em; text-align: center">Gratuit</p>
                                        </div>
                                    </div>
                                    <p>
                                        <i class="fa fa-angle-right"> </i> &nbsp;Lors de cette ultime étape vous pouvez choisir la quantité,
                                        c’est aussi à ce moment là qu’il faudra nous transmettre vos coordonnées.
                                    </p>
                                    <p>
                                        <i class="fa fa-angle-right"> </i> &nbsp;Votre demande parviendra immédiatement à
                                        notre service commercial qui vous répondra dans un délai de 4h maximum.
                                    </p>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <!-- end col -->
        </div>
        <br>
        <div class="row">
            <div class="col-lg-12">
                <p></p>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</section>