<div class='card-wrapper '>
    <a href="/basket" class="" title="">
        <div class='card-euro'>
            <div class='card-content'
                 style='background-image:url(<?php echo PROJECTS.'/upload/images/geo/zt600.jpg' ?>)'>
                <h3 class="imgtitlebox">

                    &nbsp;<i class="fa fa-question-circle fa-2x"> </i> &nbsp;Besoin d'aide
                </h3>
                <h6>Laisser vous guider par notre <b>CONFIGURATEUR</b></h6>
                <div class="card-overlay">&nbsp;</div>
            </div>
        </div>
    </a>
</div>