<form action="/filtre/apply" method="post"
      class="wrapper_form-filtre"
>
    
    <div class="row">
        <?php 
        //var_dump($this->input);
        ?>
    </div>
    <!--TITRE -->
    <div class="row " >
        <div class="col-lg-10 col-md-10 col-sm-12 h2 ">
            <b>Imprimantes etiquette - THERMIQUE</b>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-12 h2">
            <?php include('aide_imprimante_thermique.phtml') ?>
        </div>
    </div>
    <!--FIN TITRe-->
    <br>

    <div class="form-section row ">
        <div class="col-lg-4 col-sm-4 col-xs-12 ">
            <div class="row">
                <div class="col-xs-12 col-lg-12">
                    <?php if ($this->input['dpi'] <> 'na' && $this->input['dpi'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            résolution </b> &nbsp;&nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> résolution    &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row ">
                <div class="col-lg-12">
                    <select class="form-control" name="dpi">
                        <option value="na" <?php echo $this->input['dpi'] == 'na' ? 'selected' : '' ?> >non-défini</option>
                        <option value="200" <?php echo $this->input['dpi'] == '200' ? 'selected' : '' ?> >200dpi
                        </option>
                        <option value="300" <?php echo $this->input['dpi'] == '300' ? 'selected' : '' ?> >300dpi
                        </option>
                        <option value="600" <?php echo $this->input['dpi'] == '600' ? "selected" : '' ?> >600dpi
                        </option>
                        <option value="1200" <?php echo $this->input['dpi'] == '1200' ? "selected" : '' ?> >1200dpi
                        </option>
                    </select>
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-sm-8 col-xs-12 ">
            <div class="row">
                <div class="col-lg-12 visible-md visible-lg visible-sm">
                    <?php if ($this->input['width'] <> 'na' && $this->input['width'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            largeur impression</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> largeur impression   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
                <div class="col-lg-12 visible-xs">
                    <?php if ($this->input['width'] <> 'na' && $this->input['width'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            largeur</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> largeur
                                                                                      &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row ">
                <div class="col-lg-12 col-sm-12">
                    <select class="form-control" name="width">
                        <option <?php echo $this->input['width'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                        <option <?php echo $this->input['width'] == '4' ? 'selected' : '' ?> value="4">4" (116mm) </option>
                        <option <?php echo $this->input['width'] == '6' ? 'selected' : '' ?> value="6">6" (152mm) </option>
                        <option <?php echo $this->input['width'] == '8' ? 'selected' : '' ?> value="8">8" (203mm) </option>
                        <option <?php echo $this->input['width'] == '2' ? 'selected' : '' ?> value="2">2" (50mm) </option>
                        <option <?php echo $this->input['width'] == '3' ? 'selected' : '' ?> value="3">3" (76mm) </option>
                        <option <?php echo $this->input['width'] == '5' ? 'selected' : '' ?> value="5">5" (127mm) </option>
                    </select>
                </div>
            </div>
        </div>
        <div class="hidden-lg form-section-sm">&nbsp;</div>
        <div class="col-lg-4 col-sm-12 col-xs-12 ">
            <div class="row ">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <?php if ($this->input['gamme'] <> 'na' && $this->input['gamme'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            gamme</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px "> </i> gamme
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>

                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <select class="form-control" name="gamme">
                        <option <?php echo $this->input['gamme'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                        <option <?php echo $this->input['gamme'] == 'bureau' ? 'selected' : '' ?> value="bureau">
                            bureau
                        </option>
                        <option <?php echo $this->input['gamme'] == 'si' ? 'selected' : '' ?> value="si">
                            semi-Industrielle
                        </option>
                        <option <?php echo $this->input['gamme'] == 'i' ? 'selected' : '' ?> value="i">industrielle
                        </option>
                    </select>
                </div>
            </div>
        </div>
    </div>


    <div class=" row ">

        <!--MARQUES-->
        <div class="col-lg-4 col-sm-6 col-xs-12">
            <div class="row">
                <div class="col-lg-12">
                    <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            marques</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> marques   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row form-section">
                <div class="col-lg-12">
                    <select class="form-control" name="marque">
                        <option <?php echo $this->input['marque'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                        <option <?php echo $this->input['marque'] == 'm_zebra' ? 'selected' : '' ?> value="m_zebra"> zebra </option>
                        <option <?php echo $this->input['marque'] == 'm_datamax' ? 'selected' : '' ?> value="m_datamax"> datamax </option>
                        <option <?php echo $this->input['marque'] == 'm_intermec' ? 'selected' : '' ?> value="m_intermec">intermec </option>
                        <option <?php echo $this->input['marque'] == 'm_toshiba' ? 'selected' : '' ?> value="m_toshiba">toshiba - tec </option>
                        <option <?php echo $this->input['marque'] == 'm_honeywell' ? 'selected' : '' ?> value="m_honeywell">honeywell </option>
                        <option <?php echo $this->input['marque'] == 'all' ? 'selected' : '' ?> value="all">toutes marques </option>
                    </select>
                </div>
            </div>
        </div>
        <!--MARQUES-->

        <!--UTILISATION-->
        <div class="col-lg-4 col-sm-6 col-xs-12">
            <div class="row">
                <div class="col-lg-12">
                    <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            utilisation</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> utilisation   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row form-section">
                <div class="col-lg-12">
                    <select class="form-control" name="use">
                        <option <?php echo $this->input['use'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                        <option <?php echo $this->input['use'] == 'tt' ? 'selected' : '' ?> value="tt">transfert
                            thermique
                        </option>
                        <option <?php echo $this->input['use'] == 'dt' ? 'selected' : '' ?> value="dt">direct
                            thermique
                        </option>
                        <option <?php echo $this->input['use'] == 'both' ? 'selected' : '' ?> value="both">
                            les deux
                        </option>

                    </select>
                </div>
            </div>
        </div>
        <!--UTILISATION-->

        <!--OPTION-->
        <div class="col-lg-4 col-sm-6 col-xs-12">
            <div class="row">
                <div class="col-lg-12">
                    <?php if ($this->input['opt'] <> 'na' && $this->input['opt'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            options</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> options   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <select class="form-control" name="opt">
                        <option <?php echo $this->input['opt'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                        <option <?php echo $this->input['opt'] == 'cut' ? 'selected' : '' ?> value="cut">massicot /
                            cutter
                        </option>
                        <option <?php echo $this->input['opt'] == 'peel' ? 'selected' : '' ?> value="peel">
                            prédecollage
                        </option>
                        <option <?php echo $this->input['opt'] == 'rewind' ? 'selected' : '' ?> value="rewind">
                            pré-imprimer
                        </option>
                        <option <?php echo $this->input['opt'] == 'rfid' ? 'selected' : '' ?> value="rfid">rfid</option>
                    </select>
                </div>
            </div>
        </div>
        <!--OPTION-->

        <div class="row visible-xs visible-sm visible-md " >&nbsp;</div>

    </div>
    <div class="form-section row ">

        <!--INTERFACE-->
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            interface de connection</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i>  interface de connection   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input
                                    id="noborder"
                                <?php echo isset($this->input['interface']['bluetooh']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="interfacep[]" value="bluetooh">
                            bluetooh
                        </label>
                    </div>
                </div>

                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input
                                    class="checknoshadow"
                                    id="noborder"
                                <?php echo isset($this->input['interface']['serie']) ? 'checked' : '' ?> type="checkbox"
                                    name="interfacep[]" value="serie">
                            série
                        </label>
                    </div>
                </div>

                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['parra']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="interfacep[]" value="parra">
                            parralléle
                        </label>
                    </div>
                </div>

                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['usb']) ? "checked" : '' ;?>
                                    type="checkbox"
                                    class="checknoshadow"
                                    name="interfacep[]"
                                    value="usb">
                            usb
                        </label>
                    </div>
                </div>

                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['eth']) ? "checked" : '' ;?>
                                    type="checkbox"
                                    class="checknoshadow"
                                    name="interfacep[]"
                                    value="eth">
                            réseau
                        </label>
                    </div>
                </div>

                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['wifi']) ? "checked" : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="interfacep[]" value="wifi">
                            wifi
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <!--UTILISATION-->
    </div>

    <!--CONSO ET SOFTWARE-->
    <div class="row ">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if ( ($this->input['conso'] <> 'na' && $this->input['conso'] <> null) || $this->input['dimension'] <> ''): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            consommable et soft</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i>  consommable & soft   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row">
                <div class="center col-lg-3 col-md-4 col-sm-12 col-xs-12">
                    <div class="checkbox">
                        <label>
                            <input
                                    name="dimension"
                                   type="text"
                                   placeholder="largeur x hauteur (en mm)"
                                    value="<?php echo isset($this->input['dimension']) ? $this->input['dimension'] : '' ;?>"
                            >
                        </label>
                    </div>
                </div>

                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['conso']['ruban']) ? "checked" : '' ;?>
                                    type="checkbox"
                                    class="checknoshadow"
                                    name="conso[]"
                                    value="ruban">
                            ruban
                        </label>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['conso']['software']) ? "checked" : '' ;?>
                                    type="checkbox"
                                    class="checknoshadow"
                                    name="conso[]"
                                    value="software">
                            logicièl d'édition étiquette
                        </label>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['conso']['printhead']) ? "checked" : '' ;?>
                                    type="checkbox"
                                    class="checknoshadow"
                                    name="conso[]"
                                    value="printhead">
                            tête d'impression supplémentaire
                        </label>
                    </div>
                </div>

            </div>
        </div>

    </div>
    <!--CONSO ET SOFTWARE-->

    <!--BOUTTON DE VALIDATION-->
    <div class="row" >
        <div class="col-lg-8 col-sm-6 col-xs-12" >
            <input type="submit" class="btn btn-euro-blue " value="filtrer">
        </div>

        <div class="col-lg-4 col-sm-6 col-xs-12" >
            <a href="filtre/delete" class="btn btn-euro-pink"
            >reset</a>
        </div>
    </div>
    <!--BOUTTON DE VALIDATION-->
</form>