<form action="/filtre/apply" method="post"
      class="wrapper_form-filtre"
>
    <div class="row " >

        <div class="hidden-xs col-lg-6 col-md-8 col-sm-10 h2 ">
            <b>Imprimantes etiquette - COULEUR</b>
        </div>

        <div class="hidden-sm hidden-md hidden-lg col-lg-6 col-md-6 col-sm-8 col-xs-8">
            <b>Imprimantes etiquette - COULEUR</b>
        </div>

        <!--<div class="hidden-lg hidden-md form-section-sm">&nbsp;</div>-->
        <div class="hidden-xs col-lg-10 col-md-4 col-sm-2 h2 ">
            <?php include('aide_imprimante_couleur.phtml') ?>
        </div>

        <div class="hidden-sm hidden-md hidden-lg col-lg-2 col-md-4 col-sm-4 col-xs-4 small">
            <?php include('aide_imprimante_couleur.phtml') ?>
        </div>
    </div>
    <br>

    <div class="row">
        <div class="col-lg-12">
            <?php
            //var_dump($this->search) ;
            //var_dump($this->input) ;
            ?>
        </div>
    </div>
    <div class="row form-section">

        <!--MARQUE-->
        <div class="col-lg-4 col-sm-12 col-xs-12 hidden">
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Marques</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px "> </i> Marques
                                                                                       &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>

                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <select class="form-control" name="marque">
                        <option <?php echo $this->input['marque'] == 'na' ? 'selected' : '' ?> value="na">Non-défini</option>
                        <option <?php echo $this->input['marque'] == 'm_citizen' ? 'selected' : '' ?> value="m_citizen"> Citizen </option>
                        <option <?php echo $this->input['marque'] == 'm_epson' ? 'selected' : '' ?> value="m_epson"> Epson </option>
                        <option <?php echo $this->input['marque'] == 'all' ? 'selected' : '' ?> value="all">Toutes marques </option>
                    </select>
                </div>
            </div>
        </div>
        <!-- FIN MARQUE-->

        <!--RESOLUTION -->
        <div class="col-lg-6 col-sm-6 col-xs-12">
            <div class="row">
                <div class="col-xs-12 col-lg-12">
                    <?php if ($this->input['dpi'] <> 'na' && $this->input['dpi'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Résolution </b> &nbsp;&nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Résolution    &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>

                    <?php endif ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <select class="form-control" name="dpi">
                        <option value="na" <?php echo $this->input['dpi'] == 'na' ? 'selected' : '' ?> >Non-défini</option>
                        <option value="300" <?php echo $this->input['dpi'] == '300' ? 'selected' : '' ?> >300dpi </option>
                        <option value="600" <?php echo $this->input['dpi'] == '600' ? "selected" : '' ?> >600dpi </option>
                        <option value="1200" <?php echo $this->input['dpi'] == '1200' ? "selected" : '' ?> >1200dpi </option>
                    </select>
                </div>
            </div>
        </div>
        <!--FIN RESOLUTION-->
        <div class="hidden-lg hidden-md hidden-sm  form-section-sm">&nbsp;</div>
        <!--LARGEUR-->
        <div class="col-lg-6 col-sm-6 col-xs-12">
            <div class="row">
                <div class="col-lg-12 visible-md visible-lg visible-sm">
                    <?php if ($this->input['width'] <> 'na' && $this->input['width'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Largeur impression</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Largeur impression   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
                <div class="col-lg-12 visible-xs">
                    <?php if ($this->input['width'] <> 'na' && $this->input['width'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Largeur</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Largeur
                                                                                      &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12">
                    <select class="form-control" name="width">
                        <option <?php echo $this->input['width'] == 'na' ? 'selected' : '' ?> value="na">Non-défini</option>
                        <option <?php echo $this->input['width'] == '4' ? 'selected' : '' ?> value="4">4" (116mm) </option>
                        <option <?php echo $this->input['width'] == '6' ? 'selected' : '' ?> value="6">6" (152mm) </option>
                        <option <?php echo $this->input['width'] == '8' ? 'selected' : '' ?> value="8">8" (203mm) </option>
                    </select>
                </div>
            </div>
        </div>
        <!--LARGEUR-->

    </div>
    <div class="row form-section">

        <!--INTERFACE-->
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Interface de connection</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i>  Interface de connection   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row">
                <!--PARRALLELE-->
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['parra']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="interfacep[]" value="parra">
                            Parralléle
                        </label>
                    </div>
                </div>

                <!--USB-->
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['usb']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="interfacep[]" value="usb">
                            Usb
                        </label>
                    </div>
                </div>

                <!--RESEAU / ETH -->
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['eth']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="interfacep[]" value="eth">
                            Réseau
                        </label>
                    </div>
                </div>

            </div>

        </div>
        <!--UTILISATION-->

    </div>
    <!--BOUTTON DE VALIDATION-->
    <div class="row" style="padding-top: 10px">
        <div class="col-lg-8 col-sm-8 col-xs-8">
            <input type="submit" class="btn btn-euro-blue " value="Filtrer">
        </div>

        <div class="col-lg-4 col-sm-4 col-xs-4">
            <a href="filtre/delete" class="btn btn-euro-pink"
            >Reset</a>
        </div>
    </div>
    <!--BOUTTON DE VALIDATION-->
</form>