<?php
$menus = Genius_Model_Menu::getAllMenus();
$seo = new Genius_Class_Seo();
$frontController = Zend_Controller_Front::getInstance();
$controller_name = $frontController->getRequest()->getControllerName();

$page = Genius_Model_Page::getPageByCategoryAndIdOptimize(1);
$images_home = Genius_Model_Image::getHomeImageCoverById(18, 1);
$menus_ = Genius_Class_Seo::getMetasMenu(1);
?>

<!--COLONNE SIDE BAR CONFIGURATOR-->
<div class="sidebar-container " >
    <br>
    <section>
        <div class="row" style="padding-left: 15px;padding-right: 15px">
            <div class="col-lg-12" >
                <?php echo $this->render($this->search); ?>
            </div>
        </div>
    </section>
    <div class="col-lg-12  wrapper-col-configurator">
        <!--CONFIGURATOR-->
        <div class="row ">
            <div class="col-lg-12">
                <?php echo $this->render($this->filter); ?>
            </div>
        </div>
        <!--FIN CONFIGURATOR-->
        <br>
        <?php if($this->choice > 0) :?>
            <section class="iconepannier">
                <div class="row ">
                    <div class="col-lg-12" >
                            <a href="/configurateur/pannier">
                                <div class="col-lg-12 alert-info boxPannier text-center">
                                    <i class="fa fa-shopping-cart "> </i> <b>&nbsp;Pannier&nbsp;&nbsp;</b>
                                    <span class="bulle-pannier" id="pannierValue"><?php echo $this->choice ?></span>
                                </div>
                            </a>
                    </div>
                </div>
            </section>
        <?php endif ?>
        <br>
        <!--BOX EXPLICATION CONFIGURATOR-->
        <div class="row ">
            <div class="col-lg-12 ">
                <?php echo $this->render($this->configurateur); ?>
                <br>
            </div>
        </div>
        <!--FIN BOX EXPLICATION CONFIGURATOR-->
    </div>
</div>
<!--FIN COLONNE SIDE BAR CONFIGURATOR-->


<!--COLONNE CONTENU PRINCIPAL-->
<div class="section-container section margin-top-clean">
    <br>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
        <div class="container">
            <?php if($this->choice > 0) :?>
            <section class="iconepannier">
                <div class="row ">
                    <div class="col-lg-12" >
                        <?php echo $this->render($this->pannier); ?>
                    </div>
                </div>
            </section>
            <?php endif ?>
            
            <section class="  ">
                <div class="row ">
                    <div class="col-lg-12">
                        <?php include('aide.phtml') ?>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
<!--FIN COLONNE CONTENU PRINCIPAL-->


<script src="<?php echo URL_DEFAULT_JS; ?>jquery.1.8.3.min.js"></script>

<script type="text/javascript">
</script>

<style>
    .texte_video ul li {
        list-style: inherit !important
    }

    .btn_video {
        display: inline-block;
        margin-top: 20px !important;
        font-size: 16px;
    }

    #h1_home {
        font-weight: bold;
        line-height: 160%;
        margin-bottom: 15px;
        font-family: 'Open Sans', sans-serif, Arial;
        text-align: left;
        font-size: 15px;
        color: #464646;
    }
</style>


