<?php
$menus = Genius_Model_Menu::getAllMenus();
$seo = new Genius_Class_Seo();
$frontController = Zend_Controller_Front::getInstance();
$controller_name = $frontController->getRequest()->getControllerName();

$page = Genius_Model_Page::getPageByCategoryAndIdOptimize(1);
$images_home = Genius_Model_Image::getHomeImageCoverById(18, 1);
$menus_ = Genius_Class_Seo::getMetasMenu(1);
?>

<!--COLONNE SIDE BAR CONFIGURATOR-->
<div class="sidebar-container " >
    <br>
    <section>
        <div class="row" style="padding-left: 15px;padding-right: 15px">
            <div class="col-lg-12" >
                <?php echo $this->render($this->search); ?>
            </div>
        </div>
    </section>
    <div class="col-lg-12  wrapper-col-configurator">
        <!--CONFIGURATOR-->
        <div class="row ">
            <div class="col-lg-12">
                <?php echo $this->render($this->filter); ?>
            </div>
        </div>
        <!--FIN CONFIGURATOR-->
        <br>
        
        <!--BOX EXPLICATION CONFIGURATOR-->
        <div class="row ">
            <div class="col-lg-12 ">
                <?php include('explication_configurator.phtml') ?>
                <br>
            </div>
        </div>
        <!--FIN BOX EXPLICATION CONFIGURATOR-->
    </div>
</div>
<!--FIN COLONNE SIDE BAR CONFIGURATOR-->


<!--COLONNE CONTENU PRINCIPAL-->
<div class="section-container section margin-top-clean">

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">

        <!--BLOC CONTENT-->
        <section class="">
            <div class="row hidden">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 right">
                    <h1 class="right hidden-lg hidden-md hidden-sm">XSMALL</h1>
                    <h1 class="right hidden-lg hidden-md hidden-xs">SMALL</h1>
                    <h1 class="right hidden-lg hidden-xs hidden-sm">MEDIUM</h1>
                    <h1 class="right hidden-xs hidden-md hidden-sm">LARGE</h1>
                </div>
            </div>
        </section>

        <section class="">
            <div class="container">

                <br>
                <div class="row" >
                    <div class="col-lg-12 col-md-12">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col_blogPost">
                                <h1> <i class="fa fa-info-circle"> </i> AIDE AU CONFIGURATEUR</h1>

                                <div class="divider"></div>

                                <div class="blogPost">
                                    <?php include("form_printer_thermique.phtml") ?>

                                    <?php if(isset($this->search))
                                    {
                                        if($this->search == 'search_thermique')  include("form_printer_thermique.phtml");
                                        if($this->search == 'search_etiquette_badgeuse')  include("form_printer_badgeuse.phtml");
                                        if($this->search == 'search_etiquette_couleur')  include("form_printer_couleur.phtml");
                                        if($this->search == 'search_etiquette_portable')  include("form_printer_portative.phtml");

                                        if($this->search == 'search_printer_laser')  include("form_printer_laser.phtml");

                                        if($this->search == 'search_printer_matricielle')  include("form_printer_matricielle.phtml");

                                        elseif($this->search == 'search_douchette')  include("form_douchette.phtml");
                                        elseif($this->search == 'search_douchette_ring')  include("form_douchette_ring.phtml");
                                        elseif($this->search == 'search_douchette_fixe')  include("form_douchette_fixe.phtml");

                                        elseif($this->search == 'search_terminal')  include("form_terminal.phtml");
                                        elseif($this->search == 'search_terminal_pda')  include("form_terminal_pda.phtml");
                                        elseif($this->search == 'search_terminal_embarque')  include("form_terminal_embarque.phtml");
                                        elseif($this->search == 'search_terminal_poignet')  include("form_terminal_poignet.phtml");

                                        elseif($this->search == 'search_poste_client')  include("form_poste_client.phtml");
                                        elseif($this->search == 'search_poste_pc')  include("form_poste_pc.phtml");
                                        elseif($this->search == 'search_poste_portable')  include("form_poste_portable.phtml");

                                        else include("form_printer.phtml");
                                    }
                                    else
                                    {
                                        include("form_printer_thermique.phtml");
                                    } ?>

                                    <?php include("result.phtml"); ?>
                                </div>
                            </div>
                        </div>
                        <!-- end row -->
                    </div>
                    <!-- end col -->

                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
            <!-- end container -->






        </section>

    </div>
</div>
<!--FIN COLONNE CONTENU PRINCIPAL-->





<style>
    .texte_video ul li {
        list-style: inherit !important
    }

    .btn_video {
        display: inline-block;
        margin-top: 20px !important;
        font-size: 16px;
    }

    #h1_home {
        font-weight: bold;
        line-height: 160%;
        margin-bottom: 15px;
        font-family: 'Open Sans', sans-serif, Arial;
        text-align: left;
        font-size: 15px;
        color: #464646;
    }
</style>


