<?php
$menus = Genius_Model_Menu::getAllMenus();
$seo = new Genius_Class_Seo();
$frontController = Zend_Controller_Front::getInstance();
$controller_name = $frontController->getRequest()->getControllerName();

$page = Genius_Model_Page::getPageByCategoryAndIdOptimize(1);
$images_home = Genius_Model_Image::getHomeImageCoverById(18, 1);
$menus_ = Genius_Class_Seo::getMetasMenu(1);
?>

<section>
        <div class="col-lg-12">
            <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
            <h1>HELLO WORLD</h1>
        </div>
</section>
