<section style="padding: 30px;">
    <h1>liste du tracker </h1>

    <table class="table">

        <tbody style="width: ">
        <?php foreach ($this->users as $ip => $users): ?>
            <?php array_reverse ($users ) ?>
            <tr style="border-bottom: 1px solid lightgrey" >
                <td colspan="7">
                    <b style="font-size: 2em"><?php echo $ip ?></b>
                    <br>

                    <?php foreach ($users as $index => $user): ?>

                        <tr>
                            <td><?php echo $user['id'] ?></td>
                            <td><?php echo $user['ip'] ?></td>
                            <td><?php echo strtoupper($user['module']) ?></td>
                            <td><?php echo $user['value'] ?></td>
                            <td><?php echo $user['spec'] ?></td>
                            <td><?php echo $user['url'] ?></td>
                            <td width="200px"><?php echo $user['created_at'] ?></td>
                        </tr>
                    <?php endforeach ?>
                </td>
            </tr>
        <?php  endforeach;?>
        </tbody>
    </table>
</section>