<!-- Content wrapper -->
<div class="wrapper ">

    <?php echo Genius_Class_Snippets::breadcrumb($this->translate('Configuration du site'), '/admin/siteconfiguration'); ?>

    <!-- Page header -->
    <div class="page-header">
        <div class="page-title">
            <h2><?php echo $this->translate('CLIENT LEGER DANS BASE DE DONNEE'); ?></h2>
        </div>
    </div>
    <!-- /page header -->

    <div class="line"></div>

    <?php
    if (!empty($this->configs)) {
        $configs = $this->configs[0];
        ?>
        <div class="span12">
            <form method="post" action="" id="configure-form" class="form-horizontal form-to-validate">
                <input type="hidden" value="1" id="id" name="SiteConfiguration[id]">

                <fieldset>
                    <div class="widget row-fluid mt30">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><?php echo $this->translate('Informations générales'); ?></h6>
                            </div>
                        </div>

                        <div class="well">
                            <div class="control-group">
                                <label class="control-label" for="siteweb"><span class="text-error">*</span>
                                    Website:</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['siteweb']; ?>" id="siteweb"
                                                             class="validate[required]"
                                                             name="SiteConfiguration[siteweb]"/></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="adresse"><span class="text-error">*</span> Adresse
                                    :</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['adresse']; ?>" id="adresse"
                                                             name="SiteConfiguration[adresse]"/></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="email"><span class="text-error">*</span>
                                    Email:</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['email']; ?>" id="email"
                                                             class="validate[required,custom[email]]"
                                                             name="SiteConfiguration[email]"/></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="phone"><span class="text-error">*</span> Téléphone
                                    :</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['phone']; ?>" id="phone"
                                                             name="SiteConfiguration[phone]"/></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="fax"><span class="text-error">*</span> Fax :</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['fax']; ?>" id="fax"
                                                             name="SiteConfiguration[fax]"/></div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="title"><span class="text-error">*</span>
                                    Title:</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['title']; ?>" id="title"
                                                             name="SiteConfiguration[title]" class="validate[required]">
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="slogan">Catchword:</label>
                                <div class="controls"><input type="text" class="span12"
                                                             value="<?php echo $configs['slogan']; ?>" id="slogan"
                                                             name="SiteConfiguration[slogan]"/></div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="transition_slider">Transition slider :
                                    (millisec)</label>
                                <div class="controls"><input type="text" class="span12"
                                                             value="<?php echo $configs['transition_slider']; ?>"
                                                             id="transition_slider"
                                                             name="SiteConfiguration[transition_slider]"/></div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="pause_slider">Pause Slider : (millisec)</label>
                                <div class="controls"><input type="text" class="span12"
                                                             value="<?php echo $configs['pause_slider']; ?>"
                                                             id="pause_slider" name="SiteConfiguration[pause_slider]"/>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="widget row-fluid mt30">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><?php echo $this->translate('Mode maintenance'); ?></h6>
                            </div>
                        </div>

                        <div class="well">
                            <div class="control-group">
                                <label class="control-label" for="mode_maintenance"> Mode maintenance:</label>
                                <div class="controls">
                                    <select class="styled" name="SiteConfiguration[mode_maintenance]"
                                            style="opacity: 0;">
                                        <option value="0" <?php echo ($configs['mode_maintenance'] == 0) ? 'selected="selected"' : ''; ?>>
                                            <?php echo $this->translate('Non'); ?>
                                        </option>

                                        <option value="1" <?php echo ($configs['mode_maintenance'] == 1) ? 'selected="selected"' : ''; ?>>
                                            <?php echo $this->translate('Oui'); ?>
                                        </option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>

                <div class="line mt30"></div>

                <div class="form-actions align-left nobordertop form-actions-bg">
                    <button class="btn btn-primary"
                            type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
                </div>

                <div class="line mb30"></div>
            </form>
        </div>
    <?php } ?>
    <br>
    <?php if (count($this->paginator)): ?>
        <table id="all" class="table table-bordered " style="font-size: 0.90em; ">
            <thead>
            <tr>
                <th class="borderr2" colspan="1">-</th>
                <th class="borderr2" colspan="3">marque</th>
                <th class="borderr2" colspan="3">Os</th>
                <th class="borderr2" colspan="2">Options</th>
                <th class="borderr2" colspan="4">Ram</th>
                <th class="borderr2" colspan="6">Flash</th>
                <th class="borderr2" colspan="5">écran</th>
                <th class="" colspan="4">Visibilité</th>
            </tr>
            </thead>
            <thead>
            <tr class="tr-hover">
                <th class="center borderr2">Nom</th>

                <th class="center ">del - wyse</th>
                <th class="center ">hp</th>
                <th class="center borderr2">axel</th>

                <th class="center ">win</th>
                <th class="center ">linux</th>
                <th class="center borderr2">propri</th>

                <th class="center ">wifi</th>
                <th class="center  borderr2">dual display</th>

                <th class="center ">2gb</th>
                <th class="center ">4gb</th>
                <th class="center ">8gb</th>
                <th class="center borderr2">16gb</th>


                <th class="center ">2gb</th>
                <th class="center ">4gb</th>
                <th class="center ">8gb</th>
                <th class="center ">16gb</th>
                <th class="center ">32gb</th>
                <th class="center borderr2">64gb</th>

                <th class="center ">17"</th>
                <th class="center ">19" 4/3</th>
                <th class="center ">19" 16/9</th>
                <th class="center ">22"</th>
                <th class="center borderr2">24"</th>

                <th class="center ">top</th>
                <th class="center ">stock</th>
                <th class="center ">visible</th>
                <th class="center ">pertinence</th>
            </tr>
            </thead>

            <tbody>
            <?php foreach ($this->paginator as $index => $item): ?>
                <tr>

                    <td class="center borderr2">
                        <a href="">
                            <?php echo $item['nom']; ?>

                        </a>
                    </td>

                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/dell/id/<?php echo $item['id'] ?>/val/<?php echo $item['dell'] ?>">
                            <?php echo $item['dell'] == 0 ? '0' : $item['dell']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/hp/id/<?php echo $item['id'] ?>/val/<?php echo $item['hp'] ?>">
                            <?php echo $item['hp'] == 0 ? '0' : $item['hp']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/axel/id/<?php echo $item['id'] ?>/val/<?php echo $item['axel'] ?>">
                            <?php echo $item['axel'] == 0 ? '0' : $item['axel']; ?>
                        </a>
                    </td>


                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/win/id/<?php echo $item['id'] ?>/val/<?php echo $item['win'] ?>">
                            <?php echo $item['win'] == 0 ? '0' : $item['win']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/linux/id/<?php echo $item['id'] ?>/val/<?php echo $item['linux'] ?>">
                            <?php echo $item['linux'] == 0 ? '0' : $item['linux']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/propri/id/<?php echo $item['id'] ?>/val/<?php echo $item['propri'] ?>">
                            <?php echo $item['propri'] == 0 ? '0' : $item['propri']; ?>
                        </a>
                    </td>


                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/wifi/id/<?php echo $item['id'] ?>/val/<?php echo $item['wifi'] ?>">
                            <?php echo $item['wifi'] == 0 ? '0' : $item['wifi']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/dual_display/id/<?php echo $item['id'] ?>/val/<?php echo $item['dual_display'] ?>">
                            <?php echo $item['dual_display'] == 0 ? '0' : $item['dual_display']; ?>
                        </a>
                    </td>

                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/2gb_ram/id/<?php echo $item['id'] ?>/val/<?php echo $item['2gb_ram'] ?>">
                            <?php echo $item['2gb_ram'] == 0 ? '0' : $item['2gb_ram']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/4gb_ram/id/<?php echo $item['id'] ?>/val/<?php echo $item['4gb_ram'] ?>">
                            <?php echo $item['4gb_ram'] == 0 ? '0' : $item['4gb_ram']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/8gb_ram/id/<?php echo $item['id'] ?>/val/<?php echo $item['8gb_ram'] ?>">
                            <?php echo $item['8gb_ram'] == 0 ? '0' : $item['8gb_ram']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/16gb_ram/id/<?php echo $item['id'] ?>/val/<?php echo $item['16gb_ram'] ?>">
                            <?php echo $item['16gb_ram'] == 0 ? '0' : $item['16gb_ram']; ?>
                        </a>
                    </td>



                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/2gb_flash/id/<?php echo $item['id'] ?>/val/<?php echo $item['2gb_flash'] ?>">
                            <?php echo $item['2gb_flash'] == 0 ? '0' : $item['2gb_flash']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/4gb_flash/id/<?php echo $item['id'] ?>/val/<?php echo $item['4gb_flash'] ?>">
                            <?php echo $item['4gb_flash'] == 0 ? '0' : $item['4gb_flash']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/8gb_flash/id/<?php echo $item['id'] ?>/val/<?php echo $item['8gb_flash'] ?>">
                            <?php echo $item['8gb_flash'] == 0 ? '0' : $item['8gb_flash']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/16gb_flash/id/<?php echo $item['id'] ?>/val/<?php echo $item['16gb_flash'] ?>">
                            <?php echo $item['16gb_flash'] == 0 ? '0' : $item['16gb_flash']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/32gb_flash/id/<?php echo $item['id'] ?>/val/<?php echo $item['32gb_flash'] ?>">
                            <?php echo $item['32gb_flash'] == 0 ? '0' : $item['32gb_flash']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/64gb_flash/id/<?php echo $item['id'] ?>/val/<?php echo $item['64gb_flash'] ?>">
                            <?php echo $item['64gb_flash'] == 0 ? '0' : $item['64gb_flash']; ?>
                        </a>
                    </td>



                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/17p/id/<?php echo $item['id'] ?>/val/<?php echo $item['17p'] ?>">
                            <?php echo $item['17p'] == 0 ? '0' : $item['17p']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/19p_4/id/<?php echo $item['id'] ?>/val/<?php echo $item['19p_4'] ?>">
                            <?php echo $item['19p_4'] == 0 ? '0' : $item['19p_4']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/19p_16/id/<?php echo $item['id'] ?>/val/<?php echo $item['19p_16'] ?>">
                            <?php echo $item['19p_16'] == 0 ? '0' : $item['19p_16']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/22p/id/<?php echo $item['id'] ?>/val/<?php echo $item['22p'] ?>">
                            <?php echo $item['22p'] == 0 ? '0' : $item['22p']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/24p/id/<?php echo $item['id'] ?>/val/<?php echo $item['24p'] ?>">
                            <?php echo $item['24p'] == 0 ? '0' : $item['24p']; ?>
                        </a>
                    </td>


                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/top/id/<?php echo $item['id'] ?>/val/<?php echo $item['top'] ?>">
                            <?php echo $item['top'] == 0 ? '0' : $item['top']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/stock/id/<?php echo $item['id'] ?>/val/<?php echo $item['stock'] ?>">
                            <?php echo $item['stock'] == 0 ? '0' : $item['stock']; ?>
                        </a>
                    </td>

                    <td class="center ">
                        <a
                                href="/admin/filtreposteclient/update/p/<?php echo $this->current ?>/n/visible/id/<?php echo $item['id'] ?>/val/<?php echo $item['visible'] ?>">
                            <?php echo $item['visible'] == 0 ? '0' : $item['visible']; ?>
                        </a>
                    </td>

                    <td class="center " style="width: 5%">
                        <form action="/admin/filtreposteclient/post" method="POST">
                            <input name="id_" type="hidden" value="<?php echo $item['id'] ?>">
                            <input name="page_" type="hidden" value="<?php echo $this->current ?>">
                            <input id="small" type="number" name="pertinence" value="<?php echo $item['pertinence'] == null ? 0 : $item['pertinence'] ?>">
                        </form>
                    </td>

                </tr>
            <?php endforeach; ?>

            </tbody>

        </table>
    <?php endif; ?>

    <br><br><br><br>

</div>

<div class="right">
    <div class="paginate">
        <?php if ($i == $this->previous < 1) : ?>
            <a href="/admin/filtreposteclient/all/page/<?php echo $this->previous ?>" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        <?php else : ?>
            <a href="" aria-label="Previous">
                <span aria-hidden="true">x</span>
            </a>

        <?php endif ?>


        <?php for ($i = 1; $i <= $this->total; $i++): ?>
            <?php if ($i == $this->current) : ?>
                <a href="#" class="active"><?php echo $i ?></a>
            <?php else : ?>
                <a href="/admin/filtreposteclient/all/page/<?php echo $i ?>"><?php echo $i ?></a>
            <?php endif ?>
        <?php endfor ?>

        <?php if ($i == $this->next <= $this->total) : ?>
            <a href="/admin/filtreposteclient/all/page/<?php echo $this->next ?>" aria-label="Previous">
                <span aria-hidden="true">&raquo;</span>
            </a>
        <?php else : ?>
            <a href="" aria-label="next">
                <span aria-hidden="true">x</span>
            </a>

        <?php endif ?>

    </div>
</div>
<!-- /content wrapper -->
<link href="<?php echo URL_DEFAULT_CSS; ?>geo/css/app_admin.css" rel="stylesheet" type="text/css" media="all"/>