<!-- Content wrapper -->
<div class="wrapper ">

    <?php echo Genius_Class_Snippets::breadcrumb($this->translate('Configuration du site'), '/admin/siteconfiguration'); ?>

    <!-- Page header -->
    <div class="page-header">
        <div class="page-title">
            <h2><?php echo $this->translate('POSTE BUREAU DANS BASE DE DONNEE'); ?></h2>
        </div>
    </div>
    <!-- /page header -->

    <div class="line"></div>

    <?php
    if (!empty($this->configs)) {
        $configs = $this->configs[0];
        ?>
        <div class="span12">
            <form method="post" action="" id="configure-form" class="form-horizontal form-to-validate">
                <input type="hidden" value="1" id="id" name="SiteConfiguration[id]">

                <fieldset>
                    <div class="widget row-fluid mt30">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><?php echo $this->translate('Informations générales'); ?></h6>
                            </div>
                        </div>

                        <div class="well">
                            <div class="control-group">
                                <label class="control-label" for="siteweb"><span class="text-error">*</span>
                                    Website:</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['siteweb']; ?>" id="siteweb"
                                                             class="validate[required]"
                                                             name="SiteConfiguration[siteweb]"/></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="adresse"><span class="text-error">*</span> Adresse
                                    :</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['adresse']; ?>" id="adresse"
                                                             name="SiteConfiguration[adresse]"/></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="email"><span class="text-error">*</span>
                                    Email:</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['email']; ?>" id="email"
                                                             class="validate[required,custom[email]]"
                                                             name="SiteConfiguration[email]"/></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="phone"><span class="text-error">*</span> Téléphone
                                    :</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['phone']; ?>" id="phone"
                                                             name="SiteConfiguration[phone]"/></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="fax"><span class="text-error">*</span> Fax :</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['fax']; ?>" id="fax"
                                                             name="SiteConfiguration[fax]"/></div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="title"><span class="text-error">*</span>
                                    Title:</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['title']; ?>" id="title"
                                                             name="SiteConfiguration[title]" class="validate[required]">
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="slogan">Catchword:</label>
                                <div class="controls"><input type="text" class="span12"
                                                             value="<?php echo $configs['slogan']; ?>" id="slogan"
                                                             name="SiteConfiguration[slogan]"/></div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="transition_slider">Transition slider :
                                    (millisec)</label>
                                <div class="controls"><input type="text" class="span12"
                                                             value="<?php echo $configs['transition_slider']; ?>"
                                                             id="transition_slider"
                                                             name="SiteConfiguration[transition_slider]"/></div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="pause_slider">Pause Slider : (millisec)</label>
                                <div class="controls"><input type="text" class="span12"
                                                             value="<?php echo $configs['pause_slider']; ?>"
                                                             id="pause_slider" name="SiteConfiguration[pause_slider]"/>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="widget row-fluid mt30">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><?php echo $this->translate('Mode maintenance'); ?></h6>
                            </div>
                        </div>

                        <div class="well">
                            <div class="control-group">
                                <label class="control-label" for="mode_maintenance"> Mode maintenance:</label>
                                <div class="controls">
                                    <select class="styled" name="SiteConfiguration[mode_maintenance]"
                                            style="opacity: 0;">
                                        <option value="0" <?php echo ($configs['mode_maintenance'] == 0) ? 'selected="selected"' : ''; ?>>
                                            <?php echo $this->translate('Non'); ?>
                                        </option>

                                        <option value="1" <?php echo ($configs['mode_maintenance'] == 1) ? 'selected="selected"' : ''; ?>>
                                            <?php echo $this->translate('Oui'); ?>
                                        </option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>

                <div class="line mt30"></div>

                <div class="form-actions align-left nobordertop form-actions-bg">
                    <button class="btn btn-primary"
                            type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
                </div>

                <div class="line mb30"></div>
            </form>
        </div>
    <?php } ?>
    <br>
    <?php if (count($this->paginator)): ?>
        <table id="all" class="table table-bordered " style="font-size: 0.90em; ">
            <thead>
            <tr>
                <th class="borderr2" colspan="1">-</th>
                <th class="borderr2" colspan="3">format</th>
                <th class="borderr2" colspan="3">utilisation</th>
                <th class="borderr2" colspan="3">processeur</th>
                <th class="borderr2" colspan="3">Os</th>
                <th class="borderr2" colspan="3">ram</th>
                <th class="borderr2" colspan="5">disque</th>
                <th class="borderr2" colspan="1">option</th>
                <th class="borderr2" colspan="5">écran</th>
                <th class="" colspan="4">Visibilité</th>
            </tr>
            </thead>
            <thead>
            <tr class="tr-hover">
                <th class="center borderr2">Nom</th>

                <th class="center ">tour</th>
                <th class="center ">sff</th>
                <th class="center borderr2">usff</th>

                <th class="center ">bureau</th>
                <th class="center ">pao</th>
                <th class="center borderr2">cao</th>

                <th class="center ">core i3</th>
                <th class="center  ">core i5</th>
                <th class="center borderr2">core i7</th>

                <th class="center ">win 7 pro</th>
                <th class="center ">win 10 pro</th>
                <th class="center borderr2">win xp pro</th>


                <th class="center ">2gb</th>
                <th class="center ">4gb</th>
                <th class="center borderr2">8gb</th>

                <th class="center ">160gb</th>
                <th class="center ">250gb</th>
                <th class="center ">320gb</th>
                <th class="center ">500gb</th>
                <th class="center borderr2">1TO</th>

                <th class="center borderr2">ssd</th>

                <th class="center ">17"</th>
                <th class="center ">19" 4/3</th>
                <th class="center ">19" 16/9</th>
                <th class="center ">22"</th>
                <th class="center borderr2">24"</th>

                <th class="center ">top</th>
                <th class="center ">stock</th>
                <th class="center ">visible</th>
                <th class="center ">pertinence</th>
            </tr>
            </thead>

            <tbody>
            <?php foreach ($this->paginator as $index => $item): ?>
                <tr>

                    <td class="center borderr2">
                        <a href="">
                            <?php echo $item['name']; ?>

                        </a>
                    </td>

                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/p/<?php echo $this->current ?>/n/tour/id/<?php echo $item['id'] ?>/val/<?php echo $item['tour'] ?>">
                            <?php echo $item['tour'] == 0 ? '0' : $item['tour']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtrepc/update/p/<?php echo $this->current ?>/n/sff/id/<?php echo $item['id'] ?>/val/<?php echo $item['sff'] ?>">
                            <?php echo $item['sff'] == 0 ? '0' : $item['sff']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtrepc/update/p/<?php echo $this->current ?>/n/usff/id/<?php echo $item['id'] ?>/val/<?php echo $item['usff'] ?>">
                            <?php echo $item['usff'] == 0 ? '0' : $item['usff']; ?>
                        </a>
                    </td>

                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/p/<?php echo $this->current ?>/n/bureau/id/<?php echo $item['id'] ?>/val/<?php echo $item['bureau'] ?>">
                            <?php echo $item['bureau'] == 0 ? '0' : $item['bureau']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtrepc/update/p/<?php echo $this->current ?>/n/pao/id/<?php echo $item['id'] ?>/val/<?php echo $item['pao'] ?>">
                            <?php echo $item['pao'] == 0 ? '0' : $item['pao']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtrepc/update/p/<?php echo $this->current ?>/n/cao/id/<?php echo $item['id'] ?>/val/<?php echo $item['cao'] ?>">
                            <?php echo $item['cao'] == 0 ? '0' : $item['cao']; ?>
                        </a>
                    </td>


                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/p/<?php echo $this->current ?>/n/core_i3/id/<?php echo $item['id'] ?>/val/<?php echo $item['core_i3'] ?>">
                            <?php echo $item['core_i3'] == 0 ? '0' : $item['core_i3']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/p/<?php echo $this->current ?>/n/core_i5/id/<?php echo $item['id'] ?>/val/<?php echo $item['core_i5'] ?>">
                            <?php echo $item['core_i5'] == 0 ? '0' : $item['core_i5']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtrepc/update/p/<?php echo $this->current ?>/n/core_i7/id/<?php echo $item['id'] ?>/val/<?php echo $item['core_i7'] ?>">
                            <?php echo $item['core_i7'] == 0 ? '0' : $item['core_i7']; ?>
                        </a>
                    </td>

                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/win_7_pro/id/<?php echo $item['id'] ?>/val/<?php echo $item['win_7_pro'] ?>">
                            <?php echo $item['win_7_pro'] == 0 ? '0' : $item['win_7_pro']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/win_10_pro/id/<?php echo $item['id'] ?>/val/<?php echo $item['win_10_pro'] ?>">
                            <?php echo $item['win_10_pro'] == 0 ? '0' : $item['win_10_pro']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtrepc/update/n/win_cp_pro/id/<?php echo $item['id'] ?>/val/<?php echo $item['win_cp_pro'] ?>">
                            <?php echo $item['win_cp_pro'] == 0 ? '0' : $item['win_cp_pro']; ?>
                        </a>
                    </td>





                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/2gb_ram/id/<?php echo $item['id'] ?>/val/<?php echo $item['2gb_ram'] ?>">
                            <?php echo $item['2gb_ram'] == 0 ? '0' : $item['2gb_ram']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/4gb_ram/id/<?php echo $item['id'] ?>/val/<?php echo $item['4gb_ram'] ?>">
                            <?php echo $item['4gb_ram'] == 0 ? '0' : $item['4gb_ram']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtrepc/update/n/8gb_ram/id/<?php echo $item['id'] ?>/val/<?php echo $item['8gb_ram'] ?>">
                            <?php echo $item['8gb_ram'] == 0 ? '0' : $item['8gb_ram']; ?>
                        </a>
                    </td>


                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/160gb/id/<?php echo $item['id'] ?>/val/<?php echo $item['160gb'] ?>">
                            <?php echo $item['160gb'] == 0 ? '0' : $item['160gb']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/250gb/id/<?php echo $item['id'] ?>/val/<?php echo $item['250gb'] ?>">
                            <?php echo $item['250gb'] == 0 ? '0' : $item['250gb']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/320gb/id/<?php echo $item['id'] ?>/val/<?php echo $item['320gb'] ?>">
                            <?php echo $item['320gb'] == 0 ? '0' : $item['320gb']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/500gb/id/<?php echo $item['id'] ?>/val/<?php echo $item['500gb'] ?>">
                            <?php echo $item['500gb'] == 0 ? '0' : $item['500gb']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a href="/admin/filtrepc/update/n/1000gb/id/<?php echo $item['id'] ?>/val/<?php echo $item['1000gb'] ?>">
                            <?php echo $item['1000gb'] == 0 ? '0' : $item['1000gb']; ?>
                        </a>
                    </td>

                    <td class="center borderr2">
                        <a
                                href="/admin/filtrepc/update/n/ssd/id/<?php echo $item['id'] ?>/val/<?php echo $item['ssd'] ?>">
                            <?php echo $item['ssd'] == 0 ? '0' : $item['ssd']; ?>
                        </a>
                    </td>

                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/17p/id/<?php echo $item['id'] ?>/val/<?php echo $item['17p'] ?>">
                            <?php echo $item['17p'] == 0 ? '0' : $item['17p']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/19p_4/id/<?php echo $item['id'] ?>/val/<?php echo $item['19p_4'] ?>">
                            <?php echo $item['19p_4'] == 0 ? '0' : $item['19p_4']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/19p_16/id/<?php echo $item['id'] ?>/val/<?php echo $item['19p_16'] ?>">
                            <?php echo $item['19p_16'] == 0 ? '0' : $item['19p_16']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/22p/id/<?php echo $item['id'] ?>/val/<?php echo $item['22p'] ?>">
                            <?php echo $item['22p'] == 0 ? '0' : $item['22p']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtrepc/update/n/24p/id/<?php echo $item['id'] ?>/val/<?php echo $item['24p'] ?>">
                            <?php echo $item['24p'] == 0 ? '0' : $item['24p']; ?>
                        </a>
                    </td>


                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/top/id/<?php echo $item['id'] ?>/val/<?php echo $item['top'] ?>">
                            <?php echo $item['top'] == 0 ? '0' : $item['top']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/stock/id/<?php echo $item['id'] ?>/val/<?php echo $item['stock'] ?>">
                            <?php echo $item['stock'] == 0 ? '0' : $item['stock']; ?>
                        </a>
                    </td>

                    <td class="center ">
                        <a
                                href="/admin/filtrepc/update/n/visible/id/<?php echo $item['id'] ?>/val/<?php echo $item['visible'] ?>">
                            <?php echo $item['visible'] == 0 ? '0' : $item['visible']; ?>
                        </a>
                    </td>

                    <td class="center " style="width: 5%">
                        <form action="/admin/filtrepc/post" method="POST">
                            <input name="id_" type="hidden" value="<?php echo $item['id'] ?>">
                            <input name="page_" type="hidden" value="<?php echo $this->current ?>">
                            <input id="small" type="number" name="pertinence" value="<?php echo $item['pertinence'] == null ? 0 : $item['pertinence'] ?>">
                        </form>
                    </td>

                </tr>
            <?php endforeach; ?>

            </tbody>

        </table>
    <?php endif; ?>

    <br><br><br><br>

</div>

<div class="right">
    <div class="paginate">
        <?php if ($i == $this->previous < 1) : ?>
            <a href="/admin/filtrepc/all/page/<?php echo $this->previous ?>" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        <?php else : ?>
            <a href="" aria-label="Previous">
                <span aria-hidden="true">x</span>
            </a>

        <?php endif ?>


        <?php for ($i = 1; $i <= $this->total; $i++): ?>
            <?php if ($i == $this->current) : ?>
                <a href="#" class="active"><?php echo $i ?></a>
            <?php else : ?>
                <a href="/admin/filtrepc/all/page/<?php echo $i ?>"><?php echo $i ?></a>
            <?php endif ?>
        <?php endfor ?>

        <?php if ($i == $this->next <= $this->total) : ?>
            <a href="/admin/filtrepc/all/page/<?php echo $this->next ?>" aria-label="Previous">
                <span aria-hidden="true">&raquo;</span>
            </a>
        <?php else : ?>
            <a href="" aria-label="next">
                <span aria-hidden="true">x</span>
            </a>

        <?php endif ?>

    </div>
</div>
<!-- /content wrapper -->
<link href="<?php echo URL_DEFAULT_CSS; ?>geo/css/app_admin.css" rel="stylesheet" type="text/css" media="all"/>