<!-- Content wrapper -->
<div class="wrapper ">

    <?php echo Genius_Class_Snippets::breadcrumb($this->translate('Configuration du site'), '/admin/siteconfiguration'); ?>

    <!-- Page header -->
    <div class="page-header">
        <div class="page-title">
            <h2><?php echo $this->translate('TERMINAUX EMBARQUE DANS BASE DE DONNEE'); ?></h2>
        </div>
    </div>
    <!-- /page header -->

    <div class="line"></div>

    <?php
    if (!empty($this->configs)) {
        $configs = $this->configs[0];
        ?>
        <div class="span12">
            <form method="post" action="" id="configure-form" class="form-horizontal form-to-validate">
                <input type="hidden" value="1" id="id" name="SiteConfiguration[id]">

                <fieldset>
                    <div class="widget row-fluid mt30">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><?php echo $this->translate('Informations générales'); ?></h6>
                            </div>
                        </div>

                        <div class="well">
                            <div class="control-group">
                                <label class="control-label" for="siteweb"><span class="text-error">*</span>
                                    Website:</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['siteweb']; ?>" id="siteweb"
                                                             class="validate[required]"
                                                             name="SiteConfiguration[siteweb]"/></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="adresse"><span class="text-error">*</span> Adresse
                                    :</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['adresse']; ?>" id="adresse"
                                                             name="SiteConfiguration[adresse]"/></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="email"><span class="text-error">*</span>
                                    Email:</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['email']; ?>" id="email"
                                                             class="validate[required,custom[email]]"
                                                             name="SiteConfiguration[email]"/></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="phone"><span class="text-error">*</span> Téléphone
                                    :</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['phone']; ?>" id="phone"
                                                             name="SiteConfiguration[phone]"/></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="fax"><span class="text-error">*</span> Fax :</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['fax']; ?>" id="fax"
                                                             name="SiteConfiguration[fax]"/></div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="title"><span class="text-error">*</span>
                                    Title:</label>
                                <div class="controls"><input type="text" class="validate[required] span12"
                                                             value="<?php echo $configs['title']; ?>" id="title"
                                                             name="SiteConfiguration[title]" class="validate[required]">
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="slogan">Catchword:</label>
                                <div class="controls"><input type="text" class="span12"
                                                             value="<?php echo $configs['slogan']; ?>" id="slogan"
                                                             name="SiteConfiguration[slogan]"/></div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="transition_slider">Transition slider :
                                    (millisec)</label>
                                <div class="controls"><input type="text" class="span12"
                                                             value="<?php echo $configs['transition_slider']; ?>"
                                                             id="transition_slider"
                                                             name="SiteConfiguration[transition_slider]"/></div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="pause_slider">Pause Slider : (millisec)</label>
                                <div class="controls"><input type="text" class="span12"
                                                             value="<?php echo $configs['pause_slider']; ?>"
                                                             id="pause_slider" name="SiteConfiguration[pause_slider]"/>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="widget row-fluid mt30">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><?php echo $this->translate('Mode maintenance'); ?></h6>
                            </div>
                        </div>

                        <div class="well">
                            <div class="control-group">
                                <label class="control-label" for="mode_maintenance"> Mode maintenance:</label>
                                <div class="controls">
                                    <select class="styled" name="SiteConfiguration[mode_maintenance]"
                                            style="opacity: 0;">
                                        <option value="0" <?php echo ($configs['mode_maintenance'] == 0) ? 'selected="selected"' : ''; ?>>
                                            <?php echo $this->translate('Non'); ?>
                                        </option>

                                        <option value="1" <?php echo ($configs['mode_maintenance'] == 1) ? 'selected="selected"' : ''; ?>>
                                            <?php echo $this->translate('Oui'); ?>
                                        </option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>

                <div class="line mt30"></div>

                <div class="form-actions align-left nobordertop form-actions-bg">
                    <button class="btn btn-primary"
                            type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
                </div>

                <div class="line mb30"></div>
            </form>
        </div>
    <?php } ?>
    <br>
    <?php if (count($this->paginator)): ?>
        <table id="all" class="table table-bordered " style="font-size: 0.90em; ">
            <thead>
            <tr>
                <th class="borderr2" colspan="1">-</th>
                <th class="borderr2" colspan="6">marques</th>
                <th class="borderr2" colspan="2">format</th>
                <th class="borderr2" colspan="3">options</th>
                <th class="borderr2" colspan="8">OS</th>
                <th class="borderr2" colspan="5">Interfaces</th>
                <th class="" colspan="4">Visibilité</th>
            </tr>
            </thead>
            <thead>
            <tr class="tr-hover">
                <th class="center borderr2">Nom</th>

                <th class="center ">Zebra</th>
                <th class="center ">Motorola</th>
                <th class="center ">Intermec</th>
                <th class="center ">Lxe</th>
                <th class="center ">Honeywell</th>
                <th class="center borderr2">Psion</th>

                <th class="center ">clavier</th>
                <th class="center borderr2">tactile</th>

                <th class="center ">grand froid</th>
                <th class="center ">douchette</th>
                <th class="center borderr2">clavier dur</th>

                <th class="center ">wince</th>
                <th class="center ">win emb</th>
                <th class="center ">win emb comp</th>
                <th class="center ">winmobile</th>
                <th class="center ">win7</th>
                <th class="center ">win10</th>
                <th class="center ">win xp pro</th>
                <th class="center borderr2">win xp pro embe</th>

                <th class="center ">usb</th>
                <th class="center ">eth</th>
                <th class="center ">wifi</th>
                <th class="center ">serie</th>
                <th class="center borderr2">narrow</th>

                <th class="center ">top</th>
                <th class="center ">stock</th>
                <th class="center ">visible</th>
                <th class="center ">pertinence</th>
            </tr>
            </thead>

            <tbody>
            <?php foreach ($this->paginator as $index => $item): ?>
                <tr>

                    <td class="center borderr2">
                        <a href="">
                            <?php echo $item['nom']; ?>

                        </a>
                    </td>

                    <td class="center ">
                        <a
                                href="/admin/filtreembarque/update/p/<?php echo $this->current ?>/n/m_zebra/id/<?php echo $item['id'] ?>/val/<?php echo $item['m_zebra'] ?>">
                            <?php echo $item['m_zebra'] == 0 ? '0' : $item['m_zebra']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtreembarque/update/p/<?php echo $this->current ?>/n/m_motorola/id/<?php echo $item['id'] ?>/val/<?php echo $item['m_motorola'] ?>">
                            <?php echo $item['m_motorola'] == 0 ? '0' : $item['m_motorola']; ?>
                        </a>
                    </td>

                    <td class="center ">
                        <a
                                href="/admin/filtreembarque/update/p/<?php echo $this->current ?>/n/m_intermec/id/<?php echo $item['id'] ?>/val/<?php echo $item['m_intermec'] ?>">
                            <?php echo $item['m_intermec'] == 0 ? '0' : $item['m_intermec']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreembarque/update/p/<?php echo $this->current ?>/n/m_lxe/id/<?php echo $item['id'] ?>/val/<?php echo $item['m_lxe'] ?>">
                            <?php echo $item['m_lxe'] == 0 ? '0' : $item['m_lxe']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreembarque/update/p/<?php echo $this->current ?>/n/m_honeywell/id/<?php echo $item['id'] ?>/val/<?php echo $item['m_honeywell'] ?>">
                            <?php echo $item['m_honeywell'] == 0 ? '0' : $item['m_honeywell']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtreembarque/update/p/<?php echo $this->current ?>/n/m_psion/id/<?php echo $item['id'] ?>/val/<?php echo $item['m_psion'] ?>">
                            <?php echo $item['m_psion'] == 0 ? '0' : $item['m_psion']; ?>
                        </a>
                    </td>

                    <td class="center ">
                        <a
                                href="/admin/filtreembarque/update/p/<?php echo $this->current ?>/n/clavier/id/<?php echo $item['id'] ?>/val/<?php echo $item['clavier'] ?>">
                            <?php echo $item['clavier'] == 0 ? '0' : $item['clavier']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtreembarque/update/p/<?php echo $this->current ?>/n/tactile/id/<?php echo $item['id'] ?>/val/<?php echo $item['tactile'] ?>">
                            <?php echo $item['tactile'] == 0 ? '0' : $item['tactile']; ?>
                        </a>
                    </td>

                    <td class="center ">
                        <a
                                href="/admin/filtreembarque/update/n/grand_froid/id/<?php echo $item['id'] ?>/val/<?php echo $item['grand_froid'] ?>">
                            <?php echo $item['grand_froid'] == 0 ? '0' : $item['grand_froid']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreembarque/update/n/douchette/id/<?php echo $item['id'] ?>/val/<?php echo $item['douchette'] ?>">
                            <?php echo $item['douchette'] == 0 ? '0' : $item['douchette']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a
                                href="/admin/filtreembarque/update/n/clavier_dur/id/<?php echo $item['id'] ?>/val/<?php echo $item['clavier_dur'] ?>">
                            <?php echo $item['clavier_dur'] == 0 ? '0' : $item['clavier_dur']; ?>
                        </a>
                    </td>


                    <td class="center ">
                        <a
                                href="/admin/filtreembarque/update/n/wince/id/<?php echo $item['id'] ?>/val/<?php echo $item['wince'] ?>">
                            <?php echo $item['wince'] == 0 ? '0' : $item['wince']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtreembarque/update/n/win_embeded_std/id/<?php echo $item['id'] ?>/val/<?php echo $item['win_embeded_std'] ?>">
                            <?php echo $item['win_embeded_std'] == 0 ? '0' : $item['win_embeded_std']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtreembarque/update/n/win_embeded_compact/id/<?php echo $item['id'] ?>/val/<?php echo $item['win_embeded_compact'] ?>">
                            <?php echo $item['win_embeded_compact'] == 0 ? '0' : $item['win_embeded_compact']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtreembarque/update/n/winmobile/id/<?php echo $item['id'] ?>/val/<?php echo $item['winmobile'] ?>">
                            <?php echo $item['winmobile'] == 0 ? '0' : $item['winmobile']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtreembarque/update/n/win_7/id/<?php echo $item['id'] ?>/val/<?php echo $item['win_7'] ?>">
                            <?php echo $item['win_7'] == 0 ? '0' : $item['win_7']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtreembarque/update/n/win_10/id/<?php echo $item['id'] ?>/val/<?php echo $item['win_10'] ?>">
                            <?php echo $item['win_10'] == 0 ? '0' : $item['win_10']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtreembarque/update/n/win_xp_pro/id/<?php echo $item['id'] ?>/val/<?php echo $item['win_xp_pro'] ?>">
                            <?php echo $item['win_xp_pro'] == 0 ? '0' : $item['win_xp_pro']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a href="/admin/filtreembarque/update/n/win_xp_embeded/id/<?php echo $item['id'] ?>/val/<?php echo $item['win_xp_embeded'] ?>">
                            <?php echo $item['win_xp_embeded'] == 0 ? '0' : $item['win_xp_embeded']; ?>
                        </a>
                    </td>

                    <td class="center  ">
                        <a href="/admin/filtreembarque/update/n/usb/id/<?php echo $item['id'] ?>/val/<?php echo $item['usb'] ?>">
                            <?php echo $item['usb'] == 0 ? '0' : $item['usb']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtreembarque/update/n/eth/id/<?php echo $item['id'] ?>/val/<?php echo $item['eth'] ?>">
                            <?php echo $item['eth'] == 0 ? '0' : $item['eth']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtreembarque/update/n/wifi/id/<?php echo $item['id'] ?>/val/<?php echo $item['wifi'] ?>">
                            <?php echo $item['wifi'] == 0 ? '0' : $item['wifi']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtreembarque/update/n/serie/id/<?php echo $item['id'] ?>/val/<?php echo $item['serie'] ?>">
                            <?php echo $item['serie'] == 0 ? '0' : $item['serie']; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a href="/admin/filtreembarque/update/n/narrow/id/<?php echo $item['id'] ?>/val/<?php echo $item['narrow'] ?>">
                            <?php echo $item['narrow'] == 0 ? '0' : $item['narrow']; ?>
                        </a>
                    </td>




                    <td class="center ">
                        <a
                                href="/admin/filtreembarque/update/n/top/id/<?php echo $item['id'] ?>/val/<?php echo $item['top'] ?>">
                            <?php echo $item['top'] == 0 ? '0' : $item['top']; ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a
                                href="/admin/filtreembarque/update/n/stock/id/<?php echo $item['id'] ?>/val/<?php echo $item['stock'] ?>">
                            <?php echo $item['stock'] == 0 ? '0' : $item['stock']; ?>
                        </a>
                    </td>

                    <td class="center ">
                        <a
                                href="/admin/filtreembarque/update/n/visible/id/<?php echo $item['id'] ?>/val/<?php echo $item['visible'] ?>">
                            <?php echo $item['visible'] == 0 ? '0' : $item['visible']; ?>
                        </a>
                    </td>

                    <td class="center " style="width: 5%">
                        <form action="/admin/filtreembarque/post" method="POST">
                            <input name="id_" type="hidden" value="<?php echo $item['id'] ?>">
                            <input name="page_" type="hidden" value="<?php echo $this->current ?>">
                            <input id="small" type="number" name="pertinence" value="<?php echo $item['pertinence'] == null ? 0 : $item['pertinence'] ?>">
                        </form>
                    </td>

                </tr>
            <?php endforeach; ?>

            </tbody>

        </table>
    <?php endif; ?>

    <br><br><br><br>

</div>

<div class="right">
    <div class="paginate">
        <?php if ($i == $this->previous < 1) : ?>
            <a href="/admin/filtreembarque/all/page/<?php echo $this->previous ?>" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        <?php else : ?>
            <a href="" aria-label="Previous">
                <span aria-hidden="true">x</span>
            </a>

        <?php endif ?>


        <?php for ($i = 1; $i <= $this->total; $i++): ?>
            <?php if ($i == $this->current) : ?>
                <a href="#" class="active"><?php echo $i ?></a>
            <?php else : ?>
                <a href="/admin/filtreembarque/all/page/<?php echo $i ?>"><?php echo $i ?></a>
            <?php endif ?>
        <?php endfor ?>

        <?php if ($i == $this->next <= $this->total) : ?>
            <a href="/admin/filtreembarque/all/page/<?php echo $this->next ?>" aria-label="Previous">
                <span aria-hidden="true">&raquo;</span>
            </a>
        <?php else : ?>
            <a href="" aria-label="next">
                <span aria-hidden="true">x</span>
            </a>

        <?php endif ?>

    </div>
</div>
<!-- /content wrapper -->
<link href="<?php echo URL_DEFAULT_CSS; ?>geo/css/app_admin.css" rel="stylesheet" type="text/css" media="all"/>