<div class="wrapper-content-index" style="font-size: 1.2em">
    <h1>DECOUVRIR EUROCOMPUTER</h1>
    <h3>En video</h3>

    <p style="text-align:justify">
        <span style="font-size:12px">
            Depuis 25 ans, <strong>Eurocomputer</strong> propose son savoir-faire en mati&egrave;re d&rsquo;optimisation des co&ucirc;ts informatiques.
        </span>
    </p>

    <p style="text-align:justify">
        <span style="font-size:12px">Consultez nos offres de d&eacute;stockage en tra&ccedil;abilit&eacute;&nbsp;: <strong>
                <a href="https://www.eurocomputer.fr/imprimantes/imprimantes-etiquettes-14.html">
                    <span><u>imprimantes &eacute;tiquettes</u> </span>
                </a> &amp;
                <a href="https://www.eurocomputer.fr/tracabilite/terminaux-code-barres-17.html">
                    <span><u>lecteurs code-barres</u></span>
                </a>
            </strong>
        </span>
    </p>

    <ul>
        <li style="text-align:justify">
            <span style="font-size:12px">Toutes les plus grandes marques sont en stock&nbsp;:
                <strong>
                    <a href="https://www.eurocomputer.fr/imprimantes/imprimantes-etiquettes-14/zebra-39.html">
                        imprimante &eacute;tiquette Zebra
                    </a>
                    Motorola Symbol
                </strong>&ndash; <strong>Datalogic</strong> &ndash;<strong> Psion Teklogix</strong> &ndash;<strong> Intermec</strong></span>
        </li>
    </ul>

    <p style="text-align:justify"><span style="font-size:12px">Profitez de nos promotions sur les p&eacute;riph&eacute;riques de bureau&nbsp;:
            <strong><a href="https://www.eurocomputer.fr/micro/micro-27/pc-en-destockage-116.html"><span><u>PC</u></span></a>
                &ndash; <a href="https://www.eurocomputer.fr/micro/micro-27/ecrans-en-destockage-118.html"><span
                            style="">&eacute;crans</span></a>
                &ndash; <a href="https://www.eurocomputer.fr/micro/micro-27/portables-en-destockage-117.html"><span
                            style="">portables</span></a> </strong>
                &ndash; platines <strong><a href="https://www.eurocomputer.fr/micro/micro-27.html"><span style="">clients-l&eacute;gers</span></a> </strong>
                &ndash; imprimantes<strong> <a href="https://www.eurocomputer.fr/imprimantes/imprimantes-laser-24.html"><span
                            style="">laser</span></a></strong>
                &ndash; imprimantes<strong> <a
                        href="https://www.eurocomputer.fr/imprimantes/imprimantes-matricielles-32.html"><span style="">matricielles</span></a></strong></span>
    </p>

    <ul>
        <li style="text-align:justify"><span style="font-size:12px"><strong>marques HP &ndash; Lenovo &ndash; Dell Wyse &ndash; Lexmark &ndash; Epson &ndash; Oki</strong></span>
        </li>
    </ul>

    <p style="text-align:justify"><span style="font-size:12px">Vous recherchez d&rsquo;anciennes r&eacute;f&eacute;rences, du <strong>mat&eacute;riel informatique reconditionn&eacute;</strong> ou en d&eacute;stockage, des <strong>accessoires &amp; pi&egrave;ces d&eacute;tach&eacute;es</strong>&nbsp;: contactez-nous, une r&eacute;ponse vous sera apport&eacute;e dans les 24 heures.</span>
    </p>

    <p style="text-align:justify"><span style="font-size:12px">Pour tous ces mat&eacute;riels commercialis&eacute;s, des prestations d&rsquo;<a
                    href="https://www.eurocomputer.fr/vente">&eacute;change</a>, de <a
                    href="https://www.eurocomputer.fr/vente">reconditionnement</a>, de <a
                    href="https://www.eurocomputer.fr/reparation">r&eacute;paration</a>, de <a
                    href="https://www.eurocomputer.fr/location">location</a> sont propos&eacute;s.</span></p>

    <p style="text-align:justify"><span style="font-size:12px">Envoyez-nous vos p&eacute;riph&eacute;riques en panne&nbsp;: <a
                    href="https://www.eurocomputer.fr/tracabilite/terminaux-code-barres-embarques-17.html">terminaux mobiles</a>, <a
                    href="https://www.eurocomputer.fr/tracabilite/scanners-code-barres-21.html">scanners code-barres</a> et <a
                    href="https://www.eurocomputer.fr/tracabilite/imprimantes-etiquettes-14.html">imprimantes thermiques</a>&nbsp;etc&hellip; Un <strong>devis gratuit de r&eacute;paration</strong> vous sera adress&eacute; imm&eacute;diatement. La r&eacute;paration est effectu&eacute;e dans nos locaux, au si&egrave;ge fran&ccedil;ais du groupe. Le mat&eacute;riel r&eacute;par&eacute; vous sera retourn&eacute; dans des d&eacute;lais reconnus comme &eacute;tant les plus courts du march&eacute;. Eurocomputer est partout pl&eacute;biscit&eacute; pour sa r&eacute;activit&eacute;, y compris hors contrat de maintenance.</span>
    </p>

    <p style="text-align:justify">
        <span style="font-size:12px">La <a
                    href="https://www.eurocomputer.fr/reprise">reprise</a>
            et la valorisation de vos imprimantes d&rsquo;occasion en panne est possible, dans le cadre de remplacement par du mat&eacute;riel reconditionn&eacute; ou neuf.
        </span>
    </p>

    <p style="text-align:justify"><span style="font-size:12px">Tous nos mat&eacute;riels, neufs ou reconditionn&eacute;s sont garantis jusqu&rsquo;&agrave; 3 ou 5 ans.</span>
    </p>

    <p style="text-align:justify"><span style="font-size:12px">Eurocomputer&nbsp;: 25 ans d&rsquo;expertise aupr&egrave;s d&rsquo;enseignes de l&rsquo;agroalimentaire, du transport et de la logistique, de l&rsquo;industrie.</span>
    </p>

</div>
