
<div    class="flex-rectangle js-modal-btn hidden"
        data-video-id="zLr9TEK8D8I"
        style='background-image:url(<?php echo PROJECTS.'/upload/images/geo/team__.jpg' ?>)'
>
        <div class="play-video ">
            <i class="fa fa-play fa-3x"></i>
        </div>
        <div class="card-overlay">&nbsp;</div>
</div>
<div style="padding-top: 55px">
    <iframe
            width="100%"
            height="400px"
            src="https://www.youtube.com/embed/zLr9TEK8D8I"
            frameborder="0"
            allowfullscreen>

    </iframe>
</div>
<br><br><br>



