<!-- Content wrapper -->
<div class="wrapper ">

    <?php echo Genius_Class_Snippets::breadcrumb($this->translate('Configuration du site'), '/admin/siteconfiguration'); ?>

    <!-- Page header -->
    <div class="page-header">
        <div class="page-title">
            <h2><?php echo $this->translate('DOUCHETTES DANS BASE DE DONNEE'); ?></h2>
        </div>
    </div>
    <!-- /page header -->

    <div class="line"></div>

    <?php
    if (!empty($this->configs)) {
        $configs = $this->configs[0];
        ?>
        <div class="span12">
            <form method="post" action="" id="configure-form" class="form-horizontal form-to-validate">
                <input type="hidden" value="1" id="id" name="SiteConfiguration[id]">

                <fieldset>
                    <div class="widget row-fluid mt30">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><?php echo $this->translate('Informations générales'); ?></h6>
                            </div>
                        </div>

                        <div class="well">
                            <div class="control-group">
                                <label class="control-label" for="siteweb"><span class="text-error">*</span> Website:</label>
                                <div class="controls"><input type="text" class="validate[required] span12" value="<?php echo $configs['siteweb']; ?>" id="siteweb" class="validate[required]" name="SiteConfiguration[siteweb]" /></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="adresse"><span class="text-error">*</span> Adresse :</label>
                                <div class="controls"><input type="text" class="validate[required] span12" value="<?php echo $configs['adresse']; ?>" id="adresse" name="SiteConfiguration[adresse]" /></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="email"><span class="text-error">*</span> Email:</label>
                                <div class="controls"><input type="text" class="validate[required] span12" value="<?php echo $configs['email']; ?>" id="email" class="validate[required,custom[email]]" name="SiteConfiguration[email]" /></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="phone"><span class="text-error">*</span> Téléphone :</label>
                                <div class="controls"><input type="text" class="validate[required] span12" value="<?php echo $configs['phone']; ?>" id="phone" name="SiteConfiguration[phone]" /></div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="fax"><span class="text-error">*</span> Fax :</label>
                                <div class="controls"><input type="text" class="validate[required] span12" value="<?php echo $configs['fax']; ?>" id="fax" name="SiteConfiguration[fax]" /></div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="title"><span class="text-error">*</span> Title:</label>
                                <div class="controls"><input type="text" class="validate[required] span12" value="<?php echo $configs['title']; ?>" id="title" name="SiteConfiguration[title]" class="validate[required]"></div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="slogan">Catchword:</label>
                                <div class="controls"><input type="text" class="span12" value="<?php echo $configs['slogan']; ?>" id="slogan" name="SiteConfiguration[slogan]" /></div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="transition_slider">Transition slider : (millisec)</label>
                                <div class="controls"><input type="text" class="span12" value="<?php echo $configs['transition_slider']; ?>" id="transition_slider" name="SiteConfiguration[transition_slider]" /></div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="pause_slider">Pause Slider : (millisec)</label>
                                <div class="controls"><input type="text" class="span12" value="<?php echo $configs['pause_slider']; ?>" id="pause_slider" name="SiteConfiguration[pause_slider]" /></div>
                            </div>
                        </div>
                    </div>

                    <div class="widget row-fluid mt30">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><?php echo $this->translate('Mode maintenance'); ?></h6>
                            </div>
                        </div>

                        <div class="well">
                            <div class="control-group">
                                <label class="control-label" for="mode_maintenance"> Mode maintenance:</label>
                                <div class="controls">
                                    <select class="styled" name="SiteConfiguration[mode_maintenance]" style="opacity: 0;">
                                        <option value="0" <?php echo ($configs['mode_maintenance'] == 0) ? 'selected="selected"' : ''; ?>>
                                            <?php echo $this->translate('Non'); ?>
                                        </option>

                                        <option value="1" <?php echo ($configs['mode_maintenance'] == 1) ? 'selected="selected"' : ''; ?>>
                                            <?php echo $this->translate('Oui'); ?>
                                        </option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>

                <div class="line mt30"></div>

                <div class="form-actions align-left nobordertop form-actions-bg">
                    <button class="btn btn-primary" type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
                </div>

                <div class="line mb30"></div>
            </form>
        </div>
    <?php } ?>
    <br>
    <?php if (count($this->paginator)): ?>
    <table id="all" class="table table-bordered " style="font-size: 0.90em">
        <thead>
        <tr>
            <th class="borderr2" colspan="2">-</th>
            <th class="borderr2" colspan="2">Gamme</th>
            <th class="borderr2" colspan="6">Marques</th>
            <th class="borderr2" colspan="2">Type materiel</th>
            <th class="borderr2" colspan="2">Connectique D</th>
            <th class="borderr2" colspan="5">Scanner</th>
            <th class="borderr2" colspan="3">Option</th>
            <th class="borderr2" colspan="4">Connectique B</th>

            <th class="borderr2" colspan="4">Visibilité</th>
            <th >-</th>
        </tr>
        </thead>
        <thead>
        <tr class="tr-hover">
            <th class="center " >id</th>

            <th class="center borderr2" >Nom</th>

            <th class="center "  >Bureau</th>
            <th class="center borderr2 "  >Indu</th>

            <th class="center  ">Zebra</th>
            <th class="center  ">Motorola</th>
            <th class="center  ">Symbol</th>
            <th class="center  ">Datalogic</th>
            <th class="center  ">Honeywell</th>
            <th class="center borderr2">Opticon</th>

            <th class="center "  >Filaire</th>
            <th class="center borderr2"  >Wireless</th>

            <th class="center ">bluetooh</th>
            <th class="center borderr2">radio</th>

            <th class="center"  >1d std</th>
            <th class="center"  >1d lg</th>
            <th class="center"  >1d xlg</th>
            <th class="center"  >2d std</th>
            <th class="center borderr2"  >2d lg</th>

            <th class="center " >Ecran</th>
            <th class="center "  >Clavier</th>
            <th class="center borderr2"  >Batch</th>

            <th class="center " >Eth</th>
            <th class="center " >Usb</th>
            <th class="center " >Serie</th>
            <th class="center borderr2"  >Wedge</th>


            <th class="center "  >top</th>
            <th class="center "  >stock</th>
            <th class="center "  >visibilité</th>
            <th class="center borderr2"  >pertinence</th>
            <th class="center "  >Edit</th>
        </tr>
        </thead>

        <tbody>
            <?php foreach ($this->paginator as $index => $item): ?>
                <tr>
                    <td class="center">   <?php echo $item['product_id']?></td>
                    <td class="center borderr2"> <?php echo $item['name']; ?></td>

                    <td class="center">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/bureau/id/<?php echo $item['id'] ?>/val/<?php echo $item['bureau'] ?>">
                            <?php echo $item['bureau'] == null ? 0 : $item['bureau'] ;  ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/indu/id/<?php echo $item['id'] ?>/val/<?php echo $item['indu'] ?>">
                            <?php echo $item['indu'] == null ? 0 : 1 ;  ?>
                        </a>
                    </td>

                    <td class="center">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/m_zebra/id/<?php echo $item['id'] ?>/val/<?php echo $item['m_zebra'] ?>">
                            <?php echo $item['m_zebra'] == null ? 0 : $item['m_zebra'] ;  ?>
                        </a>
                    </td>
                    <td class="center">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/m_motorola/id/<?php echo $item['id'] ?>/val/<?php echo $item['m_motorola'] ?>">
                            <?php echo $item['m_motorola'] == null ? 0 : $item['m_motorola'] ;  ?>
                        </a>
                    </td>
                    <td class="center">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/m_symbol/id/<?php echo $item['id'] ?>/val/<?php echo $item['m_symbol'] ?>">
                            <?php echo $item['m_symbol'] == null ? 0 : $item['m_symbol'] ;  ?>
                        </a>
                    </td>
                    <td class="center">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/m_datalogic/id/<?php echo $item['id'] ?>/val/<?php echo $item['m_datalogic'] ?>">
                            <?php echo $item['m_datalogic'] == null ? 0 : $item['m_datalogic'] ;  ?>
                        </a>
                    </td>
                    <td class="center">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/m_honeywell/id/<?php echo $item['id'] ?>/val/<?php echo $item['m_honeywell'] ?>">
                            <?php echo $item['m_honeywell'] == null ? 0 : $item['m_honeywell'] ;  ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/m_opticon/id/<?php echo $item['id'] ?>/val/<?php echo $item['m_opticon'] ?>">
                            <?php echo $item['m_opticon'] == null ? 0 : $item['m_opticon'] ;  ?>
                        </a>
                    </td>

                    <td class="center">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/filaire/id/<?php echo $item['id'] ?>/val/<?php echo $item['filaire'] ?>">
                            <?php echo $item['filaire'] == null ? 0 : $item['filaire'] ; ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/nofilaire/id/<?php echo $item['id'] ?>/val/<?php echo $item['nofilaire'] ?>">
                            <?php echo $item['nofilaire'] == null ? 0 : $item['nofilaire'] ;  ?>
                        </a>
                    </td>

                    <td class="center ">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/bluetooh/id/<?php echo $item['id'] ?>/val/<?php echo $item['bluetooh'] ?>">
                            <?php echo $item['bluetooh'] == null ? 0 : $item['bluetooh'] ;  ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/radio/id/<?php echo $item['id'] ?>/val/<?php echo $item['radio'] ?>">
                            <?php echo $item['radio'] == null ? 0 : $item['radio'] ;  ?>
                        </a>
                    </td>

                    <td class="center ">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/1std/id/<?php echo $item['id'] ?>/val/<?php echo $item['1std'] ?>">
                            <?php echo $item['1std'] == null ? 0 : $item['1std'] ;  ?>
                        </a>
                    </td>
                    <td class="center">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/1lg/id/<?php echo $item['id'] ?>/val/<?php echo $item['1lg'] ?>">
                            <?php echo $item['1lg'] == null ? 0 : $item['1lg'] ;  ?>
                        </a>
                    </td>
                    <td class="center">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/1xlg/id/<?php echo $item['id'] ?>/val/<?php echo $item['1xlg'] ?>">
                            <?php echo $item['1xlg'] == null ? 0 : $item['1xlg'] ;  ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/2std/id/<?php echo $item['id'] ?>/val/<?php echo $item['2std'] ?>">
                            <?php echo $item['2std'] == null ? 0 : $item['2std'] ;  ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/2lg/id/<?php echo $item['id'] ?>/val/<?php echo $item['2lg'] ?>">
                            <?php echo $item['2lg'] == null ? 0 : $item['2lg'] ;  ?>
                        </a>
                    </td>

                    <td class="center">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/ecran/id/<?php echo $item['id'] ?>/val/<?php echo $item['ecran'] ?>">
                            <?php echo $item['ecran'] == null ? 0 : $item['ecran'] ;  ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/clavier/id/<?php echo $item['id'] ?>/val/<?php echo $item['clavier'] ?>">
                            <?php echo $item['clavier'] == null ? 0 : $item['clavier'] ;  ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/batch/id/<?php echo $item['id'] ?>/val/<?php echo $item['batch'] ?>">
                            <?php echo $item['batch'] == null ? 0 : $item['batch'] ;  ?>
                        </a>
                    </td>

                    <td class="center">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/eth/id/<?php echo $item['id'] ?>/val/<?php echo $item['eth'] ?>">
                            <?php echo $item['eth'] == null ? 0 : $item['eth'] ;  ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/usb/id/<?php echo $item['id'] ?>/val/<?php echo $item['usb'] ?>">
                            <?php echo $item['usb'] == null ? 0 : $item['usb'] ;  ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/serie/id/<?php echo $item['id'] ?>/val/<?php echo $item['serie'] ?>">
                            <?php echo $item['serie'] == null ? 0 : $item['serie'] ;  ?>
                        </a>
                    </td>
                    <td class="center borderr2">
                        <a href="/admin/filtredouchette/update/p/<?php echo $this->current ?>/n/wedge/id/<?php echo $item['id'] ?>/val/<?php echo $item['wedge'] ?>">
                            <?php echo $item['wedge'] == null ? 0 : $item['wedge'] ;  ?>
                        </a>
                    </td>





                    <td class="center ">
                        <a href="/admin/filtredouchette/update/n/top/id/<?php echo $item['id'] ?>/val/<?php echo $item['top'] ?>">
                            <?php echo $item['top'] == null ? 0 : $item['top'] ;  ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtredouchette/update/n/stock/id/<?php echo $item['id'] ?>/val/<?php echo $item['stock'] ?>">
                            <?php echo $item['stock'] == null ? 0 : $item['stock'] ;  ?>
                        </a>
                    </td>
                    <td class="center ">
                        <a href="/admin/filtredouchette/update/n/visible/id/<?php echo $item['id'] ?>/val/<?php echo $item['visible'] ?>">
                            <?php echo $item['visible'] == null ? 0 : $item['visible'] ;  ?>
                        </a>
                    </td>
                    <td class="center borderr2" style="width: 5%">
                        <form action="/admin/filtredouchette/post" method="POST">
                            <input name="id_" type="hidden" value="<?php echo $item['id'] ?>">
                            <input name="page_" type="hidden" value="<?php echo $this->current ?>">
                            <input  id="small" type="number" name="pertinence" value="<?php  echo $item['pertinence'] == null ? 0 : $item['pertinence'] ;?>">
                        </form>
                    </td>

                    <td class="center " style="padding: 2px">
                            <a class="hide" style="color:white;" href="/admin/filtredouchette/edit/id/<?php echo $item['id'] ?>/page/<?php echo $this->current ?>">
                                <button  class="btn btn-primary">edit</button>
                            </a>
                    </td>
                   
                </tr>
            <?php endforeach; ?>

        </tbody>

    </table>
    <?php endif; ?>

    <br><br><br><br>

</div>

<div class="right">
    <div class="paginate">
        <?php if($i == $this->previous < 1) : ?>
            <a href="/admin/filtredouchette/all/page/<?php echo $this->previous ?>" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        <?php else :?>
            <a href="" aria-label="Previous">
                <span aria-hidden="true">x</span>
            </a>

        <?php endif ?>


        <?php for($i = 1 ; $i <= $this->total ; $i++): ?>
            <?php if($i == $this->current) : ?>
                <a href="#" class="active" ><?php echo $i ?></a>
            <?php else :?>
                <a href="/admin/filtredouchette/all/page/<?php echo $i ?>" ><?php echo $i ?></a>
            <?php endif ?>
        <?php endfor ?>

        <?php if($i == $this->next <= $this->total) : ?>
            <a href="/admin/filtredouchette/all/page/<?php echo $this->next ?>" aria-label="Previous">
                <span aria-hidden="true">&raquo;</span>
            </a>
        <?php else :?>
            <a href="" aria-label="next">
                <span aria-hidden="true">x</span>
            </a>

        <?php endif ?>

    </div>
</div>
<!-- /content wrapper -->
<link href="<?php echo URL_DEFAULT_CSS; ?>geo/css/app_admin.css" rel="stylesheet" type="text/css" media="all" />