<div class="">
    <h4
            style="cursor: pointer"
            class="right aide-form"
        data-toggle="modal"
        data-target="#myModal">
        <i class="fa fa-info-circle"> </i>
        <u style=" text-decoration:none ;border-bottom: 2px dashed #CC6DC7">aide</u>
    </h4>

</div>

<!-- Modal -->
<div style="border-bottom: none;padding-bottom: 70px" class="modal fade " id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div style="width: 60%" class="modal-dialog" role="document">

        <div class="modal-content col-lg-10">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">
                    <b>Information sur les parametre de configuration d'un <u>TERMINAL</u></b>
                </h4>
            </div>
            <div class="modal-body">
                <div class="row" style="padding-bottom: 10px">
                    <div class="col-lg-12">
                        <h6 class="u"><b><u>LES RESOLUTIONS</u></b></h6>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto est facere
                            placeat praesentium, quaerat similique voluptas. Accusamus, beatae corporis,
                            dicta distinctio ipsa neque odio possimus quibusdam quidem, quod sequi suscipit.
                        </p>
                    </div>
                </div>

                <div class="row" style="padding-bottom: 10px">
                    <div class="col-lg-12">
                        <h6 class="u"><b><u>LES RESOLUTIONS</u></b></h6>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto est facere
                            placeat praesentium, quaerat similique voluptas. Accusamus, beatae corporis,
                            dicta distinctio ipsa neque odio possimus quibusdam quidem, quod sequi suscipit.
                        </p>
                    </div>
                </div>

                <div class="row" style="padding-bottom: 10px">
                    <div class="col-lg-12">
                        <h6 class="u"><b><u>LES RESOLUTIONS</u></b></h6>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto est facere
                            placeat praesentium, quaerat similique voluptas. Accusamus, beatae corporis,
                            dicta distinctio ipsa neque odio possimus quibusdam quidem, quod sequi suscipit.
                        </p>
                    </div>
                </div>

                <div class="row" style="padding-bottom: 10px">
                    <div class="col-lg-12">
                        <h6 class="u"><b><u>LES RESOLUTIONS</u></b></h6>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto est facere
                            placeat praesentium, quaerat similique voluptas. Accusamus, beatae corporis,
                            dicta distinctio ipsa neque odio possimus quibusdam quidem, quod sequi suscipit.
                        </p>
                    </div>
                </div>

                <div class="row" style="padding-bottom: 10px">
                    <div class="col-lg-12">
                        <h6 class="u"><b><u>LES RESOLUTIONS</u></b></h6>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto est facere
                            placeat praesentium, quaerat similique voluptas. Accusamus, beatae corporis,
                            dicta distinctio ipsa neque odio possimus quibusdam quidem, quod sequi suscipit.
                        </p>
                    </div>
                </div>

                <div class="row" style="padding-bottom: 10px">
                    <div class="col-lg-12">
                        <h6 class="u"><b><u>LES RESOLUTIONS</u></b></h6>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto est facere
                            placeat praesentium, quaerat similique voluptas. Accusamus, beatae corporis,
                            dicta distinctio ipsa neque odio possimus quibusdam quidem, quod sequi suscipit.
                        </p>
                    </div>
                </div>

                <div class="row" style="padding-bottom: 10px">
                    <div class="col-lg-12">
                        <h6 class="u"><b><u>LES RESOLUTIONS</u></b></h6>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto est facere
                            placeat praesentium, quaerat similique voluptas. Accusamus, beatae corporis,
                            dicta distinctio ipsa neque odio possimus quibusdam quidem, quod sequi suscipit.
                        </p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>

</div>