<div class="panel-group" id="min_configurator" role="tablist" aria-multiselectable="true">

    <div class="">

        <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#min_configurator" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                    Imprimantes
                </a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse " role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
                <a href="">Thermique</a> <br>
                <a href="">Badgeuse</a> <br>
                <a href="">Couleur</a> <br>
                <a href="">Portable</a> <br>
            </div>
        </div>

    </div>

    <div class="">
        <div class="panel-heading" role="tab" id="headingTwo">
            <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#min_configurator" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Lecteurs Code-barres
                </a>
            </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
            <div class="panel-body">
                <a href="">Douchette</a> <br>
                <a href="">Ring</a> <br>
            </div>
        </div>
    </div>

    <div class="">
        <div class="panel-heading" role="tab" id="headingThree">
            <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#min_configurator" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Terminaux mobiles - embarqué
                </a>
            </h4>
        </div>
        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
            <div class="panel-body">
                <a href="">Terminal mobile</a> <br>
                <a href="">PDA</a> <br>
                <a href="">Embarqué</a> <br>
                <a href="">Terminal poignet</a> <br>
            </div>
        </div>
    </div>

    <div class="">
        <div class="panel-heading" role="tab" id="headingFour">
            <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#min_configurator" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                    Postes de travail
                </a>
            </h4>
        </div>
        <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
            <div class="panel-body">
                <a href="">Client leger</a> <br>
                <a href="">PC</a> <br>
                <a href="">Portable</a> <br>
            </div>
        </div>
    </div>
</div>