<div class="panel-group" id="min_configurator" role="tablist" aria-multiselectable="true">

    <div class="">

        <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#min_configurator" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                    <i class="fa fa-angle-right"> </i> &nbsp;Imprimantes
                </a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse " role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
                <a href="/configurateur/form?f=search_thermique"> Thermique</a> <br>
                <a href="/configurateur/form?f=search_etiquette_badgeuse">Badgeuse</a> <br>
                <a href="/configurateur/form?f=search_etiquette_couleur">Couleur</a> <br>
                <a href="/configurateur/form?f=search_etiquette_portable">Portable</a> <br>
                <a href="/configurateur/form?f=search_printer_laser">Laser</a> <br>
                <a href="/configurateur/form?f=search_printer_matricielle">Matricielle</a> <br>
            </div>
        </div>

    </div>

    <div class="">
        <div class="panel-heading" role="tab" id="headingTwo">
            <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#min_configurator" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    <i class="fa fa-angle-right"> </i> &nbsp;Lecteurs Code-barres
                </a>
            </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
            <div class="panel-body">
                <a href="/configurateur/form?f=search_douchette">Douchette</a> <br>
                <a href="/configurateur/form?f=search_douchette_ring">Ring</a> <br>
            </div>
        </div>
    </div>

    <div class="">
        <div class="panel-heading" role="tab" id="headingThree">
            <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#min_configurator" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    <i class="fa fa-angle-right"> </i> &nbsp;Terminaux mobiles
                </a>
            </h4>
        </div>
        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
            <div class="panel-body">
                <a href="/configurateur/form?f=search_terminal">Terminal mobile</a> <br>
                <a href="/configurateur/form?f=search_terminal_pda">PDA</a> <br>
                <a href="/configurateur/form?f=search_terminal_embarque">Embarqué</a> <br>
                <a href="/configurateur/form?f=search_terminal_poignet">Terminal poignet</a> <br>
            </div>
        </div>
    </div>

    <div class="">
        <div class="panel-heading" role="tab" id="headingFour">
            <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#min_configurator" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                    <i class="fa fa-angle-right"> </i> &nbsp;Postes de travail
                </a>
            </h4>
        </div>
        <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
            <div class="panel-body">
                <a href="/configurateur/form?f=search_poste_client">Client leger</a> <br>
                <a href="/configurateur/form?f=search_poste_pc">PC</a> <br>
                <a href="/configurateur/form?f=search_poste_portable">Portable</a> <br>
            </div>
        </div>
    </div>
</div>