<div class="row wrapper-configurator-section ">
    <div class="col-md-12 text-left configurator">
        <div class="row">

            <!--FORMAT XS-->
            <div class="col-lg-10 col-md-10 visible-xs">

                <div style=" " >
                    <a
                        style="font-size: 0.8em;font-weight: bold"
                        class="anconfigurator" href="/configurateur"> Imprimantes - THERMIQUE
                    </a>
                    <br>
                    <span
                        class="etape-emp"> Quel Caractèristiques ?  - <b class="etape-under"> ETAPE 55/3</b>
                                </span>
                </div>
            </div>
            <!--FORMAT XS-->

            <!--FORMAT SM-->
            <div class="col-lg-10 col-md-10 hidden-lg hidden-md visible-sm hidden-xs">
                <a class="anconfigurator" href="/configurateur">
                                <span class="fa-stack fa-lg" style="font-size: 2em">
                                    <i class="fa fa-circle fa-stack-2x " style="font-size: 2em ; color:white;"></i>
                                    <i class="fa fa-print fa-stack-1x blue_royal" ></i>
                                </span>
                </a>
                <br>
                <div style="
                            padding-left: 77px;
                            margin-top:-62px;
                            text-decoration-style: initial;
                            font-weight: lighter;
                            position: relative;
                            font-size: 0.7em;
                            padding-bottom: 10px;
                            "
                >
                    <a
                        style="font-size: 2em;font-weight: bold"
                        class="anconfigurator" href="/configurateur"> Imprimantes etiquettes - THERMIQUE
                    </a>
                    <br>
                    <?php include('etape-3.phtml') ?>
                </div>
            </div>
            <!--FORMAT SM-->

            <!--FORMAT NORMAL-->
            <div class="col-lg-10 col-md-10 hidden-sm hidden-xs">

                <span class="fa-stack fa-lg" style="font-size: 2em">
                    <i class="fa fa-circle fa-stack-2x " style="font-size: 2em ; color:white;"></i>
                    <i class="fa <?php echo isset($configurator['icone']) ? $configurator['icone'] : 'fa-info' ?> fa-stack-1x blue_royal" ></i>
                </span>

                <br>
                
                <div
                    style=
                    "
                    padding-left: 77px;
                    margin-top:-62px;
                    text-decoration-style: initial;
                    font-weight: lighter;
                    position: relative;
                    padding-bottom: 10px;
                    "
                >
                    <a
                        style="font-size: 1.3em;font-weight: bold"
                        class="anconfigurator" href="/configurateur"> <?php echo isset($configurator['title']) ? $configurator['title'] : 'TITRE PAR DEFAUT' ?>
                    </a>

                    <br>

                    <?php include(isset($configurator['etape']) ? $configurator['etape'] : 'etape-3.phtml') ?>

                </div>

            </div>

            <!--FORMAT NORMAL-->

            <div class="col-lg-2 col-md-2 right hidden-sm hidden-xs">
                <?php
                $picture =isset($configurator['photo']) ? $configurator['photo'] : '/upload/images/geo/pf4i.jpg' ;
                $url = PROJECTS.$picture
                ?>
                <img
                    style=" width 82px; height: 82px ; border-radius: 82px ; "
                    src="<?php echo $url ?>" alt="">
            </div>

        </div>

    </div>

</div>