<table class="table">
    <thead>
    <tr>
        <th></th>
        <th>PRODUIT</th>
        <th>CARACTERISTIQUES</th>
        <th class="center">Qte</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->panier as $index => $item) : ?>
        <tr id="<?php echo "row_$index" ?>">
            <td style="padding-top: 20px">

                <a  id="<?php echo "$index" ?>" class="testdelete" href="configurateur/deletechoice?product=<?php echo $index ?>">
                    <i style="color:indianred" class="fa fa-times "></i>
                </a>
            </td>
            <td>
                <img style="height: 50px ;width: 50px" src="<?php echo $item['image'] ?>" alt=" <?php echo $item['choice'] ?>"> <?php echo $item['choice'] ?>
            </td>
            <td>
                <?php echo strtoupper($item['section']) ?>
                <br>
                <ul>
                    <?php echo is_string($item['input']) ? $item['input'] : ''; ?>

                    <?php foreach ($item['input'] as $i => $v) : ?>
                        <?php if (is_array($v)): ?>
                            <ul style="font-size:12px ; ">
                                <b><?php echo $i ?> :</b>
                                <?php foreach ($v as $subindex => $subvalue) : ?>
                                    <li style="font-size: 12px "> <?php echo $subvalue ?> </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php else: ?>
                            <li style="font-size:12px"><?php echo $i.' : '.$v ?></li>
                        <?php endif; ?>
                    <?php endforeach; ?>

                </ul>
            </td>
            <td class="center" style="padding-top: 20px">

                &nbsp;
                <a id="<?php echo $index ?>" class="button_qte_minus " href="/configurateur/qte/sub?product=<?php echo $index?>">-</a>
                &nbsp;
                <b id="<?php echo "valq_$index" ?>"> <?php echo $item['qte']  ?> </b>
                &nbsp;
                <a id="<?php echo $index ?>" class="button_qte_plus" href="/configurateur/qte/add?product=<?php echo $index?>">+</a>
                &nbsp;
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>