<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>

    <div class="row">
        <?php
            //var_dump($this->input);
            //var_dump($this->session);
            //var_dump($this->search);
        ?>
    </div>

    <div class="row " >
        <div class="col-lg-12 ">

            <?php
            $configurator =
                [
                    'icone' => 'fa-mobile-phone',
                    'title' => 'Terminaux mobiles & embarqué - TERMINAL MOBILE',
                    'etape' => 'etape-2.phtml',
                    'photo' => '/upload/images/geo/MC92_.jpg'
                ]
            ?>

            <?php include('configurator_title.phtml') ?>

        </div>
    </div>



    <div class="row " style="padding-top:10px;background-color: white;">
        <div class="col-lg-12 ">

            <div class="form-section row wrapper-content-configurator ">

                <!--MARQUE-->
                <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> marque</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>marque</b>
                                                                                              &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="marque" onchange='this.form.submit();'>
                                    <option  value="na" <?php echo $this->input['marque'] == 'na' ? 'selected' : ''?> >non-défini</option>
                                    <option  value="m_zebra" <?php echo $this->input['marque'] == 'm_zebra' ? 'selected' : ''?> >Zebra</option>
                                    <option  value="m_motorola" <?php echo $this->input['marque'] == 'm_motorola' ? 'selected' : ''?> >Motorola</option>
                                    <option  value="m_symbol" <?php echo $this->input['marque'] == 'm_symbol' ? "selected" : ''?> >Symbol</option>
                                    <option  value="m_datalogic" <?php echo $this->input['marque'] == 'm_datalogic' ? "selected" : ''?> >Datalogic</option>
                                    <option  value="m_intermec" <?php echo $this->input['marque'] == 'm_intermec' ? "selected" : ''?> >Intermec</option>
                                    <option  value="m_lxe" <?php echo $this->input['marque'] == 'm_lxe' ? "selected" : ''?> >Lxe</option>
                                    <option  value="m_honeywell" <?php echo $this->input['marque'] == 'm_honeywell' ? "selected" : ''?> >Honeywell</option>
                                    <option  value="m_psion" <?php echo $this->input['marque'] == 'm_psion' ? "selected" : ''?> >Psion</option>
                                    <option  value="all" <?php echo $this->input['marque'] == 'all' ? "selected" : ''?> >toutes marques</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--MARQUE-->

                <!--FORMAT-->
                <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 ">
                            <?php if($this->input['format'] <> 'na' && $this->input['format'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> format</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>format</b>
                                                                                              &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <select name="format" onchange='this.form.submit();'>
                                    <option <?php echo $this->input['format'] == 'na' ? 'selected' : ''?> value="na">non-défini</option>
                                    <option <?php echo $this->input['format'] == 'gun' ? 'selected' : ''?> value="gun">avec poignée</option>
                                    <option <?php echo $this->input['format'] == 'droit' ? 'selected' : ''?> value="droit">sans poignée</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--FORMAT-->

                <!--SYSTEME-->
                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <?php if($this->input['os'] <> 'na' && $this->input['os'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> système</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>système</b>
                                                                                              &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>

                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <div class="select">
                                <select name="os" onchange='this.form.submit();'>
                                    <option  value="na" <?php echo $this->input['os'] == 'na' ? 'selected' : ''?> >non-défini</option>
                                    <option  value="wince" <?php echo $this->input['os'] == 'wince' ? 'selected' : ''?> >Windows CE</option>
                                    <option  value="winmobile" <?php echo $this->input['os'] == 'winmobile' ? 'selected' : ''?> >Windows mobile</option>
                                    <option  value="android" <?php echo $this->input['os'] == 'android' ? "selected" : ''?> >Android</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!--SYSTEME-->

            </div>

            <div class="form-section row wrapper-content-configurator ">

                <!--SCANNER-->
                <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if($this->input['scanner'] <> 'na' && $this->input['scanner'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> scanner</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>scanner</b>
                                                                                              &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="scanner" onchange='this.form.submit();'>
                                    <option <?php echo $this->input['scanner'] == 'na' ? 'selected' : ''?> value="na"> non-défini </option>
                                    <option <?php echo $this->input['scanner'] == '1std' ? 'selected' : ''?> value="1std">1D standard</option>
                                    <option <?php echo $this->input['scanner'] == '1lg' ? 'selected' : ''?> value="1lg">1D longue portée</option>
                                    <option <?php echo $this->input['scanner'] == '1xlg' ? 'selected' : ''?> value="1xlg">1D trés longue portée</option>
                                    <option <?php echo $this->input['scanner'] == '2std' ? 'selected' : ''?> value="2std">2D standard</option>
                                    <option <?php echo $this->input['scanner'] == '2lg' ? 'selected' : ''?> value="2lg">2D longue portée</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--SCANNER-->

                <!--CLAVIER-->
                <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 ">
                            <?php if($this->input['clavier'] <> 'na' && $this->input['clavier'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> clavier</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>clavier</b>
                                                                                              &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <select name="clavier" onchange='this.form.submit();'>
                                    <option <?php echo $this->input['clavier'] == 'na' ? 'selected' : ''?> value="na">non-défini</option>
                                    <option <?php echo $this->input['clavier'] == 'nume' ? 'selected' : ''?> value="nume">numérique</option>
                                    <option <?php echo $this->input['clavier'] == 'alpha' ? 'selected' : ''?> value="alpha">alphanumérique</option>
                                    <option <?php echo $this->input['clavier'] == 'tactil' ? 'selected' : ''?> value="tactil">tactile</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--CLAVIER-->

                <!--INTERFACR-->
                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <?php if($this->input['com'] <> 'na' && $this->input['com'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i>  interface de communication et option</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>interface de communication et option</b>
                                                                                               &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>

                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-4">
                            <div class="checkbox">
                                <label>
                                    wifi
                                    <input <?php echo isset($this->input['com']['wifi']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="com[]"
                                            value="wifi">
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    narrowband
                                    <input <?php echo isset($this->input['com']['narrow']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="com[]"
                                            value="narrow">
                                </label>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="checkbox">
                                <label>
                                    gprs
                                    <input <?php echo isset($this->input['com']['gprs']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="com[]"
                                            value="gprs">
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    gsm
                                    <input <?php echo isset($this->input['com']['gsm']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="com[]"
                                            value="gsm">
                                </label>
                            </div>

                        </div>
                        <div class="col-lg-4">
                            <div class="checkbox">
                                <label>
                                    rfid
                                    <input <?php echo isset($this->input['com']['rfid']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="com[]"
                                            value="rfid">
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    grand froid
                                    <input <?php echo isset($this->input['com']['gf']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="com[]"
                                            value="gf">
                                </label>
                            </div>

                        </div>
                    </div>

                </div>
                <!--INTERFACR-->

            </div>
        </div>
    </div>


    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->
</form>