<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>

    <div class="row form-section">
        <div class="col-lg-12">
            <?php
            //var_dump($this->search) ;
            //var_dump($this->input) ;
            ?>
        </div>
    </div>

    <div class="row " >
        <div class="col-lg-12 ">
            <div class="row wrapper-configurator-section ">
                <div class="col-md-10 text-left configurator">
                    <div class="configurator-title">
                                    <span class="fa-stack fa-lg" style="font-size: 2em">
                                        <i class="fa fa-circle fa-stack-2x " style="font-size: 2em ; color:white;"></i>
                                        <i class="fa fa-print fa-stack-1x " ></i>
                                    </span>
                        Imprimantes - MATRICIELLE
                        <br>
                    </div>
                </div>
                <div class="col-md-2 configurator-img" style="background-color: #004FAE;">
                    <div class="configurator-title right  pull-right">
                        <img style=" width 82px; height: 82px ; border-radius: 82px ; " src="<?php echo PROJECTS.'/upload/images/geo/pf4i.jpg' ?>" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row " style="padding-top:10px;background-color: white;">
        <div class="col-lg-12 ">

            <div class="form-section row wrapper-content-configurator ">

                <!--MARQUE-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    marque</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression <b><u>xxxxxxxxxx xxxxxxxxxxx </u><b>"
                                > </i>
                            <?php else: ?>
                                marque
                                                                                               &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression <br><br> <b><u>xxxxxxxxxx xxxxxxxxxxx </u> <br><br><b>"
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="marque">
                                    <option <?php echo $this->input['marque'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['marque'] == 'm_lexmark' ? 'selected' : '' ?> value="m_lexmark"> lexmark </option>
                                    <option <?php echo $this->input['marque'] == 'm_ibm' ? 'selected' : '' ?> value="m_ibm"> ibm </option>
                                    <option <?php echo $this->input['marque'] == 'm_epson' ? 'selected' : '' ?> value="m_epson"> epson </option>
                                    <option <?php echo $this->input['marque'] == 'm_oki' ? 'selected' : '' ?> value="m_oki"> oki </option>
                                    <option <?php echo $this->input['marque'] == 'all' ? 'selected' : '' ?> value="all">toutes marques </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--FORMAT-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 visible-md visible-lg visible-sm">
                            <?php if ($this->input['format'] <> 'na' && $this->input['format'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    format </b> &nbsp;&nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                format    &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>

                            <?php endif ?>
                        </div>

                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <select name="format">
                                    <option value="na" <?php echo $this->input['format'] == 'na' ? 'selected' : '' ?> >non-défini</option>
                                    <option value="c_132" <?php echo $this->input['format'] == 'c_132' ? 'selected' : '' ?> > 132 colonnes</option>
                                    <option value="c_80" <?php echo $this->input['format'] == 'c_80' ? "selected" : '' ?> >80 colonnes </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--GAMME-->
                <div class="col-lg-4 col-sm-12 col-xs-12 ">
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <?php if ($this->input['gamme'] <> 'na' && $this->input['gamme'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    gamme</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                gamme &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <div class="select">
                                <select name="gamme">
                                    <option <?php echo $this->input['gamme'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['gamme'] == 'bureau' ? 'selected' : '' ?> value="bureau">bureau</option>
                                    <option <?php echo $this->input['gamme'] == 'indu' ? 'selected' : '' ?> value="indu">industrielle </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>


    <div class="row form-section">

        <!--UTILISATION-->
        <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12 visible-md visible-lg visible-sm">
                    <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            utilisation</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        utilisation &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>

            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12" style="padding-top: 8px">
                    <div class="select">
                        <select class="" name="use">
                            <option <?php echo $this->input['use'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                            <option <?php echo $this->input['use'] == 'ligne' ? 'selected' : '' ?> value="ligne">ligne</option>
                            <option <?php echo $this->input['use'] == 'aiguille' ? 'selected' : '' ?> value="aiguille">aiguille </option>
                        </select>
                        <div class="select_arrow"> </div>
                    </div>

                </div>
            </div>
        </div>
        <!--UTILISATION-->
        <div class="hidden-lg  form-section-sm">&nbsp;</div>

        <!--INTERFACE-->
        <div  class="col-lg-8 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            option & interface de communication</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        option & interface de communication   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4 ">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['eth']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="eth">
                            réseau
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['serie']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="serie">
                            série
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['parra']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="parra">
                            parallèle
                        </label>
                    </div>
                </div>

                <div class="col-lg-4 ">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['feuille']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="feuille">
                            feuille à feuille
                        </label>
                    </div>

                </div>
            </div>
        </div>
        <!--UTILISATION-->
    </div>

    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->
</form>