<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>

    <div class="row">
        <?php
        //var_dump($this->input);
        //var_dump($this->session);
        //var_dump($this->search);
        ?>
    </div>



    <div class="row " >
        <div class="col-lg-12 ">

            <?php
            $configurator =
                [
                    'icone' => 'fa-mobile-phone',
                    'title' => 'Terminaux mobiles & embarqué - PDA',
                    'etape' => 'etape-2.phtml',
                    'photo' => '/upload/images/geo/pda_.jpg'
                ]
            ?>
            <?php include('configurator_title.phtml') ?>
        </div>
    </div>
    <?php if($this->error !== null) : ?>
        <div class=" row" style="padding-top: 10px;background-color: white;">
            <div class="col-lg-12 col-md-10 col-sm-12  " >
                <p style="padding: 10px" class="alert-danger "><?php echo $this->error ?></p>
            </div>
        </div>
    <?php endif ?>


    <div class="row " style="padding-top:10px;background-color: white;">
        <div class="col-lg-12 ">

            <div class="form-section row wrapper-content-configurator ">

                <!--MARQUES  -->
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    marque </b> &nbsp;&nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['pda_marque'] ?>"
                                > </i>
                            <?php else: ?>
                                <b>marque</b>    &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['pda_marque'] ?>"
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                    <select class="active"  name="marque" onchange='this.form.submit();'">
                                <?php else: ?>
                                    <select  name="marque" onchange='this.form.submit();'">
                                <?php endif ?>
                                    <option  value="na" <?php echo $this->input['marque'] == 'na' ? 'selected' : ''?> >non-défini</option>
                                    <option  value="m_zebra" <?php echo $this->input['marque'] == 'm_zebra' ? 'selected' : ''?> >Zebra</option>
                                    <option  value="m_motorola" <?php echo $this->input['marque'] == 'm_motorola' ? 'selected' : ''?> >Motorola</option>
                                    <option  value="m_datalogic" <?php echo $this->input['marque'] == 'm_datalogic' ? "selected" : ''?> >Datalogic</option>
                                    <option  value="m_intermec" <?php echo $this->input['marque'] == 'm_intermec' ? "selected" : ''?> >Intermec</option>
                                    <option  value="m_honeywell" <?php echo $this->input['marque'] == 'm_honeywell' ? "selected" : ''?> >Honeywell</option>
                                    <option  value="m_opticon" <?php echo $this->input['marque'] == 'm_opticon' ? "selected" : ''?> >Opticon</option>
                                    <option  value="all" <?php echo $this->input['marque'] == 'all' ? "selected" : ''?> >toutes marques</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--MARQUES  -->

                <!--SCANNER-->
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 ">
                            <?php if ($this->input['scanner'] <> 'na' && $this->input['scanner'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    scanner</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['pda_scanner'] ?>"

                                > </i>
                            <?php else: ?>
                                <b>scanner</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['pda_scanner'] ?>"

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <?php if ($this->input['scanner'] <> 'na' && $this->input['scanner'] <> null): ?>
                                    <select class="active"  name="scanner" onchange='this.form.submit();'">
                                <?php else: ?>
                                    <select  name="scanner" onchange='this.form.submit();'">
                                <?php endif ?>
                                    <option <?php echo $this->input['scanner'] == 'na' ? 'selected' : ''?> value="na"> non-défini </option>
                                    <option <?php echo $this->input['scanner'] == '1std' ? 'selected' : ''?> value="1std">1D standard</option>
                                    <option <?php echo $this->input['scanner'] == '2std' ? 'selected' : ''?> value="2std">2D standard</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--SCANNER-->

            </div>

            <div class="form-section row wrapper-content-configurator ">

                <!--CLAVIER-->
                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <?php if ($this->input['clavier'] <> 'na' && $this->input['clavier'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    clavier</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['pda_clavier'] ?>"
                                > </i>
                            <?php else: ?>
                                <b>clavier</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['pda_clavier'] ?>"
                                > </i>
                            <?php endif ?>

                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <div class="select">
                                <?php if ($this->input['clavier'] <> 'na' && $this->input['clavier'] <> null): ?>
                                    <select class="active"  name="clavier" onchange='this.form.submit();'">
                                <?php else: ?>
                                    <select  name="clavier" onchange='this.form.submit();'">
                                <?php endif ?>
                                    <option <?php echo $this->input['clavier'] == 'na' ? 'selected' : ''?> value="na">non-défini</option>
                                    <option <?php echo $this->input['clavier'] == 'nume' ? 'selected' : ''?> value="nume">numerique</option>
                                    <option <?php echo $this->input['clavier'] == 'alpha' ? 'selected' : ''?> value="alpha">alphanumerique</option>
                                    <option <?php echo $this->input['clavier'] == 'tactile' ? 'selected' : ''?> value="tactile">tactile</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!--CLAVIER-->

                <!--SYSTEM OS -->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 ">
                            <?php if ($this->input['os'] <> 'na' && $this->input['os'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    système</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['pda_os'] ?>"

                                > </i>
                            <?php else: ?>
                                <b>système</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['pda_os'] ?>"

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <?php if ($this->input['os'] <> 'na' && $this->input['os'] <> null): ?>
                                    <select class="active"  name="os" onchange='this.form.submit();'">
                                <?php else: ?>
                                    <select  name="os" onchange='this.form.submit();'">
                                <?php endif ?>
                                    <option  value="na" <?php echo $this->input['os'] == 'na' ? 'selected' : ''?> >non-défini</option>
                                    <option  value="ce" <?php echo $this->input['os'] == 'ce' ? 'selected' : ''?> >Windows CE</option>
                                    <option  value="mo" <?php echo $this->input['os'] == 'mo' ? 'selected' : ''?> >Windows mobile</option>
                                    <option  value="android" <?php echo $this->input['os'] == 'android' ? "selected" : ''?> >Android</option>
                                    <option  value="os_propri" <?php echo $this->input['os'] == 'os_propri' ? "selected" : ''?> >propriètaire</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--SYSTEM OS -->

                <!--INTERFACE-->
                <div class="col-lg-4 col-sm-12 col-xs-12">
                    <div class="row">
                        <div class="col-lg-12  col-xs-12">
                            <?php if($this->input['com'] <> 'na' && $this->input['com'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i>  interface de communication </b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['pda_com'] ?>"

                                > </i>
                            <?php else: ?>
                                <b>interface de communication</b>
                                                                                               &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['pda_com'] ?>"

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-6">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['com']['wifi']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="com[]"
                                            value="wifi">
                                    wifi
                                </label>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['com']['bluetooh']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="com[]"
                                            value="bluetooh">
                                    bluetooth
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <!--INTERFACE-->

            </div>

            <div class="form-section row wrapper-content-configurator ">

                <!--OPTION-->
                <div class="col-lg-6 col-sm-12 col-xs-12">
                    <div class="row">
                        <div class="col-lg-12  col-xs-12">
                            <?php if ($this->input['option'] <> 'na' && $this->input['option'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    options</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['pda_opt'] ?>"
                                > </i>
                            <?php else: ?>
                                <b>options</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['pda_opt'] ?>"
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-4">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['gf']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="option[]"
                                            value="gf">
                                    grand froid
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['3g']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="option[]"
                                            value="3g">
                                    téléphonie 3G &nbsp;&nbsp;&nbsp;&nbsp;
                                </label>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['4g']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="option[]"
                                            value="4g">
                                    téléphonie 4G
                                </label>
                            </div>

                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['picture']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="option[]"
                                            value="picture">
                                    appareil photo
                                </label>
                            </div>

                        </div>

                        <div class="col-lg-4">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['gps']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="option[]"
                                            value="gps">
                                    GPS
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['gsl']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="option[]"
                                            value="gsl">
                                    GSL
                                </label>
                            </div>

                        </div>
                    </div>
                </div>
                <!--OPTION-->

            </div>

        </div>
    </div>




    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->
</form>