<form action="/filtre/apply" method="post"
      class="wrapper_form-filtre"
>

    <div class="row">
        <?php
        //var_dump($this->input);
        //var_dump($this->session);
        //var_dump($this->input['option']);
        //var_dump($this->search);
        ?>
    </div>

    <div class="row " >
        <div class="col-lg-12 ">
            <div class="row wrapper-configurator-section ">
                <div class="col-md-10 text-left configurator">
                    <div class="configurator-title">
                                    <span class="fa-stack fa-lg" style="font-size: 2em">
                                        <i class="fa fa-circle fa-stack-2x " style="font-size: 2em ; color:white;"></i>
                                        <i class="fa fa-print fa-stack-1x " ></i>
                                    </span>
                        Terminaux mobiles & embarqué - POIGNET
                        <br>
                    </div>
                </div>
                <div class="col-md-2 configurator-img" style="background-color: #004FAE;">
                    <div class="configurator-title right  pull-right">
                        <img style=" width 82px; height: 82px ; border-radius: 82px ; " src="<?php echo PROJECTS.'/upload/images/geo/pf4i.jpg' ?>" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php if($this->input['option'] !== null) : ?>
    <div id="msgring" class=" row" style="padding-top: 10px;background-color: white;">
        <div class="col-lg-12 col-md-10 col-sm-12  " >
            <p class="alert-danger" style="padding: 10px">
                <b>ETAPE 1</b>  : choix du terminal poignet , valider le terminal selectionné grace au bouton caddy , pour passé a l'étape suivante afin de choisir votre scanner .
            </p>
        </div>
    </div>
    <?php endif ?>

    <div class="row " style="padding-top:10px;background-color: white;">
        <div class="col-lg-12 ">

            <div class="form-section row wrapper-content-configurator ">

                <!--MARQUE-->
                <div class="col-lg-4 col-sm-4 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> marque</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <i class="fa fa-angle-right" style="margin-right: 15px"> </i> marque
                                                                                              &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="marque">
                                    <option  value="na" <?php echo $this->input['marque'] == 'na' ? 'selected' : ''?> >non-défini</option>
                                    <option  value="m_zebra" <?php echo $this->input['marque'] == 'm_zebra' ? 'selected' : ''?> >zebra</option>
                                    <option  value="m_motorola" <?php echo $this->input['marque'] == 'm_motorola' ? 'selected' : ''?> >motorola</option>
                                    <option  value="m_intermec" <?php echo $this->input['marque'] == 'm_intermec' ? "selected" : ''?> >intermec</option>
                                    <option  value="m_honeywell" <?php echo $this->input['marque'] == 'm_honeywell' ? "selected" : ''?> >honeywell</option>
                                    <option  value="all" <?php echo $this->input['marque'] == 'all' ? "selected" : ''?> >toutes marques</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--FORMAT-->
                <div class="col-lg-4 col-sm-8 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 visible-md visible-lg visible-sm">
                            <?php if($this->input['format'] <> 'na' && $this->input['format'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> format</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                format
                                                                                              &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>

                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <select name="format">
                                    <option <?php echo $this->input['format'] == 'na' ? 'selected' : ''?> value="na"> non-défini </option>
                                    <option <?php echo $this->input['format'] == 'clavier' ? 'selected' : ''?> value="clavier">clavier</option>
                                    <option <?php echo $this->input['format'] == 'tactile' ? 'selected' : ''?> value="tactile">tactile</option>
                                    <option <?php echo $this->input['format'] == 'vocal' ? 'selected' : ''?> value="vocal">commande vocal</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--VIEWPORT-->
                <div class="hidden-lg form-section-sm">&nbsp;</div>

                <!--SYSTEME-->
                <div class="col-lg-4 col-sm-12 col-xs-12 ">
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <?php if($this->input['os'] <> 'na' && $this->input['os'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> système</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                système
                                                                                              &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>

                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <div class="select">
                                <select name="os">
                                    <option  value="na" <?php echo $this->input['os'] == 'na' ? 'selected' : ''?> >non-défini</option>
                                    <option  value="win_embeded_compact" <?php echo $this->input['os'] == 'win_embeded_compact' ? 'selected' : ''?> >windows embeded compact</option>
                                    <option  value="android" <?php echo $this->input['os'] == 'android' ? "selected" : ''?> >android</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>


    <div class="row bgw" >
        <!--OPTION  -->
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 ">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if($this->input['option'] <> 'na' && $this->input['option'] <> null): ?>
                        <b class="blue_royal">
                            <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            options
                        </b>
                        &nbsp; &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        options
                                                                                      &nbsp; &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row ">

                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['option']['scanner_1d']) ? 'checked' : ''?>
                                    id="scanner1d"
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="option[]"
                                    value="scanner_1d">
                            Scanner 1D
                        </label>
                    </div>
                </div>

                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['option']['scanner_2d']) ? 'checked' : ''?>
                                    id="scanner2d"
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="option[]"
                                    value="scanner_2d">
                            scanner 2D
                        </label>
                    </div>
                </div>


            </div>
        </div>
        <!--OPTION -->
    </div>




    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->
</form>