<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>


    <div class="row " >
            <div class="col-lg-12 ">
                <div class="row wrapper-configurator-section ">
                    <div class="col-md-10 text-left configurator">
                        <div class="configurator-title">
                                    <span class="fa-stack fa-lg" style="font-size: 2em">
                                        <i class="fa fa-circle fa-stack-2x " style="font-size: 2em ; color:white;"></i>
                                        <i class="fa fa-print fa-stack-1x " ></i>
                                    </span>
                            Imprimantes etiquettes - COULEUR
                            <br>
                        </div>
                    </div>
                    <div class="col-md-2 configurator-img" style="background-color: #004FAE;">
                        <div class="configurator-title right  pull-right">
                            <img style=" width 82px; height: 82px ; border-radius: 82px ; " src="<?php echo PROJECTS.'/upload/images/geo/LX100.jpg' ?>" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <div class="row">
        <div class="col-lg-12">
            <?php
            //var_dump($this->search) ;
            //var_dump($this->input) ;
            ?>
        </div>
    </div>

    <div class="row " style="padding-top:10px;background-color: white;">

        <div class="col-lg-12 ">

            <div class="form-section row wrapper-content-configurator ">

                <!--RESOLUTION -->
                <div class="col-lg-4 col-sm-12 col-xs-12">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if ($this->input['dpi'] <> 'na' && $this->input['dpi'] <> null): ?>

                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    résolution</b>   &nbsp;

                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                résolution    &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>

                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="select">
                                <select class="" name="dpi">
                                    <option value="na" <?php echo $this->input['dpi'] == 'na' ? 'selected' : '' ?> >non-défini</option>
                                    <option value="300" <?php echo $this->input['dpi'] == '300' ? 'selected' : '' ?> >&nbsp;&nbsp;300 dpi </option>
                                    <option value="600" <?php echo $this->input['dpi'] == '600' ? "selected" : '' ?> >&nbsp;&nbsp;600 dpi </option>
                                    <option value="1200" <?php echo $this->input['dpi'] == '1200' ? "selected" : '' ?> >1200 dpi </option>
                                </select>
                                <div class="select_arrow"> </div>
                            </div>

                        </div>
                    </div>
                </div>

                <!--LARGEUR IMPRESSION-->
                <div class="col-lg-4 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 visible-md visible-lg visible-sm">
                            <?php if ($this->input['width'] <> 'na' && $this->input['width'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    largeur impression</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                largeur impression   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                        <div class="col-lg-12 visible-xs">
                            <?php if ($this->input['width'] <> 'na' && $this->input['width'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    largeur</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <i class="fa fa-angle-right" style="margin-right: 15px"> </i> largeur
                                                                                              &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">

                                <select name="width">
                                    <option <?php echo $this->input['width'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['width'] == '4' ? 'selected' : '' ?> value="4">4" (116mm) </option>
                                    <option <?php echo $this->input['width'] == '6' ? 'selected' : '' ?> value="6">6" (152mm) </option>
                                    <option <?php echo $this->input['width'] == '8' ? 'selected' : '' ?> value="8">8" (203mm) </option>
                                </select>
                                <div class="select_arrow"> </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--VIEWPORT-->
                <div class="hidden-lg form-section-sm">&nbsp;</div>

                <!--INTERFACE-->
                <div class="col-lg-4 col-sm-12 col-xs-12">
                    <div class="row">
                        <div class="col-lg-12  col-xs-12">
                            <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    interface de communication</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                interface de communication   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>


                    <div class="row ">
                        <div class="col-lg-6">
                            <div class="checkbox">
                                <label>
                                    parallèle
                                    <input id="noborder"
                                        <?php echo isset($this->input['interface']['parra']) ? 'checked' : '' ?>
                                           class="checknoshadow " type="checkbox" name="interfacep[]" value="parra">
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    usb
                                    <input id="noborder"
                                        <?php echo isset($this->input['interface']['usb']) ? 'checked' : '' ?>
                                           class="checknoshadow " type="checkbox" name="interfacep[]" value="usb">
                                </label>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="checkbox">
                                <label>
                                    réseau
                                    <input id="noborder"
                                        <?php echo isset($this->input['interface']['eth']) ? 'checked' : '' ?>
                                           class="checknoshadow " type="checkbox" name="interfacep[]" value="eth">
                                </label>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>


    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->
</form>