<form action="/filtre/apply" method="post"
      class="wrapper_form-filtre"
>
    <div class="row form-section" >
        <div class="col-lg-6 col-md-6 col-sm-12 h2 ">
            <b>Imprimante - Badgeuse</b>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 h2">
            <?php include('aide_imprimante_badgeuse.phtml') ?>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <?php
            //var_dump($this->search) ;
            //var_dump($this->input) ;
            ?>
        </div>
    </div>

    <div class="row ">
        <!--UTILISATION -->
        <div  class="col-lg-4 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-xs-12 col-lg-12">
                    <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Mode d'impression </b> &nbsp;&nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Mode d'impression    &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>

                    <?php endif ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12" style="padding-top: 8px">
                    <select class="form-control" name="use">
                        <option value="na" <?php echo $this->input['use'] == 'na' ? 'selected' : '' ?> >Non-défini</option>
                        <option value="one_face" <?php echo $this->input['use'] == 'one_face' ? 'selected' : '' ?> > Une face </option>
                        <option value="dual_face" <?php echo $this->input['use'] == 'dual_face' ? "selected" : '' ?> >deux faces </option>
                    </select>
                </div>
            </div>
        </div>
        <!--FIN UTILISATION-->
        <div class="hidden-lg form-section-sm">&nbsp;</div>
        <!--OPTION ENCODAGE-->
        <div  class="col-lg-7 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12 visible-md visible-lg visible-sm">
                    <?php if ($this->input['opt'] <> 'na' && $this->input['opt'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Options & Encodage</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Options & Encodage   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
                <div class="col-lg-12 visible-xs">
                    <?php if ($this->input['opt'] <> 'na' && $this->input['opt'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Options</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Options
                                                                                      &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row">
                <!--MAGNETIQUE-->
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['opt']['magnetique']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="optd[]" value="magnetique">
                            Magnétique
                        </label>
                    </div>
                </div>
                <!-- / MAGNETIQUE-->

                <!--PUCE-->
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['opt']['puce']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="optd[]" value="puce">
                            Puce
                        </label>
                    </div>
                </div>
                <!-- / PUCE-->

                <!--NFC-->
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['opt']['nfc']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="optd[]" value="nfc">
                            NFC
                        </label>
                    </div>
                </div>
                <!-- / NFC-->

                <!--RFID-->
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['opt']['rfid']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="optd[]" value="rfid">
                            RFID
                        </label>
                    </div>
                </div>
                <!-- / RFID-->

                <!--RFID-->
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['opt']['serrure']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="optd[]" value="serrure">
                            Sécurité serrure
                        </label>
                    </div>
                </div>
                <!-- / RFID-->
            </div>
        </div>
        <!--OPTION ENCODAGE-->
    </div>

    <div class="row form-section">
        <div class="hidden-lg form-section-sm">&nbsp;</div>
        <!--INTERFACE-->
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Interaface de connection</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i>  Interface de connection   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row">
                <!--PARRALLELE-->
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['wifi']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="interfacep[]" value="wifi">
                            Wifi
                        </label>
                    </div>
                </div>

                <!--USB-->
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['usb']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="interfacep[]" value="usb">
                            Usb
                        </label>
                    </div>
                </div>

                <!--RESEAU / ETH -->
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6 ">
                    <div class="checkbox" >
                        <label>
                            <input <?php echo isset($this->input['interface']['eth']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="interfacep[]" value="eth">
                            Réseau
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <!--UTILISATION-->
    </div>

    <!--BOUTTON DE VALIDATION-->
    <div class="row">
        <div class="col-lg-8 col-sm-8 col-xs-8">
            <input type="submit" class="btn btn-euro-blue " value="Filtrer">
        </div>

        <div class="col-lg-4 col-sm-4 col-xs-4">
            <a href="filtre/delete" class="btn btn-euro-pink"
            >Reset</a>
        </div>
    </div>
    <!--BOUTTON DE VALIDATION-->
</form>