<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>

    <div class="row">
        <?php
        //var_dump($this->input);
        //var_dump($this->session);
        //var_dump($this->search);
        ?>
    </div>
    <div class="row " >
        <div class="col-lg-12 ">
            <div class="row wrapper-configurator-section ">
                <div class="col-md-10 text-left configurator">
                    <div class="configurator-title">
                        <a class="anconfigurator" href="/configurateur">
                            <span class="fa-stack fa-lg" style="font-size: 2em">
                                <i class="fa fa-circle fa-stack-2x " style="font-size: 2em ; color:white;"></i>
                                <i class="fa fa-mobile fa-stack-1x " ></i>
                            </span>
                        </a>
                        <br>
                        <div style="
                            padding-left: 77px;
                            margin-top:-55px;
                            text-decoration-style: initial;
                            font-weight: lighter;
                            position: relative;
                            font-size: 0.7em;
                            padding-bottom: 10px;
                            "
                        >
                            <a
                                    style="font-size: 2em;font-weight: bold"
                                    class="anconfigurator" href="/configurateur"> Terminaux mobiles & embarqué - PDA
                            </a><br>
                            <span style="letter-spacing: 2px; border-bottom: 1px lightsteelblue dashed">DEFINITION des caractéristiques</span> - Etape <b>2</b>&nbsp;/&nbsp;3
                        </div>
                    </div>
                </div>

                <div class="col-md-2 configurator-img" style="background-color: #004FAE;">
                    <div class="configurator-title right  pull-right">
                        <img style=" width 82px; height: 89px ; border-radius: 82px ; " src="<?php echo PROJECTS.'/upload/images/geo/pf4i.jpg' ?>" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row " style="padding-top:10px;background-color: white;">
        <div class="col-lg-12 ">

            <div class="form-section row wrapper-content-configurator ">

                <!--MARQUES  -->
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    marque </b> &nbsp;&nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit <br> l'environement <br> et le volume  <br> d'impression <br> xxxxxxxxxx <br> xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                marque    &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit <br> l'environement <br> et le volume  <br> d'impression <br> xxxxxxxxxx <br> xxxxxxxxxxx"
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="marque">
                                    <option  value="na" <?php echo $this->input['marque'] == 'na' ? 'selected' : ''?> >non-défini</option>
                                    <option  value="m_zebra" <?php echo $this->input['marque'] == 'm_zebra' ? 'selected' : ''?> >zebra</option>
                                    <option  value="m_motorola" <?php echo $this->input['marque'] == 'm_motorola' ? 'selected' : ''?> >motorola</option>
                                    <option  value="m_datalogic" <?php echo $this->input['marque'] == 'm_datalogic' ? "selected" : ''?> >datalogic</option>
                                    <option  value="m_intermec" <?php echo $this->input['marque'] == 'm_intermec' ? "selected" : ''?> >intermec</option>
                                    <option  value="m_honeywell" <?php echo $this->input['marque'] == 'm_honeywell' ? "selected" : ''?> >honeywell</option>
                                    <option  value="all" <?php echo $this->input['marque'] == 'all' ? "selected" : ''?> >toutes marques</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--MARQUES  -->

                <!--SCANNER-->
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 visible-md visible-lg visible-sm">
                            <?php if ($this->input['scanner'] <> 'na' && $this->input['scanner'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    scanner</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                scanner   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <select name="scanner">
                                    <option <?php echo $this->input['scanner'] == 'na' ? 'selected' : ''?> value="na"> non-défini </option>
                                    <option <?php echo $this->input['scanner'] == '1std' ? 'selected' : ''?> value="1std">1d standard</option>
                                    <option <?php echo $this->input['scanner'] == '1lg' ? 'selected' : ''?> value="1lg">1d longue portée</option>
                                    <option <?php echo $this->input['scanner'] == '1xlg' ? 'selected' : ''?> value="1xlg">1d trés longue portée</option>
                                    <option <?php echo $this->input['scanner'] == '2std' ? 'selected' : ''?> value="2std">2d standard</option>
                                    <option <?php echo $this->input['scanner'] == '2lg' ? 'selected' : ''?> value="2lg">2d longue portée</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--SCANNER-->

            </div>

            <div class="form-section row wrapper-content-configurator ">

                <!--CLAVIER-->
                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <?php if ($this->input['clavier'] <> 'na' && $this->input['clavier'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    clavier</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                clavier
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>

                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <div class="select">
                                <select name="clavier">
                                    <option <?php echo $this->input['clavier'] == 'na' ? 'selected' : ''?> value="na">non-défini</option>
                                    <option <?php echo $this->input['clavier'] == 'nume' ? 'selected' : ''?> value="nume">numerique</option>
                                    <option <?php echo $this->input['clavier'] == 'alpha' ? 'selected' : ''?> value="alpha">alphanumerique</option>
                                    <option <?php echo $this->input['clavier'] == 'tactile' ? 'selected' : ''?> value="tactile">tactile</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!--CLAVIER-->

                <!--SYSTEM OS -->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 visible-md visible-lg visible-sm">
                            <?php if ($this->input['os'] <> 'na' && $this->input['os'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    système</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                système   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <select name="os">
                                    <option  value="na" <?php echo $this->input['os'] == 'na' ? 'selected' : ''?> >non-défini</option>
                                    <option  value="ce" <?php echo $this->input['os'] == 'ce' ? 'selected' : ''?> >win ce</option>
                                    <option  value="mo" <?php echo $this->input['os'] == 'mo' ? 'selected' : ''?> >win mobile</option>
                                    <option  value="android" <?php echo $this->input['os'] == 'android' ? "selected" : ''?> >android</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--SYSTEM OS -->

                <!--INTERFACE-->
                <div class="col-lg-4 col-sm-12 col-xs-12">
                    <div class="row">
                        <div class="col-lg-12  col-xs-12">
                            <?php if($this->input['com'] <> 'na' && $this->input['com'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i>  interface de communication </b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <i class="fa fa-angle-right" style="margin-right: 15px"> </i>  interface de communication
                                                                                               &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-6">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['com']['wifi']) ? 'checked' : ''?>
                                            class="checknoshadow"
                                            type="checkbox"
                                            name="com[]"
                                            value="wifi">
                                    wifi
                                </label>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['com']['bluetooh']) ? 'checked' : ''?>
                                            class="checknoshadow"
                                            type="checkbox"
                                            name="com[]"
                                            value="bluetooh">
                                    bluetooh
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <!--INTERFACE-->

            </div>

            <div class="form-section row wrapper-content-configurator ">

                <!--OPTION-->
                <div class="col-lg-6 col-sm-12 col-xs-12">
                    <div class="row">
                        <div class="col-lg-12  col-xs-12">
                            <?php if ($this->input['option'] <> 'na' && $this->input['option'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    option</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                option   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-4">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['gf']) ? 'checked' : ''?>
                                            class="checknoshadow"
                                            type="checkbox"
                                            name="option[]"
                                            value="gf">
                                    grand froid
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['3g']) ? 'checked' : ''?>
                                            class="checknoshadow"
                                            type="checkbox"
                                            name="option[]"
                                            value="3g">
                                    téléphonie 3G &nbsp;&nbsp;&nbsp;&nbsp;
                                </label>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['4g']) ? 'checked' : ''?>
                                            class="checknoshadow"
                                            type="checkbox"
                                            name="option[]"
                                            value="4g">
                                    téléphonie 4G
                                </label>
                            </div>

                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['picture']) ? 'checked' : ''?>
                                            class="checknoshadow"
                                            type="checkbox"
                                            name="option[]"
                                            value="picture">
                                    appareil photo
                                </label>
                            </div>

                        </div>

                        <div class="col-lg-4">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['gps']) ? 'checked' : ''?>
                                            class="checknoshadow"
                                            type="checkbox"
                                            name="option[]"
                                            value="gps">
                                    GPS
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['gsl']) ? 'checked' : ''?>
                                            class="checknoshadow"
                                            type="checkbox"
                                            name="option[]"
                                            value="gsl">
                                    GSL
                                </label>
                            </div>

                        </div>
                    </div>
                </div>
                <!--OPTION-->

            </div>

        </div>
    </div>




    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->
</form>