

<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>
    <!--TESTING INPUT -->
    <div class="row">
        <?php
        //var_dump($this->search);
        //var_dump($this->input);
        //var_dump($this->message);
        ?>
    </div>
    <!--TESTING INPUT -->

    <div class="row " >
        <div class="col-lg-12 ">

            <?php
            $configurator =
                [
                    'icone' => 'fa-barcode',
                    'title' => 'Lecteurs code-barres - RING',
                    'etape' => 'etape-2.phtml',
                    'photo' => '/upload/images/geo/ring_.jpg'
                ]
            ?>
            <?php include('configurator_title.phtml') ?>
        </div>
    </div>


    <?php if($this->message !== null) : ?>
    <div class=" row" style="padding-top: 10px;background-color: white;">
        <div class="col-lg-12 col-md-10 col-sm-12  " >
            <p style="padding: 10px" class="alert-danger "><?php echo $this->message ?></p>
        </div>
    </div>
    <?php endif ?>

    <div class="row " style="padding-top:10px;background-color: white;">
        <div class="col-lg-12 ">

            <div class="form-section row wrapper-content-configurator ">

                <!--MARQUE-->
                <div class="col-lg-4 col-sm-4 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    marque</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>marque</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="marque" onchange='this.form.submit();'>
                                    <option <?php echo $this->input['marque'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['marque'] == 'm_zebra' ? 'selected' : '' ?> value="m_zebra"> Zebra </option>
                                    <option <?php echo $this->input['marque'] == 'm_intermec' ? 'selected' : '' ?> value="m_intermec">Intermec </option>
                                    <option <?php echo $this->input['marque'] == 'm_honeywell' ? 'selected' : '' ?> value="m_honeywell">Honeywell </option>
                                    <option <?php echo $this->input['marque'] == 'all' ? 'selected' : '' ?> value="all">toutes marques </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--SCANNER-->
                <div class="col-lg-4 col-sm-8 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 ">
                            <?php if($this->input['laser'] <> 'na' && $this->input['laser'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" > </i> scanner</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>scanner</b>
                                                                                              &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>

                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <select name="laser" onchange='this.form.submit();'>
                                    <option <?php echo $this->input['laser'] == 'na' ? 'selected' : ''?> value="na"> non-défini </option>
                                    <option <?php echo $this->input['laser'] == '1d' ? 'selected' : ''?> value="1d">1D </option>
                                    <option <?php echo $this->input['laser'] == '2d' ? 'selected' : ''?> value="2d">2D </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--INTERFACE-->
                <div class="col-lg-4 col-sm-12 col-xs-12 ">
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    interface de communication </b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>interface de communication</b>  &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>

                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <div class="select">
                                <select name="interface" onchange='this.form.submit();'>
                                    <option <?php echo $this->input['interface'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['interface'] == 'bluetooh' ? 'selected' : '' ?> value="bluetooh"> bluetooth </option>
                                    <option <?php echo $this->input['interface'] == 'filaire' ? 'selected' : '' ?> value="filaire"> filaire </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>

        </div>
    </div>


    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->
</form>