<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>

    <div class="row " >
        <div class="col-lg-12 ">
            <?php
            $configurator =
                [
                    'icone' => 'fa-print',
                    'title' => 'Imprimantes - LASER',
                    'etape' => 'etape-2.phtml',
                    'photo' => '/upload/images/geo/laser_1.jpg'
                ]
            ?>
            <?php include('configurator_title.phtml') ?>
        </div>
    </div>
    <?php if($this->error !== null) : ?>
        <div class=" row" style="padding-top: 10px;background-color: white;">
            <div class="col-lg-12 col-md-10 col-sm-12  " >
                <p style="padding: 10px" class="alert-danger "><?php echo $this->error ?></p>
            </div>
        </div>
    <?php endif ?>

    <div class="row " style="padding-top:10px;background-color: white;">
        <div class="col-lg-12 ">

            <div class="form-section row wrapper-content-configurator ">

                <!--MARQUE-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    marque</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>marque</b>
                                                                                               &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="marque" onchange='this.form.submit();'>
                                    <option <?php echo $this->input['marque'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['marque'] == 'm_hp' ? 'selected' : '' ?> value="m_hp"> HP </option>
                                    <option <?php echo $this->input['marque'] == 'm_lexmark' ? 'selected' : '' ?> value="m_lexmark"> Lexmark </option>
                                    <option <?php echo $this->input['marque'] == 'all' ? 'selected' : '' ?> value="all">toutes marques </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--FORMAT-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 ">
                            <?php if ($this->input['format'] <> 'na' && $this->input['format'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    format </b> &nbsp;&nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>format</b>    &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>

                            <?php endif ?>
                        </div>

                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <select name="format" onchange='this.form.submit();'>
                                    <option value="na" <?php echo $this->input['format'] == 'na' ? 'selected' : '' ?> >non-défini</option>
                                    <option value="a4" <?php echo $this->input['format'] == 'a4' ? 'selected' : '' ?> > A4</option>
                                    <option value="a3" <?php echo $this->input['format'] == 'a3' ? "selected" : '' ?> >A3 </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--GAMME-->
                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <?php if ($this->input['gamme'] <> 'na' && $this->input['gamme'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    gamme</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>gamme</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>

                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <div class="select">
                                <select name="gamme" onchange='this.form.submit();'>
                                    <option <?php echo $this->input['gamme'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['gamme'] == 'groupe_petit' ? 'selected' : '' ?> value="groupe_petit">petit groupe de travail </option>
                                    <option <?php echo $this->input['gamme'] == 'droupe_dep' ? 'selected' : '' ?> value="droupe_dep">groupe départemental </option>
                                </select>
                                <div class="select_arrow"> </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </div>


    <div class="form-section row" style="background-color: white;">

        <!--UTILISATION-->
        <div class="col-lg-4 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12 ">
                    <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            utilisation</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <b>utilisation</b> &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>

            </div>
            <div class="row ">
                <div class="col-lg-12 col-sm-12" >
                    <div class="select">
                        <select class="" name="use" onchange='this.form.submit();'>
                            <option <?php echo $this->input['use'] == 'na' ? 'selected' : '' ?> value="na">
                                non-défini
                            </option>
                            <option <?php echo $this->input['use'] == 'mono' ? 'selected' : '' ?> value="mono">
                                monochrome
                            </option>
                            <option <?php echo $this->input['use'] == 'couleur' ? 'selected' : '' ?> value="couleur">
                                couleur
                            </option>
                        </select>
                        <div class="select_arrow"></div>
                    </div>

                </div>
            </div>
        </div>

        <!--INTERFACE-->
        <div style="padding-bottom: 7px" class="col-lg-8 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            options & interface de communication</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <b>options & interface de communication</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4 ">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['rectov']) ? 'checked' : '' ?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="rectov">
                            recto / Verso
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['multi']) ? 'checked' : '' ?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="multi">
                            multifonction
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['eth']) ? 'checked' : '' ?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox" name="interfacep[]" value="eth">
                            réseau
                        </label>
                    </div>
                </div>
                <div class="col-lg-4 ">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['wifi']) ? 'checked' : '' ?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox" name="interfacep[]" value="wifi">
                            wifi
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['parra']) ? 'checked' : '' ?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox" name="interfacep[]" value="parra">
                            paralléle
                        </label>
                    </div>

                </div>
                <div class="col-lg-4 ">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['serie']) ? 'checked' : '' ?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox" name="interfacep[]" value="serie">
                            série
                        </label>
                    </div>

                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['usb']) ? 'checked' : '' ?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox" name="interfacep[]" value="usb">
                            usb
                        </label>
                    </div>
                </div>
            </div>

        </div>

    </div>


    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->
</form>