

<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>
    <!--TESTING INPUT -->
    <div class="row">
        <?php
        //var_dump($this->session);
        //var_dump($this->input);
        ?>
    </div>
    <!--TESTING INPUT -->


    <div class="row" >
        <div class="col-lg-10 col-md-10 col-sm-9 h2 ">
            <b>Lecteurs code-barres - Scanner fixe</b>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-3 h2">
            <?php include('aide_fixe.phtml') ?>
        </div>
    </div>

    <br>

    <div class="row form-section ">
        <!--MARQUES-->
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12">
                    <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Marques</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Marques   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <select class="form-control" name="marque">
                        <option <?php echo $this->input['marque'] == 'na' ? 'selected' : '' ?> value="na">Non-défini</option>
                        <option <?php echo $this->input['marque'] == 'm_zebra' ? 'selected' : '' ?> value="m_zebra"> Zebra </option>
                        <option <?php echo $this->input['marque'] == 'm_motorola' ? 'selected' : '' ?> value="m_motorola"> Motorola </option>
                        <option <?php echo $this->input['marque'] == 'm_symbol' ? 'selected' : '' ?> value="m_symbol">Symbol </option>
                        <option <?php echo $this->input['marque'] == 'm_datalogic' ? 'selected' : '' ?> value="m_datalogic">Datalogic</option>
                        <option <?php echo $this->input['marque'] == 'm_honeywell' ? 'selected' : '' ?> value="m_honeywell">Honeywell </option>
                        <option <?php echo $this->input['marque'] == 'm_opticon' ? 'selected' : '' ?> value="m_opticon">Opticon </option>
                        <option <?php echo $this->input['marque'] == 'all' ? 'selected' : '' ?> value="all">Toutes marques </option>
                    </select>
                </div>
            </div>
        </div>
        <!--MARQUES-->

        <div class="hidden-lg hidden-md form-section-sm">&nbsp;</div>

        <!--GAMMES-->
        <div class=" col-lg-4  col-md-6 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <?php if($this->input['gamme'] <> 'na' && $this->input['gamme'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> Gamme</b>
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Gamme
                                                                                      &nbsp;&nbsp; <i class="fa fa-question-circle"
                                                                                                      data-toggle="tooltip"
                                                                                                      data-placement="right"
                                                                                                      title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12" >
                    <select class="form-control" name="gamme" >
                        <option <?php echo $this->input['gamme'] == 'na' ? 'selected' : ''?> value="na">Non-défini</option>
                        <option <?php echo $this->input['gamme'] == 'bureau' ? 'selected' : ''?> value="bureau">bureau</option>
                        <option <?php echo $this->input['gamme'] == 'i' ? 'selected' : ''?> value="i">Industrielle</option>
                    </select>
                </div>
            </div>
        </div>
        <!--GAMMES-->

        <div class="hidden-lg  form-section-sm">&nbsp;</div>

        <!--TYPE-->
        <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12">
                    <?php if($this->input['type'] <> 'nr' && $this->input['type'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> Type</b>
                        &nbsp;&nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Type
                                                                                      &nbsp;&nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12" >

                    <select class="form-control" name="type" >
                        <option  value="nr" <?php echo $this->input['type'] == 'nr' ? 'selected' : ''?> >Non-défini</option>
                        <option  value="filaire" <?php echo $this->input['type'] == 'filaire' ? 'selected' : ''?> >Filaire</option>
                        <option  value="nofilaire" <?php echo $this->input['type'] == 'nofilaire' ? 'selected' : ''?> >Sans-fils</option>
                    </select>

                </div>
            </div>
        </div>
        <!--TYPE-->
    </div>

    <div class="row  form-section">
        <!--SCANNER-->
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12 visible-md visible-lg visible-sm">
                    <?php if($this->input['laser'] <> 'nr' && $this->input['laser'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> Scanner</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Scanner
                                                                                      &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>

            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12" style="padding-top: 8px">
                    <select class="form-control" name="laser" >
                        <option <?php echo $this->input['laser'] == 'nr' ? 'selected' : ''?> value="nr"> Non-défini </option>
                        <option <?php echo $this->input['laser'] == '1std' ? 'selected' : ''?> value="1std">1d std</option>
                        <option <?php echo $this->input['laser'] == '1lg' ? 'selected' : ''?> value="1lg">1d long range</option>
                        <option <?php echo $this->input['laser'] == '1xlg' ? 'selected' : ''?> value="1xlg">1d extra longue range</option>
                        <option <?php echo $this->input['laser'] == '2std' ? 'selected' : ''?> value="2std">2d std</option>
                        <option <?php echo $this->input['laser'] == '2lg' ? 'selected' : ''?> value="2lg">2d long range</option>
                    </select>
                </div>
            </div>
        </div>
        <!--SCANNER-->

        <div class="hidden-lg hidden-md form-section-sm">&nbsp;</div>

        <!--INTERFACE DOUCHETTE-->
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 ">
            <div class="row">
                <div class="col-lg-12">
                    <?php if($this->input['interfaced'] <> 'nr' && $this->input['interfaced'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i>  Interface de connection</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i>  Interface de connection
                                                                                       &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-4 col-sm-4 col-xs-4">
                    <div class="checkbox">
                        <label>
                            <input
                                <?php echo isset($this->input['interfaced']['bluetooh']) ? 'checked' : ''?>
                                class="checknoshadow"
                                type="checkbox"
                                name="interfaced[]"
                                value="bluetooh">
                            Bluetooh
                        </label>
                    </div>
                </div>

                <div class="col-lg-6 col-md-4 col-sm-4 col-xs-4">
                    <div class="checkbox">
                        <label>
                            <input
                                <?php echo isset($this->input['interfaced']['radio']) ? 'checked' : ''?>
                                class="checknoshadow"
                                type="checkbox"
                                name="interfaced[]"
                                value="radio">
                            Radio
                        </label>
                    </div>
                </div>

            </div>
        </div>
        <!--INTERFACE DOUCHETTE-->
    </div>

    <div class="row form-section ">
        <!--OPTIONS-->
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12 visible-md visible-lg visible-sm">
                    <?php if($this->input['optiond'] <> 'nr' && $this->input['optiond'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> Options de la douchette </b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Options de la douchette
                                                                                      &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>

            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12" >
                    <div class="col-lg-4 col-md-3 col-sm-3 col-xs-4">
                        <div class="checkbox">
                            <label>
                                <input
                                    <?php echo isset($this->input['optiond']['ecran']) ? 'checked' : ''?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="optiond[]"
                                    value="ecran">
                                Ecran
                            </label>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-3 col-sm-3 col-xs-4">
                        <div class="checkbox">
                            <label>
                                <input
                                    <?php echo isset($this->input['optiond']['clavier']) ? 'checked' : ''?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="optiond[]"
                                    value="clavier">
                                Clavier
                            </label>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-3 col-sm-3 col-xs-4">
                        <div class="checkbox">
                            <label>
                                <input
                                    <?php echo isset($this->input['optiond']['batch']) ? 'checked' : ''?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="interface[]"
                                    value="batch">
                                Batch
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--OPTIONS-->

        <div class="hidden-lg  form-section">&nbsp;</div>

        <!--INTERFACE SOCLE-->
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 ">
            <div class="row">
                <div class="col-lg-12">
                    <?php if($this->input['interfaceb'] <> 'nr' && $this->input['interfaceb'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i>  Interface de connection du socle</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i>  Interface de connection du socle
                                                                                       &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row">

                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                    <div class="checkbox">
                        <label>
                            <input
                                <?php echo isset($this->input['interfaceb']['eth']) ? 'checked' : ''?>
                                class="checknoshadow"
                                type="checkbox"
                                name="interfaceb[]"
                                value="eth">
                            Réseau
                        </label>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                    <div class="checkbox">
                        <label>
                            <input
                                <?php echo isset($this->input['interfaceb']['usb']) ? 'checked' : ''?>
                                class="checknoshadow"
                                type="checkbox"
                                name="interfaceb[]"
                                value="usb">
                            USB
                        </label>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                    <div class="checkbox">
                        <label>
                            <input
                                <?php echo isset($this->input['interfaceb']['serie']) ? 'checked' : ''?>
                                class="checknoshadow"
                                type="checkbox"
                                name="interfaceb[]"
                                value="serie">
                            Série
                        </label>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                    <div class="checkbox">
                        <label>
                            <input
                                <?php echo isset($this->input['interfaceb']['wedge']) ? 'checked' : ''?>
                                class="checknoshadow"
                                type="checkbox"
                                name="interfaceb[]"
                                value="wedge">
                            Wedge
                        </label>
                    </div>
                </div>

            </div>
        </div>
        <!--INTERFACE SOCLE-->
    </div>

    <!--BOUTTON DE VALIDATION-->
    <div class="row" >
        <div class="col-lg-8 col-sm-8 col-xs-8">
            <input type="submit" class="btn btn-euro-blue " value="Filtrer">
        </div>

        <div class="col-lg-4 col-sm-4 col-xs-4">
            <a href="filtre/delete" class="btn btn-euro-pink"
            >Reset</a>
        </div>
    </div>
    <!--BOUTTON DE VALIDATION-->
</form>