<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>

    <div class="row">
        <?php
        //var_dump($this->input);
        //var_dump($this->session);
        //var_dump($this->search);
        ?>
    </div>


    <div class="row " >
        <div class="col-lg-12 ">

            <?php
            $configurator =
                [
                    'icone' => 'fa-laptop',
                    'title' => 'Poste de travail - CLIENT LEGER',
                    'etape' => 'etape-2.phtml',
                    'photo' => '/upload/images/geo/cl_.jpg'
                ]
            ?>
            <?php include('configurator_title.phtml') ?>
        </div>
    </div>



    <div class="row " style="padding-top:10px;background-color: white;">

        <div class="col-lg-12 ">

            <div class="form-section row wrapper-content-configurator ">

                <!--MARQUES-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if($this->input['marque'] <> 'nr' && $this->input['marque'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> marque</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>marque</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="marque" onchange='this.form.submit();'">
                                    <option <?php echo $this->input['marque'] == 'nr' ? 'selected' : ''?> value="nr"> non-défini </option>
                                    <option <?php echo $this->input['marque'] == 'dell' ? 'selected' : ''?> value="dell">Dell - Wyse</option>
                                    <option <?php echo $this->input['marque'] == 'hp' ? 'selected' : ''?> value="hp">Hp</option>
                                    <option <?php echo $this->input['marque'] == 'axel' ? 'selected' : ''?> value="axel">Axel</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--MARQUES-->

                <!--SYSTEME-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if($this->input['os'] <> 'na' && $this->input['os'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> système</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>système</b>
                                                                                              &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="os" onchange='this.form.submit();'">
                                    <option  value="na" <?php echo $this->input['os'] == 'na' ? 'selected' : ''?> >non-défini</option>
                                    <option  value="win" <?php echo $this->input['os'] == 'win' ? 'selected' : ''?> >Windows</option>
                                    <option  value="linux" <?php echo $this->input['os'] == 'linux' ? 'selected' : ''?> >Linux</option>
                                    <option  value="propri" <?php echo $this->input['os'] == 'propri' ? 'selected' : ''?> >Propriétaire</option>
                                    <option  value="none_os" <?php echo $this->input['os'] == 'none_os' ? 'selected' : ''?> >Aucun système</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--SYSTEME-->

                <!--ECRAN-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if($this->input['ecran'] <> 'nr' && $this->input['ecran'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> écran</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>écran</b>
                                                                                              &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="ecran" onchange='this.form.submit();'">
                                    <option <?php echo $this->input['ecran'] == 'nr' ? 'selected' : ''?> value="nr"> non-défini </option>
                                    <option <?php echo $this->input['ecran'] == '17p' ? 'selected' : ''?> value="17p">17" 4/3</option>
                                    <option <?php echo $this->input['ecran'] == '19p_4' ? 'selected' : ''?> value="19p_4">19" 4/3</option>
                                    <option <?php echo $this->input['ecran'] == '19p_16' ? 'selected' : ''?> value="19p_16">19" 16/9</option>
                                    <option <?php echo $this->input['ecran'] == '22p' ? 'selected' : ''?> value="22p">22" 16/9</option>
                                    <option <?php echo $this->input['ecran'] == '24p' ? 'selected' : ''?> value="24p">24" 16/9</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--ECRAN-->

            </div>

        </div>
    </div>

    <div class="row " style="background-color: white;">

        <div class="col-lg-12 ">

            <div class="form-section row wrapper-content-configurator ">

                <!--RAM-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if($this->input['ram'] <> 'na' && $this->input['ram'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> mémoire RAM</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>mémoire RAM</b>
                                                                                              &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="ram" onchange='this.form.submit();'">
                                    <option  value="na" <?php echo $this->input['ram'] == 'na' ? 'selected' : ''?> >non-défini</option>
                                    <option  value="2gb_ram" <?php echo $this->input['ram'] == '2gb_ram' ? 'selected' : ''?> > < 2 GB</option>
                                    <option  value="4gb_ram" <?php echo $this->input['ram'] == '4gb_ram' ? 'selected' : ''?> >4 GB</option>
                                    <option  value="8gb_ram" <?php echo $this->input['ram'] == '8gb_ram' ? 'selected' : ''?> >8 GB</option>
                                    <option  value="16gb_ram" <?php echo $this->input['ram'] == '16gb_ram' ? 'selected' : ''?> >16 GB</option>
                                    <option  value="32gb_ram" <?php echo $this->input['ram'] == '32gb_ram' ? 'selected' : ''?> >32 GB</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--RAM-->

                <!--FLASH-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if($this->input['flash'] <> 'na' && $this->input['flash'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> mémoire flash</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>mémoire flash</b>
                                                                                              &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="flash" onchange='this.form.submit();'">
                                    <option  value="na" <?php echo $this->input['flash'] == 'na' ? 'selected' : ''?> >non-défini</option>
                                    <option  value="2gb_flash" <?php echo $this->input['flash'] == '2gb_flash' ? 'selected' : ''?> > < 2 GB</option>
                                    <option  value="4gb_flash" <?php echo $this->input['flash'] == '4gb_flash' ? 'selected' : ''?> >4 GB</option>
                                    <option  value="8gb_flash" <?php echo $this->input['flash'] == '8gb_flash' ? 'selected' : ''?> >8 GB</option>
                                    <option  value="16gb_flash" <?php echo $this->input['flash'] == '16gb_flash' ? 'selected' : ''?> >16 GB</option>
                                    <option  value="32gb_flash" <?php echo $this->input['flash'] == '32gb_flash' ? 'selected' : ''?> >32 GB</option>
                                    <option  value="64gb_flash" <?php echo $this->input['flash'] == '64gb_flash' ? 'selected' : ''?> >64 GB</option>
                                    <option  value="128gb_flash" <?php echo $this->input['flash'] == '128gb_flash' ? 'selected' : ''?> >128 GB</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--FLASH-->

                <!--OPTIONS-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if($this->input['option'] <> 'na' && $this->input['option'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> options</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>options</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">

                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['wifi']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="option[]"
                                            value="wifi">
                                    wifi
                                </label>
                            </div>

                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['dual_display']) ? 'checked' : ''?>
                                            class="checknoshadow" onclick='this.form.submit();'
                                            type="checkbox"
                                            name="option[]"
                                            value="dual_display">
                                    double affichage
                                </label>
                            </div>

                        </div>
                    </div>
                </div>
                <!--OPTIONS-->



            </div>

        </div>
    </div>


    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->
</form>