<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>

    <div class="row">
        <?php
        //var_dump($this->input['option']['douchette']);
        //var_dump($this->input);
        //var_dump($this->search);
        ?>
    </div>


    <div class="row " >
        <div class="col-lg-12 ">

            <?php
            $configurator =
                [
                    'icone' => 'fa-mobile-phone',
                    'title' => 'Terminaux mobiles & embarqué - EMBARQUE',
                    'etape' => 'etape-2.phtml',
                    'photo' => '/upload/images/geo/8525_.jpg'
                ]
            ?>
            <?php include('configurator_title.phtml') ?>
        </div>
    </div>
    <?php if($this->error !== null) : ?>
        <div class=" row" style="padding-top: 10px;background-color: white;">
            <div class="col-lg-12 col-md-10 col-sm-12  " >
                <p style="padding: 10px" class="alert-danger "><?php echo $this->error ?></p>
            </div>
        </div>
    <?php endif ?>
    <?php if($this->input['option']['douchette'] !== null) :?>
        <br>
    <div id="msgscanneremb" class=" row" style="padding-bottom: 10px;">
        <div class="col-lg-11 col-md-11 col-sm-12  " >
            <p class="alert-danger" style="padding: 10px">
                <b>ETAPE 1</b>  : choix du terminal embarqué , valider le terminal selectionné grace au bouton caddy , pour passé a l'étape suivante afin de choisir votre lecteur code-barres .
            </p>
        </div>
    </div>
    <?php endif ?>


    <div class="row " style="padding-top:10px;background-color: white;">
        <div class="col-lg-12 ">
            <div class="form-section row wrapper-content-configurator ">

                <!--MARQUES  -->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    marque </b> &nbsp;&nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['emb_marque'] ?>"
                                > </i>
                            <?php else: ?>
                                <b>marque</b>    &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['emb_marque'] ?>"
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                    <select class="active"  name="marque" >
                                <?php else: ?>
                                    <select  name="marque" >
                                <?php endif ?>
                                    <option  value="na" <?php echo $this->input['marque'] == 'na' ? 'selected' : ''?> >non-défini</option>
                                    <option  value="m_zebra" <?php echo $this->input['marque'] == 'm_zebra' ? 'selected' : ''?> >Zebra</option>
                                    <option  value="m_motorola" <?php echo $this->input['marque'] == 'm_motorola' ? 'selected' : ''?> >Motorola</option>
                                    <option  value="m_intermec" <?php echo $this->input['marque'] == 'm_intermec' ? "selected" : ''?> >Intermec</option>
                                    <option  value="m_honeywell" <?php echo $this->input['marque'] == 'm_honeywell' ? "selected" : ''?> >Honeywell</option>
                                    <option  value="m_psion" <?php echo $this->input['marque'] == 'm_psion' ? "selected" : ''?> >Psion</option>
                                    <option  value="all" <?php echo $this->input['marque'] == 'all' ? "selected" : ''?> >toutes marques</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--MARQUES  -->

                <!--FORMAT-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 ">
                            <?php if ($this->input['format'] <> 'na' && $this->input['format'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    format</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['emb_format'] ?>"

                                > </i>
                            <?php else: ?>
                                <b>format</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['emb_format'] ?>"

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <?php if ($this->input['format'] <> 'na' && $this->input['format'] <> null): ?>
                                    <select class="active"  name="format" >
                                <?php else: ?>
                                    <select  name="format" >
                                <?php endif ?>
                                    <option <?php echo $this->input['format'] == 'na' ? 'selected' : ''?> value="na"> non-défini </option>
                                    <option <?php echo $this->input['format'] == 'clavier' ? 'selected' : ''?> value="clavier">écran + clavier</option>
                                    <option <?php echo $this->input['format'] == 'tactile' ? 'selected' : ''?> value="tactile">écan tactile</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--FORMAT-->

                <!--OPTION-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12  col-xs-12">
                            <?php if($this->input['option'] <> 'na' && $this->input['option'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> options</b>
                                &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['emb_opt'] ?>"

                                > </i>
                            <?php else: ?>
                                <b>options</b>
                                                                                              &nbsp; &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<?php echo $this->bulle['emb_opt'] ?>"

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['grand_froid']) ? 'checked' : ''?>
                                            class="checknoshadow"
                                            type="checkbox"
                                            name="option[]"
                                            value="grand_froid">
                                    grand froid
                                </label>
                            </div>

                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['clavier_dur']) ? 'checked' : ''?>
                                            class="checknoshadow"
                                            type="checkbox"
                                            name="option[]"
                                            value="clavier_dur">
                                    clavier durci
                                </label>
                            </div>
                        </div>

                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['option']['douchette']) ? 'checked' : ''?>
                                            class="checknoshadow"
                                            type="checkbox"
                                            name="option[]"
                                            value="douchette"
                                            id="scannerembarque"
                                    >
                                    douchette
                                </label>
                            </div>
                        </div>

                    </div>
                </div>
                <!--OPTION-->

            </div>
        </div>
    </div>

    <div class="row ">

        <!--SYSTEM OS  -->
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
            <div class="row">
                <div class="col-xs-12 col-lg-12">
                    <?php if ($this->input['os'] <> 'na' && $this->input['os'] <> null): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            système </b> &nbsp;&nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="<?php echo $this->bulle['emb_os'] ?>"
                        > </i>
                    <?php else: ?>
                        <b>système</b>    &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="<?php echo $this->bulle['emb_os'] ?>"
                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row ">
                <div class="col-lg-12">
                    <div class="select">
                        <?php if ($this->input['os'] <> 'na' && $this->input['os'] <> null): ?>
                            <select class="active"  name="os" >
                        <?php else: ?>
                            <select  name="os" >
                        <?php endif ?>
                            <option  value="na" <?php echo $this->input['os'] == 'na' ? 'selected' : ''?> >non-défini</option>
                            <option  value="wince" <?php echo $this->input['os'] == 'wince' ? 'selected' : ''?> >windows ce</option>
                            <option  value="win_embeded_std" <?php echo $this->input['os'] == 'win_embeded_std' ? 'selected' : ''?> >Windows embeded standard</option>
                            <option  value="win_embeded_compact" <?php echo $this->input['os'] == 'win_embeded_compact' ? 'selected' : ''?> >Windows embeded compact</option>
                            <option  value="winmobile" <?php echo $this->input['os'] == 'winmobile' ? 'selected' : ''?> >Windows mobile</option>
                            <option  value="win_7" <?php echo $this->input['os'] == 'win_7' ? 'selected' : ''?> >Windows 7</option>
                            <option  value="win_10" <?php echo $this->input['os'] == 'win_10' ? 'selected' : ''?> >Windows 10</option>
                            <option  value="win_xp_pro" <?php echo $this->input['os'] == 'win_xp_pro' ? 'selected' : ''?> >Windows xp pro</option>
                            <option  value="win_xp_embeded" <?php echo $this->input['os'] == 'win_xp_embeded' ? 'selected' : ''?> >Windows xp embeded</option>
                            <option  value="android" <?php echo $this->input['os'] == 'android' ? "selected" : ''?> >Android</option>
                        </select>
                        <div class="select_arrow">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--SYSTEM OS  -->

        <!--INTERFACE  -->
        <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12 ">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                        <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i>  interface de communication </b>
                        &nbsp; &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="<?php echo $this->bulle['emb_com'] ?>"

                        > </i>
                    <?php else: ?>
                        <b>interface de communication</b>
                                                                                       &nbsp; &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="<?php echo $this->bulle['emb_com'] ?>"

                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row ">

                <div class="col-lg-4 col-md-3 col-sm-4 col-xs-12">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['usb']) ? 'checked' : ''?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="interface[]"
                                    value="usb">
                            usb
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['eth']) ? 'checked' : ''?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="interface[]"
                                    value="eth">
                            réseau
                        </label>
                    </div>
                </div>

                <div class="col-lg-4 col-md-3 col-sm-4 col-xs-12">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['wifi']) ? 'checked' : ''?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="interface[]"
                                    value="wifi">
                            wifi
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['serie']) ? 'checked' : ''?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="interface[]"
                                    value="serie">
                            série
                        </label>
                    </div>
                </div>

                <div class="col-lg-4 col-md-3 col-sm-4 col-xs-12">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['narrow']) ? 'checked' : ''?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="interface[]"
                                    value="narrow">
                            narrowband
                        </label>
                    </div>
                </div>


            </div>
        </div>
        <!--INTERFACE -->
    </div>


    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->
</form>