<form action="/filtre/apply" method="post"
      class="wrapper_form-filtre"
>
    <div class="row" style="padding-bottom: 10px;">
        <div class="col-lg-6 col-md-6 col-sm-12 h2 ">
            <b>Imprimante - MATRICIELLE</b>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 h2">
            <?php include('aide_imprimante_matricielle.phtml') ?>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <?php
            //var_dump($this->search) ;
            //var_dump($this->input) ;
            ?>
        </div>
    </div>

    <div class="row ">

        <!--MARQUE-->
        <div class="col-lg-4 col-sm-12 col-xs-12 ">
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Marque</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px "> </i> Marque
                                                                                       &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>

                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <select class="form-control" name="marque">
                        <option <?php echo $this->input['marque'] == 'na' ? 'selected' : '' ?> value="na">N.R</option>
                        <option <?php echo $this->input['marque'] == 'm_lexmark' ? 'selected' : '' ?> value="m_lexmark"> Lexmark </option>
                        <option <?php echo $this->input['marque'] == 'm_ibm' ? 'selected' : '' ?> value="m_ibm"> IBM </option>
                        <option <?php echo $this->input['marque'] == 'm_epson' ? 'selected' : '' ?> value="m_epson"> Epson </option>
                        <option <?php echo $this->input['marque'] == 'm_oki' ? 'selected' : '' ?> value="m_oki"> Oki </option>
                        <option <?php echo $this->input['marque'] == 'all' ? 'selected' : '' ?> value="all">Toutes marques </option>
                    </select>
                </div>
            </div>
        </div>
        <!-- FIN MARQUE-->

        <!--FORMAT -->
        <div class="col-lg-4 col-sm-6 col-xs-12 ">
            <div class="row">
                <div class="col-xs-12 col-lg-12">
                    <?php if ($this->input['format'] <> 'na' && $this->input['format'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Format </b> &nbsp;&nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Format    &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>

                    <?php endif ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <select class="form-control" name="format">
                        <option value="na" <?php echo $this->input['format'] == 'na' ? 'selected' : '' ?> >N.R</option>
                        <option value="c_132" <?php echo $this->input['format'] == 'c_132' ? 'selected' : '' ?> > 132 colonnes</option>
                        <option value="c_80" <?php echo $this->input['format'] == 'c_80' ? "selected" : '' ?> >80 colonnes </option>
                    </select>
                </div>
            </div>
        </div>
        <!--FIN FORMAT-->

        <!--GAMME-->
        <div class="col-lg-4 col-sm-6 col-xs-12">
            <div class="row">
                <div class="col-lg-12 visible-md visible-lg visible-sm">
                    <?php if ($this->input['gamme'] <> 'na' && $this->input['gamme'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Gamme</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Gamme &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
                <div class="col-lg-12 visible-xs">
                    <?php if ($this->input['gamme'] <> 'na' && $this->input['gamme'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Gamme</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Gamme
                                                                                      &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12">
                    <select class="form-control" name="gamme">
                        <option <?php echo $this->input['gamme'] == 'na' ? 'selected' : '' ?> value="na">N.R</option>
                        <option <?php echo $this->input['gamme'] == 'bureau' ? 'selected' : '' ?> value="bureau">Bureau</option>
                        <option <?php echo $this->input['gamme'] == 'indu' ? 'selected' : '' ?> value="indu">Industrielle </option>
                    </select>
                </div>
            </div>
        </div>
        <!--GAMME-->



    </div>

    <br>
    <div class="row">

        <!--UTILISATION-->
        <div class="col-lg-4 col-sm-6 col-xs-12">
            <div class="row">
                <div class="col-lg-12 visible-md visible-lg visible-sm">
                    <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Utilisation</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Utilisation &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
                <div class="col-lg-12 visible-xs">
                    <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Utilisation</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Utilisation
                                                                                      &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12">
                    <select class="form-control" name="use">
                        <option <?php echo $this->input['use'] == 'na' ? 'selected' : '' ?> value="na">N.R</option>
                        <option <?php echo $this->input['use'] == 'ligne' ? 'selected' : '' ?> value="ligne">Ligne</option>
                        <option <?php echo $this->input['use'] == 'aiguille' ? 'selected' : '' ?> value="aiguille">Aiguille </option>
                    </select>
                </div>
            </div>
        </div>
        <!--UTILISATION-->

        <!--INTERFACE-->
        <div style="padding-bottom: 20px" class="col-lg-8 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Options & Interface de connection</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i>  Options & Interfaces de connection   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row">

                <!--RECTO VERSO-->
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['feuille']) ? 'checked' : '' ?>
                                    type="checkbox" name="interfacep[]" value="feuille">
                            Feuille à feuille
                        </label>
                    </div>
                </div>

                <!--RESEAU / ETH -->
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['eth']) ? 'checked' : '' ?>
                                    type="checkbox" name="interfacep[]" value="eth">
                            Réseau
                        </label>
                    </div>
                </div>

                <!--SERIE-->
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['serie']) ? 'checked' : '' ?>
                                    type="checkbox" name="interfacep[]" value="serie">
                            Serie
                        </label>
                    </div>
                </div>

                <!--PARRALLELE-->
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['parra']) ? 'checked' : '' ?>
                                    type="checkbox" name="interfacep[]" value="parra">
                            Parralléle
                        </label>
                    </div>
                </div>



            </div>

        </div>
        <!--UTILISATION-->
    </div>
    <br>


    <!--BOUTTON DE VALIDATION-->
    <div class="row" style="padding-top: 10px">
        <div class="col-lg-8 col-sm-8 col-xs-8">
            <input type="submit" class="btn btn-euro-blue " value="Filtrer">
        </div>

        <div class="col-lg-4 col-sm-4 col-xs-4">
            <a href="filtre/delete" class="btn btn-euro-pink"
            >Reset</a>
        </div>
    </div>
    <!--BOUTTON DE VALIDATION-->
</form>