<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>
    <div class="row " >
        <div class="col-lg-12 ">

            <?php
            $configurator =
                [
                    'icone' => 'fa-print',
                    'title' => 'Imprimantes etiquettes - PORTABLE',
                    'etape' => 'etape-2.phtml',
                    'photo' => '/upload/images/geo/ql420.jpg'
                ]
            ?>
            <?php include('configurator_title.phtml') ?>
        </div>
    </div>

    <div class="row bgw" style="padding-top:10px;">
        <div class="col-lg-12 ">
            <div class="form-section row wrapper-content-configurator ">

                <!--MARQUES-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    marque</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>marque</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="marque" onchange='this.form.submit();'>
                                    <option <?php echo $this->input['marque'] == 'na' ? 'selected' : '' ?> value="na">
                                        non-défini
                                    </option>
                                    <option <?php echo $this->input['marque'] == 'm_zebra' ? 'selected' : '' ?>
                                            value="m_zebra"> Zebra
                                    </option>
                                    <option <?php echo $this->input['marque'] == 'm_intermec' ? 'selected' : '' ?>
                                            value="m_intermec"> Intermec
                                    </option>
                                    <!--<option --><?php //echo $this->input['marque'] == 'm_datamax' ? 'selected' : '' ?>
                                    <!--        value="m_datamax"> Datamax-->
                                    <!--</option>-->
                                    <option <?php echo $this->input['marque'] == 'm_toshiba' ? 'selected' : '' ?>
                                            value="m_toshiba"> Toshiba - Tec
                                    </option>
                                    <option <?php echo $this->input['marque'] == 'm_honeywell' ? 'selected' : '' ?>
                                            value="m_honeywell"> Honeywell
                                    </option>
                                    <option <?php echo $this->input['marque'] == 'all' ? 'selected' : '' ?> value="all">
                                        toutes marques
                                    </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--MARQUES-->

                <!--UTILISATION-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 ">
                            <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    utilisation</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>utilisation</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>

                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <select name="use" onchange='this.form.submit();'>
                                    <option <?php echo $this->input['use'] == 'na' ? 'selected' : '' ?> value="na">
                                        non-défini
                                    </option>
                                    <option <?php echo $this->input['use'] == 'ticket' ? 'selected' : '' ?>
                                            value="ticket">ticket
                                    </option>
                                    <option <?php echo $this->input['use'] == 'etiquette' ? 'selected' : '' ?>
                                            value="etiquette">etiquette
                                    </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--UTILISATION-->

                <!--LARGEUR IMPRESSION -->
                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <?php if ($this->input['width'] <> 'na' && $this->input['width'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    largeur impression</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>largeur impression</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <div class="select">
                                <select name="width" onchange='this.form.submit();'>
                                    <option <?php echo $this->input['width'] == 'na' ? 'selected' : '' ?> value="na">
                                        non-défini
                                    </option>
                                    <option <?php echo $this->input['width'] == '2' ? 'selected' : '' ?> value="2">2"
                                        (56mm)
                                    </option>
                                    <option <?php echo $this->input['width'] == '3' ? 'selected' : '' ?> value="3">3"
                                        (76mm)
                                    </option>
                                    <option <?php echo $this->input['width'] == '4' ? 'selected' : '' ?> value="4">4"
                                        (116mm)
                                    </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!--LARGEUR IMPRESSION -->
            </div>
        </div>
    </div>

    <div class="form-section row bgw">

        <!--OPTION-->
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if ($this->input['opt'] <> 'na' && $this->input['opt'] <> null): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            options</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <b>options</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row ">
                <div class="col-lg-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['opt']['linerless']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    onclick='this.form.submit();'
                                    type="checkbox" name="optp[]" value="linerless">
                            linerless
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['opt']['magnetique']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    onclick='this.form.submit();'
                                    type="checkbox"
                                    name="optp[]"
                                    value="magnetique">

                            Lecteur de carte
                        </label>
                    </div>

                </div>
                <div class="col-lg-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['opt']['extbatterie']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    onclick='this.form.submit();'
                                    type="checkbox"
                                    name="optp[]"
                                    value="extbatterie">
                            ext-batterie
                        </label>
                    </div>

                </div>
            </div>
        </div>
        <!--OPTION-->

        <!--CONNECTION-->
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            interface de communication</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <b>interface de communication</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row ">
                <div class="col-lg-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['usb']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    onclick='this.form.submit();'
                                    name="interfacep[]"
                                    value="usb">
                            usb
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['wifi']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="wifi">
                            wifi
                        </label>
                    </div>

                </div>
                <div class="col-lg-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['bluetooh']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="bluetooh">
                            bluetooth
                        </label>
                    </div>

                </div>
            </div>
        </div>
        <!--CONNECTION-->

        <!--CONSO ET SOFTWARE-->
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if (($this->input['conso'] <> 'na' && $this->input['conso'] <> null) || $this->input['dimension'] <> ''): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            consommables et soft</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <b>consommables & soft</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row ">
                <div class="col-lg-12 ">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['conso']['ruban']) ? "checked" : ''; ?>
                                    type="checkbox"
                                    onclick='this.form.submit();'
                                    class="checknoshadow"
                                    name="conso[]"
                                    value="ruban">
                            ruban
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['conso']['software']) ? "checked" : ''; ?>
                                    type="checkbox"
                                    onclick='this.form.submit();'
                                    class="checknoshadow"
                                    name="conso[]"
                                    value="software">
                            logiciel d'édition étiquettes
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['conso']['printhead']) ? "checked" : ''; ?>
                                    type="checkbox"
                                    class="checknoshadow"
                                    onclick='this.form.submit();'
                                    name="conso[]"
                                    value="printhead">
                            tête d'impression supplémentaire
                        </label>
                    </div>
                </div>

            </div>
        </div>
        <!--CONSO ET SOFTWARE-->
    </div>



    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->
</form>