<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>

    <div class="row " >
        <div class="col-lg-12 ">
            <div class="row wrapper-configurator-section ">
                <div class="col-md-10 text-left configurator">
                    <div class="configurator-title">
                                    <span class="fa-stack fa-lg" style="font-size: 2em">
                                        <i class="fa fa-circle fa-stack-2x " style="font-size: 2em ; color:white;"></i>
                                        <i class="fa fa-print fa-stack-1x " ></i>
                                    </span>
                        Imprimantes - LASER
                        <br>
                    </div>
                </div>
                <div class="col-md-2 configurator-img" style="background-color: #004FAE;">
                    <div class="configurator-title right  pull-right">
                        <img style=" width 82px; height: 82px ; border-radius: 82px ; " src="<?php echo PROJECTS.'/upload/images/geo/pf4i.jpg' ?>" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>

    <div class="row " style="padding-top:10px;background-color: white;">
        <div class="col-lg-12 ">

            <div class="form-section row wrapper-content-configurator ">

                <!--MARQUE-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    marques</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                marques
                                                                                               &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="marque">
                                    <option <?php echo $this->input['marque'] == 'na' ? 'selected' : '' ?> value="na">Non-défini</option>
                                    <option <?php echo $this->input['marque'] == 'm_hp' ? 'selected' : '' ?> value="m_hp"> HP </option>
                                    <option <?php echo $this->input['marque'] == 'm_lexmark' ? 'selected' : '' ?> value="m_lexmark"> Lexmark </option>
                                    <option <?php echo $this->input['marque'] == 'all' ? 'selected' : '' ?> value="all">Toutes marques </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--FORMAT-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 visible-md visible-lg visible-sm">
                            <?php if ($this->input['format'] <> 'na' && $this->input['format'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    format </b> &nbsp;&nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                format    &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>

                            <?php endif ?>
                        </div>

                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <select name="format">
                                    <option value="na" <?php echo $this->input['format'] == 'na' ? 'selected' : '' ?> >Non-défini</option>
                                    <option value="a4" <?php echo $this->input['format'] == 'a4' ? 'selected' : '' ?> > A4</option>
                                    <option value="a3" <?php echo $this->input['format'] == 'a3' ? "selected" : '' ?> >A3 </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--GAMME-->
                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <?php if ($this->input['gamme'] <> 'na' && $this->input['gamme'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    gamme</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                gamme
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>

                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <div class="select">
                                <select name="gamme">
                                    <option <?php echo $this->input['gamme'] == 'na' ? 'selected' : '' ?> value="na">Non-défini</option>
                                    <option <?php echo $this->input['gamme'] == 'groupe_petit' ? 'selected' : '' ?> value="groupe_petit">Petit groupe de travail </option>
                                    <option <?php echo $this->input['gamme'] == 'droupe_dep' ? 'selected' : '' ?> value="droupe_dep">Groupe departemental </option>
                                </select>
                                <div class="select_arrow"> </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </div>


    <div class="form-section row">

        <!--UTILISATION-->
        <div class="col-lg-4 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12 visible-md visible-lg visible-sm">
                    <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            utilisation</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        utilisation &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>

            </div>
            <div class="row ">
                <div class="col-lg-12 col-sm-12" >
                    <div class="select">
                        <select class="" name="use">
                            <option <?php echo $this->input['use'] == 'na' ? 'selected' : '' ?> value="na">Non-défini
                            </option>
                            <option <?php echo $this->input['use'] == 'mono' ? 'selected' : '' ?> value="mono">
                                Monochrome
                            </option>
                            <option <?php echo $this->input['use'] == 'couleur' ? 'selected' : '' ?> value="couleur">
                                Couleur
                            </option>
                        </select>
                        <div class="select_arrow"></div>
                    </div>

                </div>
            </div>
        </div>

        <!--VIEWPORT-->
        <div class="hidden-lg form-section-sm">&nbsp;</div>

        <!--INTERFACE-->
        <div style="padding-bottom: 7px" class="col-lg-8 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            options & interface de connection</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        options & interface de connection   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4 ">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['rectov']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="rectov">
                            Recto / Verso
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['eth']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="interfacep[]" value="eth">
                            Réseau
                        </label>
                    </div>
                </div>
                <div class="col-lg-4 ">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['wifi']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="interfacep[]" value="wifi">
                            Wifi
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['parra']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="interfacep[]" value="parra">
                            Parralléle
                        </label>
                    </div>

                </div>
                <div class="col-lg-4 ">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['serie']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="interfacep[]" value="serie">
                            Serie
                        </label>
                    </div>
                </div>
            </div>

        </div>

    </div>


    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->
</form>