<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>

    <div class="row form-section">
        <div class="col-lg-12">
            <?php
            //var_dump($this->search) ;
            //var_dump($this->input) ;
            ?>
        </div>
    </div>


    <div class="row " >
        <div class="col-lg-12 ">
            <?php
            $configurator =
                [
                    'icone' => 'fa-print',
                    'title' => 'Imprimantes - MATRICIELLE',
                    'etape' => 'etape-2.phtml',
                    'photo' => '/upload/images/geo/matricielle.jpg'
                ]
            ?>
            <?php include('configurator_title.phtml') ?>
        </div>
    </div>

    <div class="row " style="padding-top:10px;background-color: white;">
        <div class="col-lg-12 ">

            <div class="form-section row wrapper-content-configurator ">

                <!--MARQUE-->
                <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    marque</b>
                                &nbsp;
                                <?php
                                $picture = '/upload/images/geo/generique.jpg' ;
                                $url = PROJECTS.$picture
                                ?>
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="
                                    <img
                                        style=' width 82px; height: 82px ; border-radius: 82px ; '
                                        src='<?php echo $url ?>' alt=''
                                    >
                                    <br>
                                    <span style='text-aligne:left;'>
                                    <b>La</b> <u>gamme</u> definit l'environement et le volume d'impression <u>xxxxxxxxxx xxxxxxxxxxx </u>
                                    </span>


                                    "

                                > </i>
                            <?php else: ?>
                                <b>marque</b>
                                                                                    &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="<i class='fa fa-home'> </i> <b>La</b> <u>gamme</u> definit l'environement et le volume d'impression <br><br> <b><u>xxxxxxxxxx xxxxxxxxxxx </u> <br><br><b>"
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="marque"  onchange='this.form.submit();'>
                                    <option <?php echo $this->input['marque'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['marque'] == 'm_lexmark' ? 'selected' : '' ?> value="m_lexmark"> Lexmark </option>
                                    <option <?php echo $this->input['marque'] == 'm_ibm' ? 'selected' : '' ?> value="m_ibm"> IBM </option>
                                    <option <?php echo $this->input['marque'] == 'm_epson' ? 'selected' : '' ?> value="m_epson"> Epson </option>
                                    <option <?php echo $this->input['marque'] == 'm_oki' ? 'selected' : '' ?> value="m_oki"> Oki </option>
                                    <option <?php echo $this->input['marque'] == 'all' ? 'selected' : '' ?> value="all">toutes marques </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--FORMAT-->
                <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 ">
                            <?php if ($this->input['format'] <> 'na' && $this->input['format'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    format </b> &nbsp;&nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>format</b>    &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>

                            <?php endif ?>
                        </div>

                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <select name="format" onchange='this.form.submit();'>
                                    <option value="na" <?php echo $this->input['format'] == 'na' ? 'selected' : '' ?> >non-défini</option>
                                    <option value="c_132" <?php echo $this->input['format'] == 'c_132' ? 'selected' : '' ?> > 132 colonnes</option>
                                    <option value="c_80" <?php echo $this->input['format'] == 'c_80' ? "selected" : '' ?> >80 colonnes </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--GAMME-->
                <div class="col-lg-4 col-sm-12 col-xs-12 ">
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <?php if ($this->input['gamme'] <> 'na' && $this->input['gamme'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    utilisation</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>utilisation</b> &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <div class="select">
                                <select name="gamme" onchange='this.form.submit();'>
                                    <option <?php echo $this->input['gamme'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['gamme'] == 'bureau' ? 'selected' : '' ?> value="bureau">bureau</option>
                                    <option <?php echo $this->input['gamme'] == 'indu' ? 'selected' : '' ?> value="indu">industrielle </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>


    <div class="row form-section" style="background-color: white;">

        <!--UTILISATION-->
        <div class="col-lg-4 col-md-12 col-sm-6 col-xs-12 hidden">
            <div class="row">
                <div class="col-lg-12 ">
                    <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            utilisation</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <b>utilisation</b> &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>

            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12" style="padding-top: 8px">
                    <div class="select">
                        <select class="" name="use" onchange='this.form.submit();'>
                            <option <?php echo $this->input['use'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                            <option <?php echo $this->input['use'] == 'ligne' ? 'selected' : '' ?> value="ligne">ligne</option>
                            <option <?php echo $this->input['use'] == 'aiguille' ? 'selected' : '' ?> value="aiguille">aiguille </option>
                        </select>
                        <div class="select_arrow"> </div>
                    </div>

                </div>
            </div>
        </div>
        <!--UTILISATION-->

        <!--INTERFACE-->
        <div  class="col-lg-8 col-sm-6 col-xs-12">
            <div class="row">
                <div class="col-lg-12  col-sm-12 col-xs-12">
                    <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            options & interface de communication</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <b>options & interface de communication</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4 col-sm-12">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['eth']) ? 'checked' : '' ?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="eth">
                            réseau
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['serie']) ? 'checked' : '' ?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="serie">
                            série
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['parra']) ? 'checked' : '' ?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="parra">
                            parallèle
                        </label>
                    </div>
                </div>

                <div class="col-lg-4 ">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['usb']) ? 'checked' : '' ?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="usb">
                            usb
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['twinax']) ? 'checked' : '' ?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="twinax">
                            twinax
                        </label>
                    </div>


                </div>
            </div>
        </div>
        <!--UTILISATION-->
    </div>

    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->
</form>