<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>

    <div class="row">
        <?php
        //var_dump($this->input);
        //var_dump($this->session);
        //var_dump($this->search);
        ?>
    </div>
    <div class="row" style="padding-bottom: 10px;">
        <div class="col-lg-10 col-md-10 col-sm-12 h2 ">
            <b>Poste de travail - CLIENT LEGER</b>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-12 h2">
            <?php include('aide_poste_client.phtml') ?>
        </div>

    </div>

    <div class="row form-section">
        <!--SYSTEME  -->
        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <div class="row ">
                <div class="col-lg-12">
                    <?php if($this->input['os'] <> 'na' && $this->input['os'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> système</b>
                        &nbsp; &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> système
                                                                                      &nbsp; &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row form-section">
                <div class="col-lg-12" style="padding-top: 8px">
                    <select class="form-control" name="os">
                        <option  value="na" <?php echo $this->input['os'] == 'na' ? 'selected' : ''?> >non-défini</option>
                        <option  value="win" <?php echo $this->input['os'] == 'win' ? 'selected' : ''?> >windows</option>
                        <option  value="linux" <?php echo $this->input['os'] == 'linux' ? 'selected' : ''?> >linux</option>
                        <option  value="propri" <?php echo $this->input['os'] == 'propri' ? 'selected' : ''?> >propriétaire</option>
                    </select>
                </div>
            </div>
        </div>
        <!--SYSTEME  -->

        <!--ECRAN-->
        <div class="col-lg-3 col-sm-6 col-xs-12">
            <div class="row">
                <div class="col-lg-12">
                    <?php if($this->input['ecran'] <> 'nr' && $this->input['ecran'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> écran</b>
                        &nbsp; &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> écran
                                                                                      &nbsp; &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row form-section">
                <div class="col-lg-12" style="padding-top: 8px">
                    <select class="form-control" name="ecran">
                        <option <?php echo $this->input['ecran'] == 'nr' ? 'selected' : ''?> value="nr"> non-défini </option>
                        <option <?php echo $this->input['ecran'] == '17p' ? 'selected' : ''?> value="17p">17" 4/3</option>
                        <option <?php echo $this->input['ecran'] == '19p_4' ? 'selected' : ''?> value="19p_4">19" 4/3</option>
                        <option <?php echo $this->input['ecran'] == '19p_16' ? 'selected' : ''?> value="19p_16">19" 16/9</option>
                        <option <?php echo $this->input['ecran'] == '22p' ? 'selected' : ''?> value="22p">22" 16/9</option>
                        <option <?php echo $this->input['ecran'] == '24p' ? 'selected' : ''?> value="24p">24" 16/9</option>
                    </select>
                </div>
            </div>
        </div>
        <!--ECRAN-->

        <!--OPTION  -->
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 ">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if($this->input['option'] <> 'na' && $this->input['option'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> options</b>
                        &nbsp; &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> options
                                                                                      &nbsp; &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row ">

                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['option']['wifi']) ? 'checked' : ''?>
                                class="checknoshadow"
                                type="checkbox"
                                name="option[]"
                                value="wifi">
                            wifi
                        </label>
                    </div>
                </div>

                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['option']['dual_display']) ? 'checked' : ''?>
                                class="checknoshadow"
                                type="checkbox"
                                name="option[]"
                                value="dual_display">
                            double affichage
                        </label>
                    </div>
                </div>


            </div>
        </div>
        <!--OPTION -->
    </div>

    <div class="row ">

        <!--MEMOIRE RAM -->
        <div class="col-lg-5 col-md-12 col-sm-12 col-xs-12 ">
            <div class="row">
                <div class="col-lg-12">
                    <?php if($this->input['ram'] <> 'na' && $this->input['ram'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> mémoire RAM</b>
                        &nbsp; &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> mémoire RAM
                                                                                      &nbsp; &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row form-section">
                <div class="col-lg-12" >
                    <select class="form-control" name="ram">
                        <option  value="na" <?php echo $this->input['ram'] == 'na' ? 'selected' : ''?> >non-défini</option>
                        <option  value="2gb_ram" <?php echo $this->input['ram'] == '2gb_ram' ? 'selected' : ''?> >2 GB</option>
                        <option  value="4gb_ram" <?php echo $this->input['ram'] == '4gb_ram' ? 'selected' : ''?> >4 GB</option>
                        <option  value="8gb_ram" <?php echo $this->input['ram'] == '8gb_ram' ? 'selected' : ''?> >8 GB</option>
                        <option  value="16gb_ram" <?php echo $this->input['ram'] == '16gb_ram' ? 'selected' : ''?> >16 GB</option>

                    </select>
                </div>
            </div>
        </div>
        <!--MEMOIRE RAM -->

        <!--MEMOIR FLASH -->
        <div class="col-lg-5 col-md-12 col-sm-12 col-xs-12 ">
            <div class="row">
                <div class="col-lg-12">
                    <?php if($this->input['flash'] <> 'na' && $this->input['flash'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> mémoire flash</b>
                        &nbsp; &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> mémoire flash
                                                                                      &nbsp; &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row form-section">
                <div class="col-lg-12" >
                    <select class="form-control" name="flash">
                        <option  value="na" <?php echo $this->input['flash'] == 'na' ? 'selected' : ''?> >non-défini</option>
                        <option  value="2gb_flash" <?php echo $this->input['flash'] == '2gb_flash' ? 'selected' : ''?> >2 GB</option>
                        <option  value="4gb_flash" <?php echo $this->input['flash'] == '4gb_flash' ? 'selected' : ''?> >4 GB</option>
                        <option  value="8gb_flash" <?php echo $this->input['flash'] == '8gb_flash' ? 'selected' : ''?> >8 GB</option>
                        <option  value="16gb_flash" <?php echo $this->input['flash'] == '16gb_flash' ? 'selected' : ''?> >16 GB</option>
                        <option  value="32gb_flash" <?php echo $this->input['flash'] == '32gb_flash' ? 'selected' : ''?> >32 GB</option>
                        <option  value="64gb_flash" <?php echo $this->input['flash'] == '64gb_flash' ? 'selected' : ''?> >64 GB</option>
                    </select>
                </div>
            </div>
        </div>
        <!--MEMOIR FLASH -->
    </div>




    <!--BOUTTON DE VALIDATION-->
    <div class="row" style="padding-top: 10px">

        <div class="col-lg-8 col-sm-8 col-xs-8">
            <input type="submit" class="btn btn-euro-blue " value="Filtrer">
        </div>

        <div class="col-lg-4 col-sm-4 col-xs-4">
            <a href="filtre/delete" class="btn btn-euro-pink"
            >Reset</a>
        </div>
    </div>
    <!--BOUTTON DE VALIDATION-->
</form>