<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>

    <div class="row " >
        <div class="col-lg-12 ">

            <?php
            $configurator =
                [
                    'icone' => 'fa-print',
                    'title' => 'Imprimantes etiquettes - BADGEUSE',
                    'etape' => 'etape-2.phtml',
                    'photo' => '/upload/images/geo/pf4i.jpg'
                ]
            ?>
            <?php include('configurator_title.phtml') ?>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <?php
            //var_dump($this->search) ;
            //var_dump($this->input) ;
            ?>
        </div>
    </div>
    <div class="row " style="padding-top:10px;background-color: white;">

        <div class="col-lg-12 ">

            <div class="row form-section  wrapper-content-configurator ">

                <!--UTILISATION-->
                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    mode d'impression </b> &nbsp;&nbsp;

                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                              mode d'impression    &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>

                            <?php endif ?>
                        </div>
                    </div>

                    <div style="margin-top: 14px" class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select  name="use">
                                    <option value="na" <?php echo $this->input['use'] == 'na' ? 'selected' : '' ?> >
                                        non-défini
                                    </option>
                                    <option value="one_face" <?php echo $this->input['use'] == 'one_face' ? 'selected' : '' ?> >
                                        une face
                                    </option>
                                    <option value="dual_face" <?php echo $this->input['use'] == 'dual_face' ? "selected" : '' ?> >
                                        deux faces
                                    </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--FIN UTILISATION-->

                <!--MISE A NIVEAU VIEWPORT-->
                <div class="hidden-lg form-section-sm">&nbsp;</div>

                <!--OPTION ET ENCODAGE -->
                <div class="col-lg-7 col-md-12 col-sm-12 col-xs-12">
                    <div class="row">
                        <div class="col-lg-12  col-xs-12">
                            <?php if ($this->input['opt'] <> 'na' && $this->input['opt'] <> null): ?>

                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    options & encodage</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                options & encodage   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>


                    <div class="row ">
                        <div class="col-lg-6">
                            <div class="checkbox">
                                <label>
                                    magnétique
                                    <input id="noborder"
                                        <?php echo isset($this->input['opt']['magnetique']) ? 'checked' : '' ?>
                                           class="checknoshadow " type="checkbox" name="optd[]" value="magnetique">
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    puce
                                    <input id="noborder"
                                        <?php echo isset($this->input['opt']['puce']) ? 'checked' : '' ?>
                                           class="checknoshadow " type="checkbox" name="optd[]" value="puce">
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    nfc
                                    <input id="noborder"
                                        <?php echo isset($this->input['opt']['nfc']) ? 'checked' : '' ?>
                                           class="checknoshadow " type="checkbox" name="optd[]" value="nfc">
                                </label>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="checkbox">
                                <label>
                                    rfid
                                    <input id="noborder"
                                        <?php echo isset($this->input['opt']['rfid']) ? 'checked' : '' ?>
                                           class="checknoshadow " type="checkbox" name="optd[]" value="rfid">
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    sécurité & serrure
                                    <input id="noborder"
                                        <?php echo isset($this->input['opt']['serrure']) ? 'checked' : '' ?>
                                           class="checknoshadow " type="checkbox" name="optd[]" value="serrure">
                                </label>
                            </div>
                        </div>
                    </div>

                </div>

            </div>


            <div class="row form-section  wrapper-content-configurator">
                <div class="hidden-lg form-section-sm">&nbsp;</div>

                <!--INTERFACE-->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">

                    <div class="row">
                        <div class="col-lg-12  col-xs-12">
                            <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>

                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    interface de communication</b> &nbsp;&nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                interface de communication   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-6">
                            <div class="checkbox">
                                <label>
                                    wifi
                                    <input id="noborder"
                                        <?php echo isset($this->input['interface']['wifi']) ? 'checked' : '' ?>
                                           class="checknoshadow " type="checkbox" name="interfacep[]" value="wifi">
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    usb
                                    <input id="noborder"
                                        <?php echo isset($this->input['interface']['usb']) ? 'checked' : '' ?>
                                           class="checknoshadow " type="checkbox" name="interfacep[]" value="usb">
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    réseau
                                    <input id="noborder"
                                        <?php echo isset($this->input['interface']['eth']) ? 'checked' : '' ?>
                                           class="checknoshadow " type="checkbox" name="interfacep[]" value="eth">
                                </label>
                            </div>
                        </div>
                    </div>

                </div>
                <!--INTERFACE-->

                <!--MISE A NIVEAU VIEWPORT-->
                <div class="hidden-lg form-section-sm">&nbsp;</div>

                <!--CONSO ET SOFT-->
                <div class="col-lg-7 col-md-6 col-sm-12 col-xs-12 ">

                    <div class="row">
                        <div class="col-lg-12  col-xs-12">
                            <?php if (($this->input['conso'] <> 'na' && $this->input['conso'] <> null) || $this->input['dimension'] <> ''): ?>

                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    consommables et soft</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                consommables & soft   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-6">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['conso']['carte']) ? "checked" : ''; ?>
                                            type="checkbox"
                                            class="checknoshadow"
                                            name="conso[]"
                                            value="printhead">
                                    carte
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['conso']['ruban']) ? "checked" : ''; ?>
                                            type="checkbox"
                                            class="checknoshadow"
                                            name="conso[]"
                                            value="ruban">
                                    ruban
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['conso']['software']) ? "checked" : ''; ?>
                                            type="checkbox"
                                            class="checknoshadow"
                                            name="conso[]"
                                            value="software">
                                    logiciel d'édition de carte
                                </label>
                            </div>
                        </div>
                    </div>

                </div>
                <!--CONSO ET SOFT-->

            </div>

            <!--BOUTTON DE VALIDATION-->
           <?php include('section_validation.phtml') ?>
            <!--BOUTTON DE VALIDATION-->


        </div>

    </div>
</form>