<form action="/filtre/apply" method="post"
      class="wrapper_form-filtre"
>
    <div class="row" >
        <div class="col-lg-6 col-md-6 col-sm-12 h2 ">
            <b>Imprimante - LASER</b>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 h2">
            <?php include('aide_imprimante_laser.phtml') ?>
        </div>
    </div>
    <br>
    <div class="form-section row">
        <div class="col-lg-12">
            <?php
            //var_dump($this->search) ;
            //var_dump($this->input) ;
            ?>
        </div>
    </div>

    <div class="form-section row  borderr">
        <!--MARQUE-->
        <div class="col-lg-4 col-sm-12 col-xs-12 ">
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Marques</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px "> </i> Marques
                                                                                       &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>

                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <select class="form-control" name="marque">
                        <option <?php echo $this->input['marque'] == 'na' ? 'selected' : '' ?> value="na">Non-défini</option>
                        <option <?php echo $this->input['marque'] == 'm_hp' ? 'selected' : '' ?> value="m_hp"> HP </option>
                        <option <?php echo $this->input['marque'] == 'm_lexmark' ? 'selected' : '' ?> value="m_lexmark"> Lexmark </option>
                        <option <?php echo $this->input['marque'] == 'all' ? 'selected' : '' ?> value="all">Toutes marques </option>
                    </select>
                </div>
            </div>
        </div>
        <!-- FIN MARQUE-->

        <div class="hidden-lg form-section-sm">&nbsp;</div>

        <!--RESOLUTION -->
        <div class="col-lg-4 col-sm-6 col-xs-12">
            <div class="row">
                <div class="col-xs-12 col-lg-12">
                    <?php if ($this->input['format'] <> 'na' && $this->input['format'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Format </b> &nbsp;&nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Format    &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>

                    <?php endif ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <select class="form-control" name="format">
                        <option value="na" <?php echo $this->input['format'] == 'na' ? 'selected' : '' ?> >Non-défini</option>
                        <option value="a4" <?php echo $this->input['format'] == 'a4' ? 'selected' : '' ?> > A4</option>
                        <option value="a3" <?php echo $this->input['format'] == 'a3' ? "selected" : '' ?> >A3 </option>
                    </select>
                </div>
            </div>
        </div>
        <!--FIN RESOLUTION-->

        <!--GAMME-->
        <div class="col-lg-4 col-sm-6 col-xs-12">
            <div class="row">
                <div class="col-lg-12 visible-md visible-lg visible-sm">
                    <?php if ($this->input['gamme'] <> 'na' && $this->input['gamme'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Gamme</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Gamme &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
                <div class="col-lg-12 visible-xs">
                    <?php if ($this->input['gamme'] <> 'na' && $this->input['gamme'] <> null): ?>
                        <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Gamme</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Gamme
                                                                                      &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12">
                    <select class="form-control" name="gamme">
                        <option <?php echo $this->input['gamme'] == 'na' ? 'selected' : '' ?> value="na">Non-défini</option>
                        <option <?php echo $this->input['gamme'] == 'groupe_petit' ? 'selected' : '' ?> value="groupe_petit">Petit groupe de travail </option>
                        <option <?php echo $this->input['gamme'] == 'droupe_dep' ? 'selected' : '' ?> value="droupe_dep">Groupe departemental </option>
                    </select>
                </div>
            </div>
        </div>
        <!--GAMME-->



    </div>

    <div class="form-section row">
            <!--UTILISATION-->
            <div  class="col-lg-4 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-lg-12 visible-md visible-lg visible-sm" >
                        <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                            <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                Utilisation</b>   &nbsp;
                            <i class="fa fa-question-circle"
                               data-toggle="tooltip"
                               data-placement="right"
                               title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                            > </i>
                        <?php else: ?>
                            <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Utilisation &nbsp;
                            <i class="fa fa-question-circle"
                               data-toggle="tooltip"
                               data-placement="right"
                               title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                            > </i>
                        <?php endif ?>
                    </div>
                    <div class="col-lg-12 visible-xs">
                        <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                            <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                Utilisation</b>
                            &nbsp;
                            <i class="fa fa-question-circle"
                               data-toggle="tooltip"
                               data-placement="right"
                               title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                            > </i>
                        <?php else: ?>
                            <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Utilisation
                                                                                          &nbsp;
                            <i class="fa fa-question-circle"
                               data-toggle="tooltip"
                               data-placement="right"
                               title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                            > </i>
                        <?php endif ?>
                    </div>
                </div>
                <div class="row " >
                    <div class="col-lg-12 col-sm-12" style="padding-top: 8px">
                        <select class="form-control" name="use">
                            <option <?php echo $this->input['use'] == 'na' ? 'selected' : '' ?> value="na">Non-défini</option>
                            <option <?php echo $this->input['use'] == 'mono' ? 'selected' : '' ?> value="mono">Monochrome </option>
                            <option <?php echo $this->input['use'] == 'couleur' ? 'selected' : '' ?> value="couleur">Couleur </option>
                        </select>
                    </div>
                </div>
            </div>
            <!--UTILISATION-->
        <div class="hidden-lg form-section-sm">&nbsp;</div>

            <!--INTERFACE-->
            <div style="padding-bottom: 20px" class="col-lg-8 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-lg-12  col-xs-12">
                        <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                            <b style="color: mediumseagreen"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                Options & Interface de connection</b>   &nbsp;
                            <i class="fa fa-question-circle"
                               data-toggle="tooltip"
                               data-placement="right"
                               title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                            > </i>
                        <?php else: ?>
                            <i class="fa fa-angle-right" style="margin-right: 15px"> </i>  Options & Interface de connection   &nbsp;
                            <i class="fa fa-question-circle"
                               data-toggle="tooltip"
                               data-placement="right"
                               title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                            > </i>
                        <?php endif ?>
                    </div>
                </div>

                <div class="row">

                    <!--RECTO VERSO-->
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <div class="checkbox">
                            <label>
                                <input <?php echo isset($this->input['interface']['rectov']) ? 'checked' : '' ?>
                                        class="checknoshadow"
                                        type="checkbox"
                                        name="interfacep[]"
                                        value="rectov">

                                Recto / Verso
                            </label>
                        </div>
                    </div>

                    <!--RESEAU / ETH -->
                    <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                        <div class="checkbox">
                            <label>
                                <input <?php echo isset($this->input['interface']['eth']) ? 'checked' : '' ?>
                                        class="checknoshadow"
                                        type="checkbox" name="interfacep[]" value="eth">
                                Réseau
                            </label>
                        </div>
                    </div>

                    <!--SERIE-->
                    <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                        <div class="checkbox">
                            <label>
                                <input <?php echo isset($this->input['interface']['serie']) ? 'checked' : '' ?>
                                        class="checknoshadow"
                                        type="checkbox" name="interfacep[]" value="serie">
                                Serie
                            </label>
                        </div>
                    </div>

                    <!--WIFI-->
                    <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                        <div class="checkbox">
                            <label>
                                <input <?php echo isset($this->input['interface']['wifi']) ? 'checked' : '' ?>
                                        class="checknoshadow"
                                        type="checkbox" name="interfacep[]" value="wifi">
                                Wifi
                            </label>
                        </div>
                    </div>

                    <!--PARRALLELE-->
                    <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6">
                        <div class="checkbox">
                            <label>
                                <input <?php echo isset($this->input['interface']['parra']) ? 'checked' : '' ?>
                                        class="checknoshadow"
                                        type="checkbox" name="interfacep[]" value="parra">
                                Parralléle
                            </label>
                        </div>
                    </div>



                </div>

            </div>
            <!--UTILISATION-->
        </div>

    <!--BOUTTON DE VALIDATION-->
    <div class="row" style="padding-top: 10px">
        <div class="col-lg-8 col-sm-8 col-xs-8">
            <input type="submit" class="btn btn-euro-blue " value="Filtrer">
        </div>

        <div class="col-lg-4 col-sm-4 col-xs-4">
            <a href="filtre/delete" class="btn btn-euro-pink"
            >Reset</a>
        </div>
    </div>
    <!--BOUTTON DE VALIDATION-->
</form>