

<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>
    <!--TESTING INPUT -->
    <div class="row">
        <?php 
        //var_dump($this->session);
        //var_dump($this->input);
        ?>
    </div>
    <!--TESTING INPUT -->

    <div class="row " >
        <div class="col-lg-12 ">

            <?php
            $configurator =
                [
                    'icone' => 'fa-barcode',
                    'title' => 'Lecteurs code-barres - DOUCHETTES',
                    'etape' => 'etape-2.phtml',
                    'photo' => '/upload/images/geo/pm8300_min1.jpg'
                ]
            ?>
            <?php include('configurator_title.phtml') ?>
        </div>
    </div>




    <div class="row " style="padding-top:10px;background-color: white;">
        <div class="col-lg-12 ">

            <div class="form-section row wrapper-content-configurator ">
                <!--MARQUE-->
                <div class="col-lg-4 col-sm-6 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    marque</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>marque</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="marque" onchange='this.form.submit();'>
                                    <option <?php echo $this->input['marque'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['marque'] == 'm_zebra' ? 'selected' : '' ?> value="m_zebra"> Zebra </option>
                                    <option <?php echo $this->input['marque'] == 'm_motorola' ? 'selected' : '' ?> value="m_motorola"> Motorola </option>
                                    <option <?php echo $this->input['marque'] == 'm_symbol' ? 'selected' : '' ?> value="m_symbol">Symbol </option>
                                    <option <?php echo $this->input['marque'] == 'm_datalogic' ? 'selected' : '' ?> value="m_datalogic">Datalogic</option>
                                    <option <?php echo $this->input['marque'] == 'm_honeywell' ? 'selected' : '' ?> value="m_honeywell">Honeywell </option>
                                    <option <?php echo $this->input['marque'] == 'm_opticon' ? 'selected' : '' ?> value="m_opticon">Opticon </option>
                                    <option <?php echo $this->input['marque'] == 'all' ? 'selected' : '' ?> value="all">toutes marques </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--GAMME-->
                <div class="col-lg-4 col-sm-6 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 ">
                            <?php if ($this->input['gamme'] <> 'na' && $this->input['gamme'] <> null): ?>
                                <b class="blue_royal">
                                <i class="fa fa-check-circle" style="margin-right: 5px"> </i> gamme</b>
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>gamme</b> &nbsp;&nbsp;
                                <i class="fa fa-question-circle"
                                        data-toggle="tooltip"
                                        data-placement="right"
                                        title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>

                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <select name="gamme" onchange='this.form.submit();'>
                                    <option <?php echo $this->input['gamme'] == 'na' ? 'selected' : ''?> value="na">non-défini</option>
                                    <option <?php echo $this->input['gamme'] == 'bureau' ? 'selected' : ''?> value="bureau">bureau</option>
                                    <option <?php echo $this->input['gamme'] == 'i' ? 'selected' : ''?> value="i">industrielle</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--TYPE-->
                <div class="col-lg-4 col-sm-12 col-xs-12 ">
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <?php if($this->input['type'] <> 'nr' && $this->input['type'] <> null): ?>
                                <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> type</b>
                                &nbsp;&nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>type</b>
                                                                                              &nbsp;&nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>

                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <div class="select">
                                <select name="type" onchange='this.form.submit();'>
                                    <option  value="nr" <?php echo $this->input['type'] == 'nr' ? 'selected' : ''?> >non-défini</option>
                                    <option  value="filaire" <?php echo $this->input['type'] == 'filaire' ? 'selected' : ''?> >filaire</option>
                                    <option  value="nofilaire" <?php echo $this->input['type'] == 'nofilaire' ? 'selected' : ''?> >sans-fil</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>



    <div class="row  form-section bgw">

        <!--LASER-->
        <div class="col-lg-4 col-sm-12 col-xs-12 ">
            <div class="row">
                <div class="col-xs-12 col-lg-12">
                    <?php if($this->input['laser'] <> 'nr' && $this->input['laser'] <> null): ?>
                        <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> scanner</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <b>scanner</b>
                                                                                      &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row ">
                <div class="col-lg-12">
                    <div class="select">
                        <select name="laser" onchange='this.form.submit();'>
                            <option <?php echo $this->input['laser'] == 'nr' ? 'selected' : ''?> value="nr"> non-défini </option>
                            <option <?php echo $this->input['laser'] == '1std' ? 'selected' : ''?> value="1std">1d std</option>
                            <option <?php echo $this->input['laser'] == '1lg' ? 'selected' : ''?> value="1lg">1d long range</option>
                            <option <?php echo $this->input['laser'] == '1xlg' ? 'selected' : ''?> value="1xlg">1d extra longue range</option>
                            <option <?php echo $this->input['laser'] == '2std' ? 'selected' : ''?> value="2std">2d std</option>
                            <option <?php echo $this->input['laser'] == '2lg' ? 'selected' : ''?> value="2lg">2d long range</option>
                        </select>
                        <div class="select_arrow">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--INTERFACE DOUCHETTE-->
        <div class="col-lg-4  col-sm-6 col-xs-12 ">
            <div class="row">
                <div class="col-lg-12">
                    <?php if($this->input['interfaced'] <> 'nr' && $this->input['interfaced'] <> null): ?>
                        <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i>  interface de communication</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <b>interface de communication</b> &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>

            <div class="row">

                <div class="col-lg-12">
                    <div class="checkbox">
                        <label>
                            <input
                                <?php echo isset($this->input['interfaced']['bluetooh']) ? 'checked' : ''?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfaced[]"
                                    value="bluetooh">
                            bluetooh
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input
                                <?php echo isset($this->input['interfaced']['radio']) ? 'checked' : ''?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfaced[]"
                                    value="radio">
                            radio
                        </label>
                    </div>
                </div>

            </div>

        </div>

        <!--INTERFACE SOCLE-->
        <div class="col-lg-4  col-sm-6 col-xs-12 ">
            <div class="row">
                <div class="col-lg-12">
                    <?php if($this->input['interfaceb'] <> 'nr' && $this->input['interfaceb'] <> null): ?>
                        <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i>  interface de communication du socle</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <b>interface de communication du socle</b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-sm-6">
                    <div class="checkbox">
                        <label>
                            <input
                                <?php echo isset($this->input['interfaceb']['eth']) ? 'checked' : ''?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfaceb[]"
                                    value="eth">
                            réseau
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input
                                <?php echo isset($this->input['interfaceb']['usb']) ? 'checked' : ''?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfaceb[]"
                                    value="usb">
                           usb
                        </label>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <div class="checkbox">
                        <label>
                            <input
                                <?php echo isset($this->input['interfaceb']['serie']) ? 'checked' : ''?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfaceb[]"
                                    value="serie">
                            série
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input
                                <?php echo isset($this->input['interfaceb']['wedge']) ? 'checked' : ''?>
                                    class="checknoshadow" onclick='this.form.submit();'
                                    type="checkbox"
                                    name="interfaceb[]"
                                    value="wedge">
                            wedge
                        </label>
                    </div>
                </div>


            </div>
        </div>

    </div>

    <div class="row form-section bgw">
        <!--OPTIONS-->
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12 ">
                    <?php if($this->input['optiond'] <> 'nr' && $this->input['optiond'] <> null): ?>
                        <b class="blue_royal">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> options de la douchette </b>
                        &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        <b>options de la douchette</b> &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>

            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12" >
                    <div class="col-lg-4 col-md-3 col-sm-3 col-xs-4">
                        <div class="checkbox">
                            <label>
                                <input
                                    <?php echo isset($this->input['optiond']['ecran']) ? 'checked' : ''?>
                                        class="checknoshadow" onclick='this.form.submit();'
                                        type="checkbox"
                                        name="optiond[]"
                                        value="ecran">
                                Ecran
                            </label>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-3 col-sm-3 col-xs-4">
                        <div class="checkbox">
                            <label>
                                <input
                                    <?php echo isset($this->input['optiond']['clavier']) ? 'checked' : ''?>
                                        class="checknoshadow" onclick='this.form.submit();'
                                        type="checkbox"
                                        name="optiond[]"
                                        value="clavier">
                                clavier
                            </label>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-3 col-sm-3 col-xs-4">
                        <div class="checkbox">
                            <label>
                                <input
                                    <?php echo isset($this->input['optiond']['batch']) ? 'checked' : ''?>
                                        class="checknoshadow" onclick='this.form.submit();'
                                        type="checkbox"
                                        name="optiond[]"
                                        value="batch">
                                batch
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--OPTIONS-->

    </div>

    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->

</form>