<form action="/filtre/apply" method="post"
      class="wrapper_form-filtre"
>

    <div class="row ">
        <div class="col-lg-12 ">
            <div class="row wrapper-configurator-section ">
                <div class="col-md-10 text-left configurator">
                    <div class="configurator-title">
                                    <span class="fa-stack fa-lg" style="font-size: 2em">
                                        <i class="fa fa-circle fa-stack-2x " style="font-size: 2em ; color:white;"></i>
                                        <i class="fa fa-print fa-stack-1x "></i>
                                    </span>
                        Imprimantes etiquette - PORTABLE
                        <br>
                    </div>
                </div>
                <div class="col-md-2 configurator-img" style="background-color: #004FAE;">
                    <div class="configurator-title right  pull-right">
                        <img style=" width 82px; height: 82px ; border-radius: 82px ; "
                             src="<?php echo PROJECTS.'/upload/images/geo/ql420.jpg' ?>" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row " style="padding-top:10px;background-color: white;">
        <div class="col-lg-12 ">
            <div class="form-section row wrapper-content-configurator ">

                <!--MARQUES-->
                <div class="col-lg-4 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">
                            <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    marques</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                marques
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select">
                                <select name="marque">
                                    <option <?php echo $this->input['marque'] == 'na' ? 'selected' : '' ?> value="na">
                                        Non-défini
                                    </option>
                                    <option <?php echo $this->input['marque'] == 'm_zebra' ? 'selected' : '' ?>
                                            value="m_zebra"> Zebra
                                    </option>
                                    <option <?php echo $this->input['marque'] == 'm_intermec' ? 'selected' : '' ?>
                                            value="m_intermec"> Intermec
                                    </option>
                                    <option <?php echo $this->input['marque'] == 'm_datamax' ? 'selected' : '' ?>
                                            value="m_datamax"> Datamax
                                    </option>
                                    <option <?php echo $this->input['marque'] == 'm_toshiba' ? 'selected' : '' ?>
                                            value="m_toshiba"> Toshiba Tec
                                    </option>
                                    <option <?php echo $this->input['marque'] == 'm_honeywell' ? 'selected' : '' ?>
                                            value="m_honeywell"> Honeywell
                                    </option>
                                    <option <?php echo $this->input['marque'] == 'all' ? 'selected' : '' ?> value="all">
                                        Toutes marques
                                    </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--UTILISATION-->
                <div class="col-lg-4 col-sm-12 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 visible-md visible-lg visible-sm">
                            <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    utilisation</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                utilisation   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>

                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">
                                <select name="use">
                                    <option <?php echo $this->input['use'] == 'na' ? 'selected' : '' ?> value="na">
                                        Non-défini
                                    </option>
                                    <option <?php echo $this->input['use'] == 'ticket' ? 'selected' : '' ?>
                                            value="ticket">Ticket
                                    </option>
                                    <option <?php echo $this->input['use'] == 'etiquette' ? 'selected' : '' ?>
                                            value="etiquette">Etiquette
                                    </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--LARGEUR IMPRESSION -->
                <div class="col-lg-4 col-sm-12 col-xs-12 ">
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <?php if ($this->input['width'] <> 'na' && $this->input['width'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    largeur impression</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                largeur impression   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <div class="select">
                                <select name="width">
                                    <option <?php echo $this->input['width'] == 'na' ? 'selected' : '' ?> value="na">
                                        Non-défini
                                    </option>
                                    <option <?php echo $this->input['width'] == '2' ? 'selected' : '' ?> value="2">2"
                                        (50mm)
                                    </option>
                                    <option <?php echo $this->input['width'] == '3' ? 'selected' : '' ?> value="3">3"
                                        (76mm)
                                    </option>
                                    <option <?php echo $this->input['width'] == '4' ? 'selected' : '' ?> value="4">4"
                                        (116mm)
                                    </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>

    <div class="form-section row ">

        <!--OPTION-->
        <div class="col-lg-4 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if ($this->input['opt'] <> 'na' && $this->input['opt'] <> null): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            options</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        options   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row ">
                <div class="col-lg-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['opt']['linerless']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox" name="optp[]" value="linerless">
                            Linerless
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['opt']['magnetique']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="optp[]"
                                    value="magnetique">
                            Carte Magnetique
                        </label>
                    </div>

                </div>
                <div class="col-lg-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['opt']['nfc']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="optp[]"
                                    value="nfc">
                            Nfc
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['opt']['extbatterie']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="optp[]"
                                    value="extbatterie">
                            Ext-batterie
                        </label>
                    </div>

                </div>
            </div>
        </div>

        <!--CONNECTION-->
        <div class="col-lg-4 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            Interface de connection</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        Interface de connection   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>
            <div class="row ">
                <div class="col-lg-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['usb']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="usb">
                            Usb
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['wifi']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="wifi">
                            Wifi
                        </label>
                    </div>

                </div>
                <div class="col-lg-6">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['interface']['bluetooh']) ? 'checked' : '' ?>
                                    class="checknoshadow"
                                    type="checkbox"
                                    name="interfacep[]"
                                    value="bluetooh">
                            Bluetooh
                        </label>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <!--CONSO ET SOFTWARE-->
    <div class="row form-section">
        <div class="col-lg-12 col-sm-12 col-xs-12 ">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if (($this->input['conso'] <> 'na' && $this->input['conso'] <> null) || $this->input['dimension'] <> ''): ?>
                        <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                            consommable et soft</b>   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php else: ?>
                        consommable & soft   &nbsp;
                        <i class="fa fa-question-circle"
                           data-toggle="tooltip"
                           data-placement="right"
                           title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                        > </i>
                    <?php endif ?>
                </div>
            </div>


            <div class="row ">

                <div class="col-lg-8 " style="padding-top: 8px">
                    <textarea
                            name="dimension"
                            id="filter"
                            placeholder="Indiquer vos dimensions étiquettes en mm ."
                    ><?php if (isset($this->input['dimension']))echo $this->input['dimension'];?></textarea>
                </div>

                <div class="col-lg-4 ">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['conso']['ruban']) ? "checked" : ''; ?>
                                    type="checkbox"
                                    class="checknoshadow"
                                    name="conso[]"
                                    value="ruban">
                            ruban
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['conso']['software']) ? "checked" : ''; ?>
                                    type="checkbox"
                                    class="checknoshadow"
                                    name="conso[]"
                                    value="software">
                            logiciel d'édition étiquettes
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['conso']['printhead']) ? "checked" : ''; ?>
                                    type="checkbox"
                                    class="checknoshadow"
                                    name="conso[]"
                                    value="printhead">
                            tête d'impression supplémentaire
                        </label>
                    </div>
                </div>
            </div>


        </div>
    </div>

    <!--BOUTTON DE VALIDATION-->
    <?php include('section_validation.phtml') ?>
    <!--BOUTTON DE VALIDATION-->
</form>