<form action="/configurateur/apply" method="post"
      class="wrapper_form-filtre"
>
    <div class="row">
        <?php 
        //var_dump($this->input);

        ?>
    </div>

    <div class="row " >
        <div class="col-lg-12 ">

           <?php
            $configurator =
                [
                    'icone' => 'fa-print',
                    'title' => 'Imprimante etiquette - THERMIQUE',
                    'etape' => 'etape-2.phtml',
                    'photo' => '/upload/images/geo/pf4i.jpg'
                ]
            ?>
           <?php include('configurator_title.phtml') ?>
        </div>
    </div>
    <?php if($this->error !== null) : ?>
        <div class=" row" style="padding-top: 10px;background-color: white;">
            <div class="col-lg-12 col-md-10 col-sm-12  " >
                <p style="padding: 10px" class="alert-danger "><?php echo $this->error ?></p>
            </div>
        </div>
    <?php endif ?>

    <div class="row " style="padding-top:10px;background-color: white;">
        <div class="col-lg-12 ">

            <!--1ERE LIGNE-->
            <div class="form-section row wrapper-content-configurator ">

                <!--RESOLUTION-->
                <div class="col-lg-4 col-md-6 col-sm-4 col-xs-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-lg-12">

                            <?php if ($this->input['dpi'] <> 'na' && $this->input['dpi'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    résolution </b> &nbsp;&nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"

                                   title="La gamme definit <br> <u>l'environement</u> <br><br><br><br><br> et le volume  <br> d'impression <br> xxxxxxxxxx <br> xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>résolution</b> &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit <br> l'environement <br> et le volume  <br> d'impression <br> xxxxxxxxxx <br> xxxxxxxxxxx"
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-lg-12">
                            <div class="select"  >

                                <?php if ($this->input['dpi'] <> 'na' && $this->input['dpi'] <> null): ?>
                                <select class="active"  name="dpi" onchange='this.form.submit();'">
                                <?php else: ?>
                                <select  name="dpi" onchange='this.form.submit();'">
                                <?php endif ?>

                                    <option value="na" <?php echo $this->input['dpi'] == 'na' ? 'selected' : '' ?> >non-défini</option>
                                    <option value="200" <?php echo $this->input['dpi'] == '200' ? 'selected' : '' ?> >&nbsp;&nbsp;200 dpi </option>
                                    <option value="300" <?php echo $this->input['dpi'] == '300' ? 'selected' : '' ?> >&nbsp;&nbsp;300 dpi </option>
                                    <option value="600" <?php echo $this->input['dpi'] == '600' ? "selected" : '' ?> >&nbsp;&nbsp;600 dpi </option>
                                    <option value="1200" <?php echo $this->input['dpi'] == '1200' ? "selected" : '' ?> >1200 dpi </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--RESOLUTION-->

                <!--LARGEUR IMPRESSION-->
                <div class="col-lg-4 col-md-6 col-sm-4 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12 ">
                            <?php if ($this->input['width'] <> 'na' && $this->input['width'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    largeur max d'impression</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>largeur max d'impression</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>

                    </div>
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12">
                            <div class="select">

                                    <?php if ($this->input['width'] <> 'na' && $this->input['width'] <> null): ?>
                                        <select class="active"  name="width" onchange='this.form.submit();'">
                                    <?php else: ?>
                                        <select  name="width" onchange='this.form.submit();'">
                                    <?php endif ?>

                                    <option <?php echo $this->input['width'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['width'] == '4' ? 'selected' : '' ?> value="4">4" (116mm) </option>
                                    <option <?php echo $this->input['width'] == '6' ? 'selected' : '' ?> value="6">6" (168mm) </option>
                                    <option <?php echo $this->input['width'] == '8' ? 'selected' : '' ?> value="8">8" (203mm) </option>
                                    <option <?php echo $this->input['width'] == '2' ? 'selected' : '' ?> value="2">2" (56mm) </option>
                                    <option <?php echo $this->input['width'] == '3' ? 'selected' : '' ?> value="3">3" (76mm) </option>
                                    <option <?php echo $this->input['width'] == '5' ? 'selected' : '' ?> value="5">5" (127mm) </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--LARGEUR IMPRESSION-->

                <!--GAMME-->
                <div class="col-lg-4 col-md-12 col-sm-4 col-xs-12 ">
                    <div class="row ">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <?php if ($this->input['gamme'] <> 'na' && $this->input['gamme'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    gamme</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>gamme</b>
                                &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>

                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 col-sm-12 col-xs-12">
                            <div class="select">

                                    <?php if ($this->input['gamme'] <> 'na' && $this->input['gamme'] <> null): ?>
                                        <select class="active"  name="gamme" onchange='this.form.submit();'">
                                    <?php else: ?>
                                        <select  name="gamme" onchange='this.form.submit();'">
                                    <?php endif ?>

                                    <option <?php echo $this->input['gamme'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['gamme'] == 'bureau' ? 'selected' : '' ?> value="bureau"> bureau </option>
                                    <option <?php echo $this->input['gamme'] == 'si' ? 'selected' : '' ?> value="si"> semi-industrielle </option>
                                    <option <?php echo $this->input['gamme'] == 'i' ? 'selected' : '' ?> value="i">industrielle </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!--GAMME-->

            </div>
            <!--1ERE LIGNE-->

            <!--2EME LIGNE-->
            <div class=" row ">

                <!--MARQUES-->
                <div class="col-lg-4 col-md-6 col-sm-4 col-xs-12">
                    <div class="row">
                        <div class="col-lg-12">
                            <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    marque</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>marque</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="row form-section">
                        <div class="col-lg-12">

                            <div class="select">

                                    <?php if ($this->input['marque'] <> 'na' && $this->input['marque'] <> null): ?>
                                        <select class="active"  name="marque" onchange='this.form.submit();'">
                                    <?php else: ?>
                                        <select  name="marque" onchange='this.form.submit();'">
                                    <?php endif ?>


                                    <option <?php echo $this->input['marque'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['marque'] == 'm_zebra' ? 'selected' : '' ?> value="m_zebra"> Zebra </option>
                                    <option <?php echo $this->input['marque'] == 'm_datamax' ? 'selected' : '' ?> value="m_datamax"> Datamax </option>
                                    <option <?php echo $this->input['marque'] == 'm_intermec' ? 'selected' : '' ?> value="m_intermec">Intermec </option>
                                    <option <?php echo $this->input['marque'] == 'm_toshiba' ? 'selected' : '' ?> value="m_toshiba">Toshiba - Tec </option>
                                    <option <?php echo $this->input['marque'] == 'm_honeywell' ? 'selected' : '' ?> value="m_honeywell">Honeywell </option>
                                    <option <?php echo $this->input['marque'] == 'all' ? 'selected' : '' ?> value="all">toutes marques </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--MARQUES-->

                <!--UTILISATION-->
                <div class="col-lg-4 col-md-6 col-sm-4 col-xs-12">
                    <div class="row">
                        <div class="col-lg-12">
                            <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    utilisation</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>utilisation</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="row form-section">
                        <div class="col-lg-12">

                            <div class="select">

                                <?php if ($this->input['use'] <> 'na' && $this->input['use'] <> null): ?>
                                    <select class="active"  name="use" onchange='this.form.submit();'">
                                <?php else: ?>
                                    <select  name="use" onchange='this.form.submit();'">
                                <?php endif ?>



                                    <option <?php echo $this->input['use'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['use'] == 'tt' ? 'selected' : '' ?> value="tt">transfert thermique </option>
                                    <option <?php echo $this->input['use'] == 'dt' ? 'selected' : '' ?> value="dt">direct thermique </option>
                                    <option <?php echo $this->input['use'] == 'both' ? 'selected' : '' ?> value="both"> les deux </option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--UTILISATION-->

                <!--OPTION-->
                <div class="col-lg-4 col-md-12 col-sm-4 col-xs-12">
                    <div class="row">
                        <div class="col-lg-12">
                            <?php if ($this->input['opt'] <> 'na' && $this->input['opt'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    options</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php else: ?>
                                <b>options</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "

                                > </i>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">

                            <div class="select">

                                <?php if ($this->input['opt'] <> 'na' && $this->input['opt'] <> null): ?>
                                    <select class="active"  name="opt" onchange='this.form.submit();'">
                                <?php else: ?>
                                    <select  name="opt" onchange='this.form.submit();'">
                                <?php endif ?>

                                    <option <?php echo $this->input['opt'] == 'na' ? 'selected' : '' ?> value="na">non-défini</option>
                                    <option <?php echo $this->input['opt'] == 'cut' ? 'selected' : '' ?> value="cut">massicot / cutter </option>
                                    <option <?php echo $this->input['opt'] == 'peel' ? 'selected' : '' ?> value="peel"> prédecollage </option>
                                    <option <?php echo $this->input['opt'] == 'rewind' ? 'selected' : '' ?> value="rewind"> pré-imprimé </option>
                                    <option <?php echo $this->input['opt'] == 'rfid' ? 'selected' : '' ?> value="rfid">rfid</option>
                                </select>
                                <div class="select_arrow">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--OPTION-->

                <div class="row visible-xs visible-sm visible-md " >&nbsp;</div>

            </div>
            <!--2EME LIGNE-->

            <!--3EME LIGNE-->
            <div class="form-section row ">

                <!--INTERFACE-->
                <div class="col-lg-4 col-md-6 col-sm-5 col-xs-12">
                    <div class="row">
                        <div class="col-lg-12  col-xs-12">
                            <?php if ($this->input['interface'] <> 'na' && $this->input['interface'] <> null): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    interface de communication</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>interface de communication</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>


                    <div class="row ">
                        <div class="col-lg-6 col-sm-8">
                            <div class="checkbox">
                                <label>
                                    ethernet
                                    <input id="noborder"
                                        <?php echo isset($this->input['interface']['eth']) ? 'checked' : '' ?>
                                           onclick='this.form.submit();' class="checknoshadow " type="checkbox" name="interfacep[]" value="eth">
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    usb
                                    <input id="noborder"
                                        <?php echo isset($this->input['interface']['usb']) ? 'checked' : '' ?>
                                           onclick='this.form.submit();' class="checknoshadow " type="checkbox" name="interfacep[]" value="usb">
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    série
                                    <input id="noborder"
                                        <?php echo isset($this->input['interface']['serie']) ? 'checked' : '' ?>
                                           onclick='this.form.submit();' class="checknoshadow " type="checkbox" name="interfacep[]" value="serie">
                                </label>
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12">
                            <div class="checkbox">
                                <label>
                                    wifi
                                    <input id="noborder"
                                        <?php echo isset($this->input['interface']['wifi']) ? 'checked' : '' ?>
                                           onclick='this.form.submit();' class="checknoshadow " type="checkbox" name="interfacep[]" value="wifi">
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    parallèle
                                    <input id="noborder"
                                        <?php echo isset($this->input['interface']['parra']) ? 'checked' : '' ?>
                                           onclick='this.form.submit();' class="checknoshadow " type="checkbox" name="interfacep[]" value="parra">
                                </label>
                            </div>

                        </div>
                    </div>
                </div>
                <!--INTERFACE-->

                <!--CONSOMMABLE-->
                <div class="col-lg-8 col-md-6 col-sm-7 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-12  col-xs-12">
                            <?php if ( ($this->input['conso'] <> 'na' && $this->input['conso'] <> null) || $this->input['dimension'] <> ''): ?>
                                <b class="blue_royal"> <i class="fa fa-check-circle" style="margin-right: 5px"> </i>
                                    consommables et soft</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php else: ?>
                                <b>consommables & soft</b>   &nbsp;
                                <i class="fa fa-question-circle"
                                   data-toggle="tooltip"
                                   data-placement="right"
                                   title="La gamme definit l'environement et le volume d'impression xxxxxxxxxx xxxxxxxxxxx "
                                > </i>
                            <?php endif ?>
                        </div>
                    </div>


                    <div class="row ">

                        <div class="col-lg-8 hidden" style="padding-top: 8px">
                            <textarea
                                    name="dimension"
                                    id="filter"
                                    placeholder=" Indiquer vos dimensions étiquettes en mm ."
                            ><?php if(isset($this->input['dimension']))  echo   $this->input['dimension'] ; ?></textarea>
                        </div>

                        <div class="col-lg-6 ">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['conso']['ruban']) ? "checked" : '' ;?>
                                            type="checkbox"
                                            onclick='this.form.submit();'
                                            class="checknoshadow"
                                            name="conso[]"
                                            value="ruban">
                                    ruban
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['conso']['software']) ? "checked" : '' ;?>
                                            type="checkbox"
                                            onclick='this.form.submit();'
                                            class="checknoshadow"
                                            name="conso[]"
                                            value="software">
                                    logiciel d'édition étiquettes
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['conso']['printhead']) ? "checked" : '' ;?>
                                            type="checkbox"
                                            onclick='this.form.submit();'
                                            class="checknoshadow"
                                            name="conso[]"
                                            value="printhead">
                                    tête d'impression supplémentaire
                                </label>
                            </div>
                        </div>
                        <div class="col-lg-6 ">
                            <div class="checkbox">
                                <label>
                                    <input <?php echo isset($this->input['conso']['etiquette']) ? "checked" : '' ;?>
                                            type="checkbox"
                                            onclick='this.form.submit();'
                                            class="checknoshadow"
                                            name="conso[]"
                                            value="etiquette">
                                    etiquette
                                </label>
                            </div>
                        </div>
                    </div>



                </div>
                <!--CONSOMMABLE-->
            </div>
            <!--3EME LIGNE-->


            <!--BOUTTON DE VALIDATION-->
            <?php include('section_validation.phtml') ?>
            <!--BOUTTON DE VALIDATION-->
        </div>
    </div>
</form>