

<section class="properties properties_contact">
    <div class="container">
        <div class="row visible-lg visible-md" style="margin-top: 80px"></div>
        <div class="row visible-sm" style="margin-top: 120px"></div>
        <div class="row visible-xs" style="margin-top: 70px"></div>
        <div class="row" >
            <div class="col-lg-12 col-md-12">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col_blogPost">
                        <h1> <i class="fa fa-search"> </i> Recherche de materiel</h1>

                        <div class="divider"></div>

                        <div class="blogPost">


                            <?php if(isset($this->search))
                                {
                                    if($this->search == 'search_thermique')  include("form_printer_thermique.phtml");
                                    if($this->search == 'search_etiquette_badgeuse')  include("form_printer_badgeuse.phtml");
                                    if($this->search == 'search_etiquette_couleur')  include("form_printer_couleur.phtml");
                                    if($this->search == 'search_etiquette_portable')  include("form_printer_portative.phtml");

                                    if($this->search == 'search_printer_laser')  include("form_printer_laser.phtml");

                                    if($this->search == 'search_printer_matricielle')  include("form_printer_matricielle.phtml");

                                    elseif($this->search == 'search_douchette')  include("form_douchette.phtml");
                                    elseif($this->search == 'search_douchette_ring')  include("form_douchette_ring.phtml");
                                    elseif($this->search == 'search_douchette_fixe')  include("form_douchette_fixe.phtml");

                                    elseif($this->search == 'search_terminal')  include("form_terminal.phtml");
                                    elseif($this->search == 'search_terminal_pda')  include("form_terminal_pda.phtml");
                                    elseif($this->search == 'search_terminal_embarque')  include("form_terminal_embarque.phtml");
                                    elseif($this->search == 'search_terminal_poignet')  include("form_terminal_poignet.phtml");

                                    elseif($this->search == 'search_poste_client')  include("form_poste_client.phtml");
                                    elseif($this->search == 'search_poste_pc')  include("form_poste_pc.phtml");
                                    elseif($this->search == 'search_poste_portable')  include("form_poste_portable.phtml");

                                    else include("form_printer.phtml");
                                }
                                else
                                {
                                    include("form_printer_thermique.phtml");
                                } ?>

                            <?php include("result.phtml"); ?>
                        </div>
                    </div>
                </div>
                <!-- end row -->
            </div>
            <!-- end col -->

        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
    <!-- end container -->






</section>
<!-- end main content -->
<!-- end properties -->
<!-- start call to action -->
<!-- end call to action -->

<link href="<?php echo URL_DEFAULT_CSS; ?>geo/css/app.css" rel="stylesheet" type="text/css" media="all" />
<script src="<?php echo URL_DEFAULT_JS; ?>jquery.1.8.3.min.js"></script>
<script src="<?php echo URL_DEFAULT_JS; ?>bootstrap.min.js"></script>

<script type="text/javascript">
    // Document ready

    $(document).ready(function () {
        var scanner1 = j('#scanner1d:checked').length;
        var scanner2 = j('#scanner2d:checked').length;
        if( scanner1 === 1 || scanner2 === 1){
            j('#msgring').removeClass('hidden')
        }


        $( "#scanner1d" ).click(function() {
            var scanner1 = j('#scanner1d:checked').length;
            if( (scanner1 === 1) ){
                j('#msgring').removeClass('hidden')
            }
            else{
                j('#msgring').addClass('hidden')
            }
        });

        $( "#scanner2d" ).click(function() {
            var scanner2 = j('#scanner2d:checked').length;
            if( (scanner2 === 1) ){
                j('#msgring').removeClass('hidden')
            }
            else{
                j('#msgring').addClass('hidden')
            }
        });



        activateTooltip();

    });


    // Tooltip
    function activateTooltip()
    {
        j('[data-toggle="tooltip"]').tooltip();
    }
</script>


