<?php
$menus = Genius_Model_Menu::getAllMenus();
$seo = new Genius_Class_Seo();
$frontController = Zend_Controller_Front::getInstance();
$controller_name = $frontController->getRequest()->getControllerName();

$page = Genius_Model_Page::getPageByCategoryAndIdOptimize(1);
$images_home = Genius_Model_Image::getHomeImageCoverById(18, 1);
$menus_ = Genius_Class_Seo::getMetasMenu(1);
?>


<?php include('modal_panier.phtml') ?>

<section class="hidden-lg hidden-md margin-top-clean">
    <div class="container">

        <section class=" ">
            <div class="row ">
                <div class="col-lg-12" style="background-color: white;">
                    <?php include('configurateur_min.phtml') ?>
                </div>
            </div>
        </section>

        <section class=" ">
            <div class="row ">
                <div class="col-lg-12" style="background-color: white;">
                    <?php include('formulaire.phtml') ?>
                </div>
            </div>
        </section>

        <section class=" hidden-lg">
            <div class="row ">
                <div class="col-lg-12" style="background-color: white;">
                    <?php   include("result.phtml"); ?>
                </div>
            </div>
        </section>

    </div>

</section>



<!--COLONNE SIDE BAR CONFIGURATOR-->
<div class="sidebar-container hidden-sm hidden-xs" >

    <br>
    <!--MODULE DE RECHERCHE-->
    <section>
        <div class="row" style="padding-left: 15px;padding-right: 15px">
            <div class="col-lg-12" >
                <?php echo $this->render($this->autocomplete); ?>
            </div>
        </div>
    </section>
    <!--MODULE DE RECHERCHE-->

    <div class="col-lg-12  wrapper-col-configurator">

        <!--MODULE CONFIGURATOR-->
        <div class="row ">
            <div class="col-lg-12">
                <?php echo $this->render($this->filter); ?>
            </div>
        </div>
        <!--FIN CONFIGURATOR-->

        <!--BOX EXPLICATION CONFIGURATOR-->
        <div class="row ">
            <div class="col-lg-12" >
                <?php echo $this->render($this->explication); ?>
                <br>
            </div>
        </div>
        <!--FIN BOX EXPLICATION CONFIGURATOR-->
    </div>
</div>
<!--FIN COLONNE SIDE BAR CONFIGURATOR-->


<!--COLONNE CONTENU PRINCIPAL-->
<div class="section-container section margin-top-clean hidden-sm hidden-xs" style="padding: 10px;min-height: 750px">

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">

        <div class="container">

            <section class="  ">
                <div class="row ">
                    <?php include('formulaire.phtml') ?>
                </div>
            </section>

            <section class=" ">
                <div class="row ">
                    <div class="col-lg-12" style="background-color: white;">
                        <?php   include("result.phtml"); ?>
                    </div>
                </div>
            </section>

        </div>
    </div>
</div>

<?php include('messageflash.phtml') ?>


<!--FIN COLONNE CONTENU PRINCIPAL-->


<script src="<?php echo URL_DEFAULT_JS; ?>jquery.1.8.3.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {

        j('[data-toggle="tooltip"], .tooltip').tooltip({ html:true });

        setTimeout(configurator, 600);
        setTimeout(configurator2, 1000);
        setTimeout(helper_configurator, 1500);

        setTimeout(first_help, 2200);
        setTimeout(second_help, 2200);
        setTimeout(first_help_free, 3000);
        setTimeout(first_star, 3500);
        setTimeout(second_help_border, 4100);

        function first_help() {
            $("#first-config-help").slideDown();
        }

        function configurator() {
            $("#configurator").slideDown();
        }
        function configurator2() {
            $("#accordion").slideDown();
        }

        function helper_configurator() {
            $("#helper_configurator").show('slow');
        }

        function second_help() {
            $("#second-config-help").show( "slow" );
        }

        function second_help_border() {
            $("#second_border").css({
                'color': '#F8CC49',
                'font-size' :'1.2em',
                'transition' :'color 1s , font-size 1s'
            });
        }

        function first_star() {
            $("#first-star").show( "slow" );
        }

        function first_help_free() {
            $("#first-free").css({
                'font-weight': 'bolder',
                'color': '#F8CC49',
                'font-size' :'1.2em',
                'transition' :'color 1s , font-size 1s'
            });
        }

        $('a[href=#top]').click(function(){
            $('html, body').animate({scrollTop:0}, 'slow');
            return false;
        });

        var counterPannier = <?php echo $this->choice ?>;

        if(counterPannier > 0)
        {
            $(".iconepannier").show( "fast" );
            $(".first-panel- ").removeClass('first-panel-').addClass('panel- panel-d ').css('border-top','none');
        }

        var valuePannier = $("#pannierValue").text();

        console.log(valuePannier);

        $("#close-modal-panier").live("click", function(e) {
            e.preventDefault();
            $('#modal-font-panier').hide();
            $('#modal-box-panier').hide();
        });
        $("#close-modal-panier-time").live("click", function(e) {
            e.preventDefault();
            $('#modal-font-panier').hide();
            $('#modal-box-panier').hide();
        });


        $(".add-demande").live("click", function(e) {

            var scanner1d = $("#scanner1d:checked").length;
            var scanner2d = $("#scanner2d:checked").length ;
            var scanneremb = $("#scannerembarque:checked").length ;

            var condition = ( (scanner1d === 1) || (scanner2d === 1)|| (scanneremb === 1) || (scanner1d === 2) || (scanner2d === 2)|| (scanneremb === 2)) ;

            console.log(condition);
            console.log(scanner1d);
            console.log(scanner2d);
            console.log(scanneremb);

            //var condition = true ;

            if(  condition === false)
            {
                e.preventDefault();

                var id  = $(this).attr('id');

                //j('[data-toggle="tooltip"], .tooltip').tooltip("hide",{ html:true });

                $.get( "/configurateur/choice?product="+id)
                    .done(function( data ) {

                        if(data.count > 0)
                        {
                            $(".iconepannier").show( "fast" );
                            $(".first-panel- ").removeClass('first-panel-').addClass('panel- panel-d ').css('border-top','none');
                        }
                        data.count = parseInt(data.count);

                        updatedValue = data.count.toString();

                        $("#pannierValue").text(updatedValue);

                        if(data.state === 1){

                            $("#panier_img").attr( 'src',data.image );
                            $("#panier_product").text(data.article );
                            $("#panier_description").html(data.description+'...' ).text();
                            $("#panier_caracteristique").text(data.carac ).html();

                            var product = ""
                            var description = ""
                            var carac = ""



                            $('#modal-font-panier').show();
                            $('#modal-box-panier').show('slow');

                            //$(".flashMessageSucess").show( "medium" ).delay(1000).hide('slow');
                        }
                        else{
                            $(".flashMessageError").show( "medium" ).delay(1000).hide('slow');
                        }
                    });
            }
        });

    });

</script>

<style>

    body{
        background-image: url(<?php echo PROJECTS.'/upload/images/geo/grille4.png' ?>);
        background-color:#f8f8f8;
        /*background-color:#e5effa;*/
        /*background-color:#fefbf2;*/
    }
    .texte_video ul li {
        list-style: inherit !important
    }

    .btn_video {
        display: inline-block;
        margin-top: 20px !important;
        font-size: 16px;
    }

    #h1_home {
        font-weight: bold;
        line-height: 160%;
        margin-bottom: 15px;
        font-family: 'Open Sans', sans-serif, Arial;
        text-align: left;
        font-size: 15px;
        color: #464646;
    }
</style>


