<div class="flashMessageSucess" > <i class="fa fa-heart"> </i> &nbsp;L'article a bien été ajouté ! </div>
<div class="flashMessageError" > <i class="fa fa-ban "> </i> &nbsp; L'article est <u><b>deja</b></u> dans votre pannier ! </div>

<div class="backtop hidden-sm hidden-md hidden-xs"><a href="#top"><i class="fa fa-arrow-up"> </i></a></div>
<div class="backtop-md visible-md"><a href="#top"><i class="fa fa-arrow-up"> </i></a></div>