<div id="modal-font-panier" style="display: none_" class="pop_window"> </div>



        <div id="modal-box-panier" style="display: none_" class="box col-lg-4 col-md-4 col-sm-4">

            <div class="row title-box">
                <div class="col-lg-12 ">
                    <h5>Ce produit a bien été ajouté aux <b>demandes de devis</b> :</h5>
                </div>
            </div>

            <div class="row box-content" >
                <div class="col-lg-5 product-img">
                    <img
                        src="<?php echo  UPLOAD_URL.'images/products/bsx5-source-2576.jpg'?> "
                        alt="<?php echo $value['filename'] ?>"
                    >
                </div>
                <div class="col-lg-7 text-left product-description">
                    <h5> Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Ad amet architecto asperiores, consequatur cum debitis dolorum ducimus,
                        eaque error incidunt iste itaque nesciunt officia optio quas quasi rerum tenetur voluptatum.
                    </h5>
                </div>
            </div>

            <br>

            <div class="row box-button" >

                <div class="col-lg-6 first-button-wrapper">
                    <div class="row first-button" style="padding: 4px">
                        <div class="button-content text-center col-lg-12" id="close-modal-panier" >
                            <a href="">
                                <h4>Continuer a chercher des produits</h4>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="col-lg-6 second-button-wrapper">
                    <div class="row second-button" style="padding: 4px">
                        <div class="button-content text-center col-lg-12" id="close-modal-panier" >
                            <a href="">
                                <h4>Acceder aux demandes en attente</h4>
                            </a>
                        </div>
                    </div>
                </div>

            </div>

        </div>

