<div id="modal-font-panier" style="display: none" class="pop_window"> </div>


<div id="modal-box-panier" style="display: none" class="box col-lg-4 col-md-4 col-sm-4">

    <div class="row title-box">
        <div class="col-lg-10 col-md-10 col-sm-10 title">
            <h4 >Ce produit a bien été ajouté aux <b>demandes de devis</b> :</h4>
        </div>
        <div
            class="col-lg-2 col-md-2    col-sm-2 text-right modal-close"
            data-toggle="tooltip"
            data-placement="top"
            title="fermer la fenetre"
        >
            <a id="close-modal-panier-time"  href=""><i class="fa fa-times-circle-o fa-2x"> </i></a>
        </div>
    </div>

    <div class="row box-content" >
        <div class="col-lg-4  col-md-6 col-sm-6 product-img">
            <img
                id="panier_img"
                src="<?php echo  UPLOAD_URL.'images/products/bsx5-source-2576.jpg'?> "
                alt="<?php echo $value['filename'] ?>"
            >
        </div>
        <div class="col-lg-8 col-md-12 col-sm-12text-left product-description">
                <h4 id="panier_product"></h4>
                <h5 id="panier_description"> </h5>
            <p> <small id="panier_caracteristique">Caractèristique : 203 ou 300dpi - 305mm/s - 168mm - semi-industrielle</small></p>
        </div>
    </div>

    <br>

    <div class="row box-button" >

        <div class="col-lg-6 first-button-wrapper">
            <div class="row first-button" >
                <div class="button-content text-center col-lg-12" id="close-modal-panier" >
                    <a href="">
                       <h4><i class="fa fa-arrow-left"> </i> &nbsp; Ajouter d'autres produits</h4>
                    </a>
                </div>
            </div>
        </div>

        <div class="col-lg-6 second-button-wrapper">
            <div class="row second-button" >
                <div class="button-content text-center col-lg-12" id="close-modal-panier" >
                    <a href="/configurateur/panier">
                        <h4>Finaliser ma demande &nbsp; <i class="fa fa-arrow-right"> </i> </h4>
                    </a>
                </div>
            </div>
        </div>

    </div>

</div>

