<!-- start subheader -->
<?php
echo $this->render($this->subheader);
global $siteconfig;
$id_product = $this->id_product;
$id_marque = $this->id_marque;
$id_type = $this->id_type;
?>
<!-- start widgets section -->
<!-- start main content section -->
?>
<br><br><br>
<br><br><br>

<section class="">
    <div class="container">
        <div class="content_fullwidth lessmar container_<?php echo $this->background; ?>">



            <div class="row " style="padding-top: 35px">
                <div class="col-lg-12 ">

                    <?php
                    $configurator =
                        [
                            'icone' => 'fa-pencil',
                            'title' => 'Envoyer ma demande de devis',
                            'etape' => 'etape-3.phtml',
                            'photo' => '/upload/images/geo/xx.jpg'
                        ]
                    ?>
                    <?php include('configurator_title.phtml') ?>
                </div>
            </div>


            <div class="row hidden" style="padding-top: 35px">
                <div class="col-lg-12 ">
                    <div class="row wrapper-configurator-section ">
                        <div class="col-md-12 text-left configurator">
                            <div class="configurator-title">
                                <a class="anconfigurator" href="/configurateur">
                                    <img style="height: auto; width: 70px;"
                                         src="<?php echo PROJECTS.'/upload/images/geo/logodeviscrayon.png'?>"
                                         alt="demande de devis"
                                    >
                                    <!--<span class="fa-stack fa-lg" style="font-size: 2em">-->
                                    <!--    <i class="fa fa-circle fa-stack-2x " style="font-size: 2em ; color:white;"></i>-->
                                    <!--    <i class="fa fa-info fa-stack-1x " ></i>-->
                                    <!--</span>-->
                                </a>

                                <br>
                                <div style="
                                    padding-left: 85px;
                                    margin-top:-55px;
                                    text-decoration-style: initial;
                                    font-weight: lighter;
                                    position: relative;
                                    font-size: 0.7em;
                                    padding-bottom: 10px;
                                    "
                                >
                                    <a
                                            style="font-size: 2em;font-weight: bold"
                                            class="anconfigurator" href="/configurateur/panier"> Envoyer ma demande de devis
                                    </a>
                                    <br>
                                    <span style="letter-spacing: 2px; border-bottom: 1px lightsteelblue dashed"></span> Etape final <b>3</b>&nbsp;/&nbsp;3
                                </div>
                            </div>

                        </div>
                        <div class="col-md-2 configurator-img hidden" style="background-color: #004FAE;">
                            <div class="configurator-title right  pull-right">
                                <img style=" width 82px; height: 82px ; border-radius: 82px ; "
                                     src="<?php echo PROJECTS.'/upload/images/geo/pf4i.jpg' ?>" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="content_contact">
                <div class="right_contact" style="display:none">
                    <p><?php echo $this->translate("Nous contacter par téléphone") ?></p>
                    <p>04 93 47 25 00</p>
                    <p><a href="mailto:<?php echo $siteconfig->email; ?>"><?php echo $siteconfig->email; ?></a></p>
                    <p><?php echo $this->translate("Contact chat") ?><img
                                src="<?php echo THEMES_DEFAULT_URL; ?>images/chat.png" alt="" title=""
                                class="inline-image"/></p>
                </div>
                <div class="spacer"></div>
            </div>

            <div class="reg_form">

                <form id="sky-form" class="sky-form" action="configurateur/demande" method="post">

                    <div class="row" >
                        <div class="col-lg-8 col-md-12 col-sm-12 " >
                            <div class="section " style="padding: 10px">
                                <div class="col-lg-12 col-md-12 col-sm-12 ">
                                    <?php @include('contenue_panier.phtml') ?>
                                </div>
                            </div>


                            <div class="section " style="padding: 10px 30px 10px 30px">
                                <div class="col-lg-12 col-md-12 col-sm-12 ">
                                    <textarea
                                            name="info"
                                            id="filterdevis"
                                            placeholder="Infomations complémentaires"
                                    ></textarea>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-12 col-sm-12" >

                            <div class="section " style="padding: 20px">
                                <div class="col-lg-12 col-md-12 col-sm-12 ">
                                    <div class="row" >
                                        <div class="col-lg-12">
                                            <h5><b>VOS COORDONNEES</b></h5>
                                        </div>
                                    </div>
                                    <br>
                                        <div class="row">
                                            <input class="configuratordevis " type="text" name="compagny" placeholder="Raison sociale" required>
                                        </div>
                                        <br>
                                        <div class="row">
                                            <input class="configuratordevis " type="text" name="prenom" placeholder="Votre prènom" >
                                        </div>
                                        <br>
                                        <div class="row">
                                            <input class="configuratordevis " type="text" name="nom" placeholder="Votre nom" >
                                        </div>
                                        <br>
                                        <div class="row">
                                            <input class="configuratordevis " type="email" name="email" placeholder="Email" required>
                                        </div>
                                        <br>
                                        <div class="row">
                                            <input class="configuratordevis " type="number" name="tel" placeholder="Téléphone"
                                                   
                                            >
                                        </div>
                                        <br>
                                        <div class="row">
                                            <div class="col-lg-11">
                                                <input type="submit" class="btn btn-euro-blue-royal b" value="Envoyer ma demande" style="padding:7px;font-weight: bolder">
                                            </div>
                                        </div>
                                    <br>
                                    <!--CAPTCHA-->
                                    <?php //include('captcha.phtml')?>
                                    <!--CAPTCHA-->
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class=" response-delay" >
                                                <i class="fa fa-info-circle"> </i>  &nbsp; Réponse sous <u>4h</u>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="section hidden" >
                                <div class="col-lg-12 col-md-12 col-sm-12 ">
                                    <header class="left"><?php echo $this->translate("Vos coordonnées") ?></header>
                                    <fieldset>
                                        <section>
                                            <label class="input">
                                                <input class="validate[required]" type="text" name=""
                                                       id="raison_sociale"
                                                       placeholder="<?php echo $this->translate("Raison sociale") ?>">
                                                <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre raison sociale") ?> </b>
                                            </label>
                                        </section>
                                        <section>
                                            <label class="input">
                                                <input type="text" name="" id="prenom"
                                                       placeholder="<?php echo $this->translate("Votre prénom") ?>">
                                                <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre prénom") ?> </b>
                                            </label>
                                        </section>
                                        <section>
                                            <label class="input">
                                                <input type="text" name="" id="nom"
                                                       placeholder="<?php echo $this->translate("Votre nom") ?>">
                                                <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre nom") ?> </b>
                                            </label>
                                        </section>
                                        <section>
                                            <label class="input">
                                                <input class="validate[required,custom[email]]" type="" name=""
                                                       id="email" placeholder="<?php echo $this->translate("Email") ?>">
                                                <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre adresse email") ?></b>
                                            </label>
                                        </section>
                                        <section>
                                            <label class="input">
                                                <input type="tel" name="" id="tel"
                                                       placeholder="<?php echo $this->translate("Téléphone") ?>">
                                                <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre numéro de téléphone") ?></b>
                                            </label>
                                        </section>
                                        <section>
                                            <!--CAPTCHA-->
                                            <?php //include('captcha.phtml')?>
                                            <!--CAPTCHA-->
                                        </section>
                                    </fieldset>
                                    <div class="note"><?php echo $this->translate("*Les champs comportant une astérisque doivent obligatoirement être remplis.") ?></div>
                                    <div style="text-align:right;">
                                        <button type="submit" class="buttonColor"
                                                style="display:inline-block;font-size:16px;margin-top:15px;"><?php echo $this->translate("Demander un devis") ?></button>
                                        <input type="hidden" name="submitted" id="submitted" value="true"/>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            test
                                        </div>
                                    </div>
                                    <div class="spacer"></div>

                                </div>
                            </div>

                        </div>
                    </div>


                </form>
            </div>

            <div class="row" style="padding: 10px 0px 20px 0px">
                <div class="" style="width: 300px">
                    <a href="configurateur/" class=" btn btn-euro-yellow" ><b><i class="fa fa-angle-left"> </i> &nbsp; Rerchercher d'autres article</b></a>
                </div>
            </div>
            <br>
            <br>
        </div>
    </div>
    <!-- end container -->
</section>
<!-- end main content -->


<link href="<?php echo URL_DEFAULT_CSS; ?>geo/css/app.css" rel="stylesheet" type="text/css" media="all"/>
<script src="<?php echo URL_DEFAULT_JS; ?>jquery.1.8.3.min.js"></script>
<script src="<?php echo URL_DEFAULT_JS; ?>bootstrap.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {

        $(".testdelete").live("click", function(e) {

            e.preventDefault();

            var id  = $(this).attr('id');

            var counterRow = $('table tr').length-2 ;
            console.log(counterRow);

            $.post("/configurateur/deletechoice?product="+id
                ,
                function() {
                })
                .done(function(data){
                    counterRow = $('table tr').length-2 ;
                    console.log(counterRow);

                    row = "#row_"+data;

                    console.log(uri);
                    if( counterRow === 0 )
                    {
                        var uri = window.location.origin;
                        window.location.replace(uri+"/configurateur/aide");
                    }
                    else{
                        $(row).remove()
                    }
                });
        });

        $(".button_qte_minus").live("click", function(e) {

            e.preventDefault();

            $.post("/configurateur/qte/sub?product="+this.id
                ,
                function() {
                })
                .done(function(data){
                    selector = '#valq_'+data
                    select = $(selector) ;
                    valueqte = select.text() ;
                    console.log(valueqte)

                    if(valueqte > 1){
                        updatedValue = parseInt(valueqte)-1;
                        updatedValue = updatedValue.toString();
                        select.replaceWith("<b id=\"valq_"+data+"\">"+updatedValue+"</b>");
                    }

                });
        });

        $(".button_qte_plus").live("click", function(e) {

            e.preventDefault();

            $.post("/configurateur/qte/add?product="+this.id
                ,
                function() {
                })
                .done(function(data){
                    selector = '#valq_'+data
                    select = $(selector) ;
                    valueqte = select.text() ;
                    updatedValue = parseInt(valueqte)+1;
                    updatedValue = updatedValue.toString();
                    select.replaceWith("<b id=\"valq_"+data+"\">"+updatedValue+"</b>");
                })
            ;
        });
    });


    // Document ready
    $(document).ready(function () {
        activateTooltip();
    });

    // Tooltip
    function activateTooltip() {
        $('[data-toggle="tooltip"]').tooltip();
    }
</script>


