
<!-- start subheader -->
<?php
echo $this->render($this->subheader);
global $siteconfig;
$id_product = $this->id_product;
$id_marque = $this->id_marque;
$id_type = $this->id_type;
?>
<!-- start widgets section -->
<!-- start main content section -->
?>
<br><br><br>
<br><br><br>

<section class="">
    <div class="container">
        <div class="content_fullwidth lessmar container_<?php echo $this->background; ?>">
            <div class="content_contact">
                <div class="left_contact" style="">
                    <h2><?php echo $this->translate("Materiel en attente de devis");?></h2>
                </div>
                <br>
                <div class="right_contact" style="display:none">
                    <p><?php echo $this->translate("Nous contacter par téléphone")?></p>
                    <p>04 93 47 25 00</p>
                    <p><a href="mailto:<?php echo $siteconfig->email;?>"><?php echo $siteconfig->email;?></a></p>
                    <p><?php echo $this->translate("Contact chat")?><img src="<?php echo THEMES_DEFAULT_URL; ?>images/chat.png" alt="" title="" class="inline-image" /></p>
                </div>
                <div class="spacer"></div>
            </div>
            <div class="reg_form">
                <form id="sky-form" class="sky-form"  action="" method="post">
                    <input type="hidden" value="<?php echo $id_product; ?>" name="id_product" />
                    <input type="hidden" value="<?php echo $id_marque; ?>" name="id_marque" />
                    <input type="hidden" value="<?php echo $id_type; ?>" name="id_type" />
                    <div class="one_half last animate fadeInLeft" data-anim-type="fadeInLeft">
                        <div class="row ">
                                        <div class="col-lg-12 " style="font-size: 12px">
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th>  </th>
                                                    <th>PRODUIT</th>
                                                    <th>CARACTERISTIQUES</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <?php foreach ($this->pannier as $index => $item) : ?>
                                                    <tr>
                                                        <td >
                                                            <a href="filtre/deletechoice?product=<?php echo $index ?>">
                                                             <i style="color:indianred" class="fa fa-times "></i>
                                                            </a>
                                                        </td>
                                                        <td> <?php echo $item['choice'] ?></td>
                                                        <td>
                                                            <?php echo strtoupper($item['section']) ?>
                                                            <br>
                                                            <ul>
                                                                <?php echo is_string($item['input']) ? $item['input'] : ''  ;?>

                                                                <?php foreach ($item['input'] as $i => $v) : ?>
                                                                    <?php if(is_array($v)): ?>
                                                                        <ul  style="font-size:12px ; ">
                                                                            <b><?php echo $i ?> :</b>
                                                                            <?php foreach ($v as $subindex => $subvalue) :?>
                                                                                <li style="font-size: 12px "> <?php echo $subvalue ?> </li>
                                                                            <?php endforeach; ?>
                                                                        </ul>
                                                                    <?php else: ?>
                                                                        <li style="font-size:12px"><?php echo $i .' : '. $v ?></li>
                                                                    <?php endif; ?>
                                                                <?php endforeach; ?>

                                                            </ul>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                    </div>
                    <div class="one_half animate fadeInRight" data-anim-type="fadeInRight">
                        <header><?php echo $this->translate("Vos coordonnées")?></header>
                        <fieldset>
                            <section>
                                <label class="input">
                                    <input class="validate[required]" type="text" name="raison_sociale" id="raison_sociale" placeholder="<?php echo $this->translate("Raison sociale")?>">
                                    <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre raison sociale")?> </b> </label>
                            </section>
                            <section>
                                <label class="input">
                                    <input type="text" name="prenom" id="prenom" placeholder="<?php echo $this->translate("Votre prénom")?>">
                                    <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre prénom")?> </b> </label>
                            </section>
                            <section>
                                <label class="input">
                                    <input type="text" name="nom" id="nom" placeholder="<?php echo $this->translate("Votre nom")?>">
                                    <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre nom")?> </b> </label>
                            </section>
                            <section>
                                <label class="input">
                                    <input class="validate[required,custom[email]]" type="email" name="email" id="email" placeholder="<?php echo $this->translate("Email")?>">
                                    <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre adresse email")?></b> </label>
                            </section>
                            <section>
                                <label class="input">
                                    <input type="tel" name="tel" id="tel" placeholder="<?php echo $this->translate("Téléphone")?>">
                                    <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre numéro de téléphone")?></b> </label>
                            </section>
                            <section>
                                <div class="g-recaptcha" data-sitekey="6Le4UwoUAAAAAMRyMG_qtFb0NoleMf5XhRsrxFO6"></div>
                            </section>
                        </fieldset>
                        <div class="note"><?php echo $this->translate("*Les champs comportant une astérisque doivent obligatoirement être remplis.")?></div>
                        <div style="text-align:right;">
                            <button type="submit" class="buttonColor" style="display:inline-block;font-size:16px;margin-top:15px;"><?php echo $this->translate("Demander un devis")?></button>
                            <input type="hidden" name="submitted" id="submitted" value="true" />
                        </div>
                        <div class="spacer"></div>
                    </div>
                    <div class="spacer"></div>
                    <input type="hidden" name="submitted" id="submitted" value="true" />
                </form>
            </div>
        </div>
    </div>
    <!-- end container -->
</section>
<!-- end main content -->



<link href="<?php echo URL_DEFAULT_CSS; ?>geo/css/app.css" rel="stylesheet" type="text/css" media="all" />
<script src="<?php echo URL_DEFAULT_JS; ?>jquery.1.8.3.min.js"></script>
<script src="<?php echo URL_DEFAULT_JS; ?>bootstrap.min.js"></script>

<script type="text/javascript">
    // Document ready
    $(document).ready(function () {
        activateTooltip();
    });

    // Tooltip
    function activateTooltip()
    {
        $('[data-toggle="tooltip"]').tooltip();
    }
</script>


