<!-- start subheader -->
<?php
echo $this->render($this->subheader);
global $siteconfig;
$id_product = $this->id_product;
$id_marque = $this->id_marque;
$id_type = $this->id_type;
?>
<!-- start widgets section -->
<!-- start main content section -->
?>
<br><br><br>
<br><br><br>

<section class="">
    <div class="container">
        <div class="content_fullwidth lessmar container_<?php echo $this->background; ?>">

            <div class="row " style="padding-top: 35px">
                <div class="col-lg-12 ">
                    <div class="row wrapper-configurator-section ">
                        <div class="col-md-12 text-left configurator">
                            <div class="configurator-title">
                                    <span class="fa-stack fa-lg" style="font-size: 2em">
                                        <i class="fa fa-circle fa-stack-2x " style="font-size: 2em ; color:white;"></i>
                                        <i class="fa fa-shopping-cart fa-stack-1x "></i>
                                    </span>
                                PANNIER - materiel en attente de devis
                                <br>
                            </div>
                        </div>
                        <div class="col-md-2 configurator-img hidden" style="background-color: #004FAE;">
                            <div class="configurator-title right  pull-right">
                                <img style=" width 82px; height: 82px ; border-radius: 82px ; "
                                     src="<?php echo PROJECTS.'/upload/images/geo/pf4i.jpg' ?>" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content_contact">
                <div class="right_contact" style="display:none">
                    <p><?php echo $this->translate("Nous contacter par téléphone") ?></p>
                    <p>04 93 47 25 00</p>
                    <p><a href="mailto:<?php echo $siteconfig->email; ?>"><?php echo $siteconfig->email; ?></a></p>
                    <p><?php echo $this->translate("Contact chat") ?><img
                                src="<?php echo THEMES_DEFAULT_URL; ?>images/chat.png" alt="" title=""
                                class="inline-image"/></p>
                </div>
                <div class="spacer"></div>
            </div>

            <div class="reg_form">

                <form id="sky-form" class="sky-form" action="" method="post">
                    <input type="hidden" value="<?php echo $id_product; ?>" name="id_product"/>
                    <input type="hidden" value="<?php echo $id_marque; ?>" name="id_marque"/>
                    <input type="hidden" value="<?php echo $id_type; ?>" name="id_type"/>

                    <div class="row" >

                        <div class="col-lg-6 col-md-12 col-sm-12 " >
                            <div class="section " style="padding: 10px">
                                <div class="col-lg-12 col-md-12 col-sm-12 ">
                                    <?php @include('contenue_pannier.phtml') ?>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6 col-md-12 col-sm-12" >
                            <div class="section " style="padding: 10px">
                                <div class="col-lg-12 col-md-12 col-sm-12 ">
                                    <header class="left"><?php echo $this->translate("Vos coordonnées") ?></header>
                                    <fieldset>
                                        <section>
                                            <label class="input">
                                                <input class="validate[required]" type="text" name="raison_sociale"
                                                       id="raison_sociale"
                                                       placeholder="<?php echo $this->translate("Raison sociale") ?>">
                                                <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre raison sociale") ?> </b>
                                            </label>
                                        </section>
                                        <section>
                                            <label class="input">
                                                <input type="text" name="prenom" id="prenom"
                                                       placeholder="<?php echo $this->translate("Votre prénom") ?>">
                                                <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre prénom") ?> </b>
                                            </label>
                                        </section>
                                        <section>
                                            <label class="input">
                                                <input type="text" name="nom" id="nom"
                                                       placeholder="<?php echo $this->translate("Votre nom") ?>">
                                                <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre nom") ?> </b>
                                            </label>
                                        </section>
                                        <section>
                                            <label class="input">
                                                <input class="validate[required,custom[email]]" type="email" name="email"
                                                       id="email" placeholder="<?php echo $this->translate("Email") ?>">
                                                <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre adresse email") ?></b>
                                            </label>
                                        </section>
                                        <section>
                                            <label class="input">
                                                <input type="tel" name="tel" id="tel"
                                                       placeholder="<?php echo $this->translate("Téléphone") ?>">
                                                <b class="tooltip tooltip-bottom-right"><?php echo $this->translate("Entrer votre numéro de téléphone") ?></b>
                                            </label>
                                        </section>
                                        <section>
                                            <div class="g-recaptcha"
                                                 data-sitekey="6Le4UwoUAAAAAMRyMG_qtFb0NoleMf5XhRsrxFO6"></div>
                                        </section>
                                    </fieldset>
                                    <div class="note"><?php echo $this->translate("*Les champs comportant une astérisque doivent obligatoirement être remplis.") ?></div>
                                    <div style="text-align:right;">
                                        <button type="submit" class="buttonColor"
                                                style="display:inline-block;font-size:16px;margin-top:15px;"><?php echo $this->translate("Demander un devis") ?></button>
                                        <input type="hidden" name="submitted" id="submitted" value="true"/>
                                    </div>
                                    <div class="spacer"></div>
                                </div>
                            </div>

                        </div>

                    </div>
                    <div class="spacer"></div>
                    <input type="hidden" name="submitted" id="submitted" value="true"/>
                </form>
            </div>
        </div>
    </div>
    <!-- end container -->
</section>
<!-- end main content -->


<link href="<?php echo URL_DEFAULT_CSS; ?>geo/css/app.css" rel="stylesheet" type="text/css" media="all"/>
<script src="<?php echo URL_DEFAULT_JS; ?>jquery.1.8.3.min.js"></script>
<script src="<?php echo URL_DEFAULT_JS; ?>bootstrap.min.js"></script>

<script type="text/javascript">
    // Document ready
    $(document).ready(function () {
        activateTooltip();
    });

    // Tooltip
    function activateTooltip() {
        $('[data-toggle="tooltip"]').tooltip();
    }
</script>


