
<div class="row result-wrapper-content " style="background-color: white; margin-bottom:0">
    <div class="col-lg-2"></div>
    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 content-product-wrapper " >

        <div class="row content-data-wrapper "  style="padding-top: 0;">
            <div class="col-lg-7 data-button ">
                <div class="row button-wrapper">
                    <input type="submit" class="add-filtre" value="APPLIQUER LE FILTRE" style="font-weight: bolder">
                </div>
            </div>

            <div class="col-lg-1"></div>

            <div class="col-lg-4  col-sm-12 data-button ">
                <?php //var_dump($value) ?>

                <div class="row button-wrapper" >

                    <a  href="configurateur/delete">
                        <div
                                class="col-lg-12  add-reset"
                        >
                            <i class="fa fa-minus"> </i> &nbsp;  Ré-initialiser les critéres
                        </div>
                    </a>

                </div>
            </div>


        </div>

    </div>
</div>
<div class="row hidden" style="padding: 8px 8px 8px 8px ; background-color: white;">

    <div class=" col-lg-4 col-sm-6 col-xs-12 " style="padding-top: 20px" >
        <input type="submit" class="btn btn-euro-blue-royal-s b" value=" APPLIQUER LE FILTRE" style="font-weight: bolder">
    </div>
    <div class=" col-lg-4 col-sm-6 col-xs-12" style="padding-top: 10px" >

    </div>

    <div class="col-lg-8 col-sm-6 col-xs-12" style="padding-top: 10px" >
        <a href="configurateur/delete" class=" btn btn-euro-yellow-s" >Ré-initialiser les critéres</a>
    </div>
</div>