<div class="row" style="padding: 8px 8px 8px 8px ; background-color: white;">

    <div class=" col-lg-8 col-sm-6 col-xs-12 " style="padding-top: 10px" >
        <input type="submit" class="btn btn-euro-blue-royal b" value="FILTRER" style="font-weight: bolder">
    </div>

    <div class="col-lg-4 col-sm-6 col-xs-12" style="padding-top: 10px" >
        <a href="configurateur/delete" class=" btn btn-euro-orange" >reset</a>
    </div>
</div>