
<div class="row result-wrapper-content " style="background-color: white; margin-bottom:0">

    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-5">

    </div>

    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 content-product-wrapper " >

        <div class="row content-data-wrapper "  style="padding-top: 0;">

            <div class="col-lg-8 col-md-12 data-description ">

                <div class="row wrapper-description">
                 &nbsp;
                </div>

            </div>

            <div class="col-lg-4  col-sm-12 data-button ">
                <?php //var_dump($value) ?>

                <div
                        class="row button-wrapper"
                >

                    <a  href="configurateur/delete">
                        <div
                            class="col-lg-12  add-reset"
                        >
                            <i class="fa fa-minus"> </i> &nbsp;  Ré-initialiser les critéres
                        </div>
                    </a>

                </div>
            </div>


        </div>

    </div>
</div>
