<!--    CATEGORIE DOUCHETTE-->
<div class="panel- panel-d">

    <div class="panel-h" role="tab" id="douchette">
        <div class="container panel-t">
            <div class="col-sm-12 col-md-12 col-lg-12 ">
                <h4 >
                        <span class="fa-stack fa-lg euro-stack">
                               <i class="fa fa-circle fa-stack-2x"></i>
                               <i class="fa fa-barcode fa-stack-1x fa-inverse "></i>
                        </span>

                    <a class="collapsed"
                       role="button"
                       data-toggle="collapse"
                       data-parent="#accordion"
                       href="#douchettedata"
                       aria-expanded="false"
                       aria-controls="douchettedata">
                        <b>L</b>ecteurs Code-barres
                    </a>
                </h4>
            </div>

        </div>
    </div>

    <div id="douchettedata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="douchette">
        <div class="panel-b">
            <div class="row " >
                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                    <a href="/configurateur/form?f=search_douchette">
                        <div class="row" id="image_configurateur">
                            <img src="<?php echo PROJECTS.'/upload/images/geo/9300.jpg' ?>" alt="">
                        </div>
                        <div class="row ">Douchette</div>
                    </a>
                </div>
                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                    <a href="/configurateur/form?f=search_douchette_ring">
                        <div class="row" id="image_configurateur">
                            <img src="<?php echo PROJECTS.'/upload/images/geo/rs6000.jpg' ?>" alt="">
                        </div>
                        <div class="row ">Ring</div>
                    </a>
                </div>
                <div class="col-sm-4 col-md-6 col-lg-4 text-center hidden">
                    <a href="/configurateur/form?f=search_douchette_fixe">
                        <div class="row" id="image_configurateur">
                            <img src="<?php echo PROJECTS.'/upload/images/geo/2200.jpg' ?>" alt="">
                        </div>
                        <div class="row blue b"><b>FIXE</b></div>
                    </a>

                </div>
                <br><br>
            </div>
        </div>
    </div>

</div>
<!--    FIN CATEGORIE DOUCHETTE-->