<div class='card-wrapper '>
    <a href="/configurateur/aide"  title=""
    >
        <div class='card-euro' ">
            <div class='card-content '
                 style='background-image:url(<?php echo PROJECTS.'/upload/images/geo/aide_configurateur.jpg' ?>)'
            >
                <h3 class="">DEVIS GRATUIT</h3>
                <h6><b>En 3 étapes !</b></h6>
                <div class="card-overlay">&nbsp;</div>
            </div>
        </div>
    </a>
</div>