<div class='card-wrapper '>
    <a href="/configurateur/aide"  title=""
    >
        <div class='card-euro' >
            <div class='card-content '
                 style='background-image:url(<?php echo PROJECTS.'/upload/images/geo/logodevis_.png' ?>)'
            >
                <h3
                        style="margin-top : 15px ; margin-bottom : 15px ;display : none;"
                        id="first-config-help" >

                    <i style="display : none;" id="first-star" class="fa fa-check  yellow" ></i>
                    DEVIS <span id="first-free">GRATUIT</span>
                </h3>
                <h6
                    style="margin-top : 15px ; display : none"
                    id="second-config-help">
                    En <span id="second_border">3</span> étapes !

                </h6>
                <div class="card-overlay">&nbsp;</div>
            </div>
        </div>
    </a>
</div>