<div class='card-wrapper '>
    <a href="/configurateur/aide"  title=""
    >
        <div class='card-euro' ">
            <div class='card-content '
                 style='background-image:url(<?php echo PROJECTS.'/upload/images/geo/aide_configurateur.jpg' ?>)'
            >
                <h3 style="display : none;" id="first-config-help" class="">DEVIS <span id="first-free">GRATUIT</span></h3>
                <h6 style="display : none;"  id="second-config-help"><b>En 3 étapes !</b></h6>
                <div class="card-overlay">&nbsp;</div>
            </div>
        </div>
    </a>
</div>