<div id="configurator" class="row wrapper-configurator " style="display:none;font-family: Arial;">
    <div class="col-md-12 text-left configurator">
        <div class="configurator-title">

            <a class="hidden-xs anconfigurator" href="/configurateur">
                <span class="fa-stack fa-lg" style="font-size: 2em">
                    <i class="fa fa-circle fa-stack-2x " style="font-size: 2em ; color:white;"></i>
                    <i class="fa fa-crop fa-stack-1x " ></i>
                </span>
            </a>

            <div
                    style="
                        padding-left: 77px;
                        margin-top:-55px;
                        text-decoration-style: initial;
                        position: relative;
                        font-size: 0.7em;
                        padding-bottom: 10px;
                    "
                    class="hidden-xs"
            >

                <a
                        style="font-size: 2em;font-weight: bold"
                        class="anconfigurator" href="/configurateur">CONFIGURATEUR
                </a>
                <br>
                <span class="etape-emp">
                    <span style="font-weight: lighter">Quel Materiel ?</span>  - <b class="etape-under"> ETAPE 1/3</b>
                </span>

            </div>
        </div>
    </div>
</div>
<div class="panel-g" id="accordion" role="tablist" aria-multiselectable="true" style="display:none;font-family: Arial;">

     <?php include('panier.phtml') ?>
    <?php //include('printer_filter.phtml') ?>
    <?php include('printer_filter_first.phtml') ?>
    <?php include('douchette_filter.phtml') ?>
    <?php include('terminal_filter.phtml') ?>
    <?php include('poste_filter.phtml') ?>
</div>
