<div class="row wrapper-configurator ">
    <div class="col-md-12 text-left configurator">
        <div class="configurator-title">
            <span class="fa-stack fa-lg" style="font-size: 2em">
                <i class="fa fa-circle fa-stack-2x " style="font-size: 2em ; color:white;"></i>
                <i class="fa fa-crop fa-stack-1x " ></i>
            </span>
            <a class="anconfigurator" href="/filtre">CONFIGURATEUR</a>
            <br>
        </div>
    </div>
</div>
<div class="panel-g" id="accordion" role="tablist" aria-multiselectable="true">
    <?php include('printer_filter.phtml') ?>
    <?php include('douchette_filter.phtml') ?>
    <?php include('terminal_filter.phtml') ?>
    <?php include('poste_filter.phtml') ?>
</div>