<div class="row wrapper-configurator ">
    <div class="col-md-12 text-left configurator">
        <div class="configurator-title">
            <a class="anconfigurator" href="/configurateur">
                <span class="fa-stack fa-lg" style="font-size: 2em">
                    <i class="fa fa-circle fa-stack-2x " style="font-size: 2em ; color:white;"></i>
                    <i class="fa fa-crop fa-stack-1x " ></i>
                </span>
            </a>

            <br>
            <div style="
            padding-left: 77px;
            margin-top:-55px;
            text-decoration-style: initial;
            font-weight: lighter;
            position: relative;
            font-size: 0.7em;
            padding-bottom: 10px;
            ">
                <a
                        style="font-size: 2em;font-weight: bold"
                        class="anconfigurator" href="/configurateur">CONFIGURATEUR
                </a><br>
                <span style="letter-spacing: 2px; border-bottom: 1px lightsteelblue dashed">LE CHOIX</span> - Etape <b>1</b>&nbsp;/&nbsp;3
            </div>
        </div>
    </div>
</div>
<div class="panel-g" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="first-panel- ">
        <h4>panier</h4>
    </div>
    <?php include('printer_filter.phtml') ?>
    <?php include('douchette_filter.phtml') ?>
    <?php include('terminal_filter.phtml') ?>
    <?php include('poste_filter.phtml') ?>
</div>
<br>