<div class="row " style="padding-top: 20px;padding-left: 15px;padding-right: 15px">
        <div class="col-lg-12 boxPannier">
            <a href="configurateur/pannier">
                <div class="row">

                    <div class="col-lg-9">
                        <img class="" src="<?php echo PROJECTS.'/upload/images/geo/paper.png'?>" alt="devis">
                        <span style="font-size: ">
                            <b>D</b>EVIS en <u style="font-style:italic;">attente</u>
                        </span>
                    </div>

                    <div class="col-lg-3" style="padding-top: 7px">
                        <span id="pannierValue" class="circle-badge"><?php echo $this->choice ?></span>
                    </div>
                </div>
            </a>

    </div>
</div>