<div class="row " style="padding-top: 10px">
    <div class="col-lg-9 gradientBox" >
        &nbsp;
        &nbsp;
        &nbsp;
    </div>

    <div class="col-lg-3 text-center">
        <a href="/configurateur/pannier">
            <div class="col-lg-12 alert-info boxPannier text-center">
                <i class="fa fa-shopping-cart "> </i> <b>&nbsp;Pannier&nbsp;&nbsp;</b>
                <span id="pannierValue" class="circle-badge"><?php echo $this->choice ?></span>
            </div>
        </a>
    </div>


</div>