<div class="row " style="padding-top: 20px;padding-left: 15px;padding-right: 15px">
        <div class="col-lg-12 boxPannier">
            <a href="configurateur/pannier">
                <div class="row">
                    <div class="col-lg-9">
                    <span class="fa-stack fa-lg" style="font-size: 2em">
                    <i class="fa fa-circle fa-stack-2x " style="font-size: 2em ; color:white;"></i>
                    <i class="fa fa-tag fa-stack-1x "></i>
                </span>
                        <span style="font-size: ">
                        <b>D</b>EVIS en <u style="font-style:italic;">attente</u>
                    </span>
                    </div>
                    <div class="col-lg-3" style="padding-top: 7px">
                        <span id="pannierValue" class="circle-badge"><?php echo $this->choice ?></span>
                    </div>
                </div>
            </a>









    </div>
</div>