<!--    PANIER-->
<div  class="iconepannier first-panel-panier- " style="display: none">
    <div class="panel-h" role="tab" id="prt">
        <div class="container panel-t">
            <div class="col-sx-12 col-sm-12 col-md-12 col-lg-12 ">
                <h4>
                    <img style="height: auto; width: 45px;" class="" src="<?php echo PROJECTS.'/upload/images/geo/logodeviscrayon.png'?>" alt="devis">

                    <a rel="nofollow"
                        href="/configurateur/panier"
                        class="collapsed"
                    >
                        <b>D</b>emande en attente  - <b id="pannierValue"> <?php echo $this->choice ?>
                            <?php if($this->choice > 1): ?>
                            <small class="white">articles</small>
                            <?php else: ?>
                                <small class="white">article</small>
                            <?php endif ?>

                        </b>
                    </a>
                </h4>
            </div>
        </div>
    </div>

</div>
<!--  PANIER-->