<!--    CATEGORIE POSTE DE TRAVAIL-->
<div class="panel- panel-d">

    <div class="panel-h" role="tab" id="termi">
        <div class="container panel-t">
            <div class="col-sm-12 col-md-12 col-lg-12 ">
                <h4 >
                        <span class="fa-stack fa-lg euro-stack">
                               <i class="fa fa-circle fa-stack-2x"></i>
                               <i class="fa fa-laptop fa-stack-1x fa-inverse "></i>
                        </span>
                    &nbsp;

                    <a class="collapsed"
                       role="button"
                       data-toggle="collapse"
                       data-parent="#accordion"
                       href="#postedata"
                       aria-expanded="false"
                       aria-controls="postedata">
                        <b>P</b>ostes de travail
                    </a>
                </h4>
            </div>

        </div>
    </div>

    <div id="postedata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="poste">
        <div class="panel-b">
            <div class="row bb3pink" >
                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                    <a href="/filtre/form?f=search_poste_client">
                        <div class="row" id="image_configurateur">
                            <img src="<?php echo PROJECTS.'/upload/images/geo/cl.jpg' ?>" alt="">
                        </div>
                        <div class="row blue b"><b>CLIENT LEGER</b></div>
                    </a>
                </div>
                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                    <a href="/filtre/form?f=search_poste_pc">
                        <div class="row" id="image_configurateur">
                            <img src="<?php echo PROJECTS.'/upload/images/geo/pc.jpg' ?>" alt="">
                        </div>
                        <div class="row blue b"><b>PC</b></div>
                    </a>
                </div>
                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                    <a href="/filtre/form?f=search_poste_portable">
                        <div class="row" id="image_configurateur">
                            <img src="<?php echo PROJECTS.'/upload/images/geo/portable.jpg' ?>" alt="">
                        </div>
                        <div class="row blue b"><b>PORTABLE</b></div>
                    </a>

                </div>
                <br><br>
            </div>
        </div>
    </div>

</div>
<!--    FIN CATEGORIE POSTE DE TRAVAIL-->