<!--    CATEGORIE IMPRIMANTE-->
<!--<div class="first-panel- ">-->
<div class="panel- panel-d ">
    <div class="panel-h" role="tab" id="prt">
        <div class="container panel-t">
            <div class="col-sx-12 col-sm-12 col-md-12 col-lg-12 ">
                <h4>
                    <span class="fa-stack fa-lg euro-stack">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-print fa-stack-1x fa-inverse "></i>
                    </span>
                    <a
                            rel="nofollow"
                            class="collapsed"
                       role="button"
                       data-toggle="collapse"
                       data-parent="#accordion"
                       href="#prtdata"
                       aria-expanded="false"
                       aria-controls="prtdata">

                        <b>I</b>mprimantes
                    </a>
                </h4>
            </div>
        </div>
    </div>

    <div id="prtdata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="prt">
        <div class="panel-b">

            <div class="panel-g" id="prtl" role="tablist" aria-multiselectable="true">

                <div class="second-nested-panel-  panel-d">
                    <div class="second-nested-panel-h" role="tab" id="etik">
                        <div class="second-nested-panel-t">
                           

                            <a class="collapsed"
                               role="button"
                               data-toggle="collapse"
                               data-parent="#prtdata"
                               href="#etikdata"
                               aria-expanded="false"
                               aria-controls="etikdata"
                               style="font-size: 1.1em"
                               rel="nofollow"
                            >
                                <i class="fa fa-angle-right"> </i> &nbsp; &nbsp; <b class="">E</b>tiquettes
                            </a>
                        </div>
                    </div>

                    <div id="etikdata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="etik">
                        <div class="second-nested-panel-b">
                            <div class="row" style="">
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a rel="nofollow" href="/configurateur/form?f=search_thermique">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/zm400_.jpg' ?>" alt="">
                                        </div>
                                        <div class="row ">Thermique</div>
                                    </a>
                                </div>
                                <div class="col-lg-2 col-sm-2"></div>
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a hrel="nofollow" ref="/configurateur/form?f=search_etiquette_badgeuse">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/p330.jpg' ?>" alt="">
                                        </div>
                                        <div class="row ">Badgeuse</div>
                                    </a>
                                </div>
                                <div class="col-lg-2 col-sm-2"></div>
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a rel="nofollow" href="/configurateur/form?f=search_etiquette_couleur">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/LX400.jpg' ?>" alt="">
                                        </div>
                                        <div class="row ">Couleur</div>
                                    </a>
                                </div>
                                <div class="col-lg-2"></div>
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a rel="nofollow" href="/configurateur/form?f=search_etiquette_portable">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/ql420.jpg' ?>" alt="">
                                        </div>
                                        <div class="row ">Portable</div>
                                    </a>

                                </div>
                                <br><br>
                            </div>
                        </div>
                    </div>

                </div>


                <div class="second-nested-panel- panel-d">
                    <div class="second-nested-panel-h" role="tab" id="laser">
                        <h4 class="second-nested-panel-t">
                            <a rel="nofollow" class="collapsed"
                               role="button"
                               data-toggle="collapse"
                               data-parent="#prtdata"
                               href="#laserdata"
                               aria-expanded="false"
                               aria-controls="laserdata">
                                <a href="/configurateur/form?f=search_printer_laser"><i class="fa fa-angle-right "> </i> &nbsp; &nbsp; <b>L</b>aser</a>
                            </a>
                        </h4>
                    </div>

                    <div id="laserdata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="laser">
                        <div class="second-nested-panel-b">
                            <div class="row" style="">
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a rel="nofollow" href="/configurateur/form?f=search_printer_laser">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/laser_.png' ?>" alt="">
                                        </div>
                                        <div class="row blue b hidden"><b>LASER</b></div>
                                    </a>
                                </div>
                                <br><br>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="second-nested-panel- panel-d">
                    <div class="second-nested-panel-h" role="tab" id="matri">
                        <h4 class="second-nested-panel-t">
                            <a rel="nofollow" class="collapsed"
                               role="button"
                               data-toggle="collapse"
                               data-parent="#prt"
                               href="#matridata"
                               aria-expanded="false"
                               aria-controls="matridata">
                                <a href="/configurateur/form?f=search_printer_matricielle"><i class="fa fa-angle-right "> </i> &nbsp; &nbsp; <b>M</b>atricielles</a>
                            </a>
                        </h4>
                    </div>

                    <div id="matridata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="matri">
                        <div class="second-nested-panel-b">
                            <div class="row" style="">
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a rel="nofollow" href="/configurateur/form?f=search_printer_matricielle">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/matricielle.jpg' ?>" alt="">
                                        </div>
                                        <div class="row blue b hidden"><b>MATRICIELLE</b></div>
                                    </a>
                                </div>
                                <br><br>
                            </div>
                        </div>
                    </div>

                </div>


            </div>

        </div>
    </div>
</div>
<!--  FIN  CATEGORIE IMPRIMANTE-->