

<div class="row ">
    <div class="col-md-12 ">
        <section class="">
            <ul class="bxslider" style="background-color: white;">
                <?php
                $sliders = [
                    [
                            'img' =>  'ban_repair-min.jpg',
                            'link' =>  "https://www.eurocomputer.fr/devis/reparation?id_category_group=14&id_category=39",
                    ],
                    [
                        'img' => 'ban_terminaux-min.jpg',
                        'link' =>  "https://www.eurocomputer.fr/devis?id_product=0&id_marque=0&id_type=0",
                    ],
                    [
                        'img' =>  'ban_imprimante-min.jpg',
                        'link' =>  "https://www.eurocomputer.fr/devis?id_product=0&id_marque=0&id_type=0",
                    ]
                ];

                //https://www.eurocomputer.fr/devis/reparation?id_category_group=14&id_category=39
                //https://www.eurocomputer.fr/devis/reparation?id_category_group=14&id_category=39%20%3E
                if (!empty($sliders)):
                    foreach ($sliders as $slide):
                        ?>
                        <li style="background-color: white;">
                            <a href="<?php echo $slide['link'] ?>" style="background-color: white;">
                                <img
                                     width="1349"
                                     height="381"
                                     src=" <?php echo PROJECTS . '/upload/images/geo/'.$slide['img']?>"
                                     title="<?php echo $slide['img'] ?>"
                                     alt="<?php echo "banniere_marketing".$slide['img'] ?>"
                                     style="background-color: white;"
                                />
                            </a>

                        </li>
                        <?php
                    endforeach;
                endif;
                ?>
            </ul>
        </section>
    </div>
</div>


