<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>

<body>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td align="center" valign="top" bgcolor="#ffe77b" style="background-color:#FFFFFF;"><br>
            <br>
            <table width="600" border="0" cellspacing="0" cellpadding="0">

                <tr>
                    <td align="left" valign="top">
                        <div style="width:100%; height:13px; background:#4097c0; border-radius:5px 5px 0 0"></div>
                    </td>
                </tr>
                <tr>
                    <td align="left"
                        valign="middle"
                        bgcolor="#564319"
                        style="background-color:#4097c0; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; padding:10px;">
                        <div style="font-size:26px; color:#ffffff;">
                            <b><?php echo $this->subject ?></b>
                        </div>
                    </td>
                </tr>
                <tr style="border-left:#963 solid 1px;border-right:#963 solid 1px;">
                    <td align="left"
                        valign="top"
                        bgcolor="#ffffff"
                        style="background-color:#fffff;border-left:#4097c0 solid 1px;border-right:#4097c0 solid 1px;">

                        <table width="95%" border="0" align="center" cellpadding="0" cellspacing="0">
                            <tr>

                                <td align="left" valign="middle"
                                    style="color:#525252; font-family:Arial, Helvetica, sans-serif; padding:10px;"

                                >
                                    <div style="font-size:16px; font-weight:bold">
                                        INFORMATION CLIENT <br>
                                        <?php echo strtoupper($this->post['compagny']) ?>
                                        <br>
                                        <?php echo strtoupper($this->post['nom']).' '.$this->post['prenom'] ?>
                                        <br>
                                        <?php echo $this->post['email'] ?>
                                        <br>
                                        <?php echo $this->post['tel'] ?>
                                        <br>
                                        <br>
                                        Informations complémentaire : <?php echo $this->post['info'] ?>
                                        <br>
                                        <br>
                                    </div>
                                    <div style="font-size:12px;font-family:Arial, Helvetica, sans-serif;">
                                        <table align="left" class="" style="float:left">
                                            <thead>
                                            <tr align="left"
                                                style="float:left;  text-align:left ; font-family:Arial, Helvetica, sans-serif; padding-bottom: 10px">
                                                <th align="left" style="float:left;">CARACTERISTIQUES</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <?php foreach ($this->input as $index => $item) : ?>
                                                <tr style="font-family:Arial, Helvetica, sans-serif;"
                                                    id="<?php echo "row_$index" ?>">
                                                    <td style="font-family:Arial, Helvetica, sans-serif;">
                                                        <?php echo "<b>".$item['choice'].'</b> -  '.strtoupper($item['section']).' - Qte : '.$item['qte'] ?>
                                                        <ul style="font-family:Arial, Helvetica, sans-serif;">
                                                            <?php echo is_string($item['input']) ? $item['input'] : ''; ?>
                                                            <?php foreach ($item['input'] as $i => $v) : ?>
                                                                <?php if (is_array($v)): ?>
                                                                    <b><?php echo $i ?> :</b>

                                                                    <ul style="font-size:12px ;">

                                                                        <?php foreach ($v as $subindex => $subvalue) : ?>
                                                                            <li style="font-size: 12px"> <?php echo $subvalue ?> </li>
                                                                        <?php endforeach; ?>
                                                                    </ul>
                                                                <?php else: ?>
                                                                    <li style="font-size:12px"><?php echo $i.' : '.$v ?></li>
                                                                <?php endif; ?>
                                                            <?php endforeach; ?>
                                                        </ul>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>
