<?php

$seo = new Genius_Class_Seo();
$menus = Genius_Model_Menu::getAllMenus();
$accessoires = Genius_Model_Product::getAccessoires();
$all_marques = true;
if ($this->id_category_group && $this->id_category) {
    $all_marques = false;

    if (!empty($this->types['categories_list'])) {
        foreach ($this->types['categories_list'] as $kt => $type) {
            $r = Genius_Model_Product::getProductsWithinCategories(array($this->id_category, $type['id_category']));
            if (empty($r)) {
                unset($this->types['categories_list'][$kt]);
            } else {
                $this->types['categories_list'][$kt]['count_product'] = count($r);
            }
        }
    }
}

$group = Genius_Model_Group::getGroupById($this->id_category_group);
if ($all_marques) {
    $marque_titre = "";
	$accroche = $group['accroche_' . DEFAULT_LANG_ABBR];
	$description = $group['text_' . DEFAULT_LANG_ABBR];
} else {
    $category = Genius_Model_Category::getCategoryById($this->id_category);
    $marque_titre = $category['title_' . DEFAULT_LANG_ABBR];
	$accroche = $group['accroche_' . DEFAULT_LANG_ABBR];
	$description = $group['text_' . DEFAULT_LANG_ABBR];
}
?>
<!-- start subheader -->

<!-- start subheader -->

<section class="subHeader page">
    <div class="container">
        <h1><?php echo $this->translate("Micro - Toutes marques") ?></h1>
    </div>
    <!-- end subheader container --> 
</section>
<!-- end subheader section -->

<section style="padding-top: 50px">

    <div class="col-lg-3" style="padding-top: 30px;">
        <?php echo($this->render($this->search)); ?>
        <?php echo($this->render($this->filter)); ?>
        <?php echo($this->render($this->explication)); ?>
    </div>

    <div class="col-lg-8" style="padding-top: 20px ;">
        <div class="container">
            <div class="page_title2">
                <?php if ($all_marques) { ?>
                    <div class="pagenation">&nbsp; <a  style="font-size:18px;font-weight:bold;color:#004FAE;" href="/">Home</a> <i>/</i> <a title="micro" href="/micro"  style="font-size:18px;font-weight:bold;color:#004FAE;"><?php echo $group['title_' . DEFAULT_LANG_ABBR]; ?></a>

                    </div>
                <?php } else { ?>
                    <div class="pagenation">&nbsp; <a  style="font-size:18px;font-weight:bold;color:#004FAE;" href="/">Home</a> <i>/</i> <a title="micro" href="/micro"><?php echo $group['title_' . DEFAULT_LANG_ABBR]; ?></a> <i>/</i> <i style="font-size:18px;font-weight:bold;color:#004FAE;"><?php echo $marque_titre; ?></i>

                    </div>
                <?php } ?>
            </div>
            <div class="divider" style="margin-top:0 !important"></div>
            <div class="row" id="banniere">
                <img src="<?php echo UPLOAD_URL?>images/multimedias/banniere_micro.jpg" width="1010" height="235">
            </div>
            <div class="divider" style="margin-top:0 !important"></div>
            <div class="accroche"><marquee behavior="loop" loop="5" width="48%"><?php echo $accroche; ?></marquee></div>
            <div class ="row">
                <div class="row">
                    <?php
                    if (!$all_marques) {

                        if (!empty($this->types['categories_list'])) {
                            $nbr1 = 0;
                            foreach ($this->types['categories_list'] as $kt => $type) {

                                $products = Genius_Model_Product::getProductsByCategoryIds($this->id_category, $type['id_category']);
                                $photocover = Genius_Model_Category::getCategoryImageCoverById($type['id_category']);
                                $ppath = (!empty($photocover)) ? $photocover['path_folder'] . '/' . $photocover['filename'] . '-cover-' . $photocover['id_image'] . '.' . $photocover['format'] : '';

                                $photocrh_cover = THEMES_DEFAULT_URL . 'images/non_dispo.png';
                                if (file_exists(UPLOAD_PATH . 'images/' . $ppath) && is_file(UPLOAD_PATH . 'images/' . $ppath)) {
                                    $photocrh_cover = UPLOAD_URL . 'images/' . $ppath;
                                }
                                if (count($products) > 0) {
                                    $nbr1++;
                                    if (in_array($type['id_category'], $accessoires)) {
                                        ?>
                                        <div class="col-lg-3 col-md-3 col-sm-6 <?php
                                        if ($nbr1 == 4) {
                                            echo'col_der';
                                            $nbr1 = 0;
                                        }
                                        ?>">
                                            <div class="propertyItem">
                                                <div class="propertyContent"> <a class="propertyType"><?php echo $type['title']; ?></a> <a class="propertyImgLink"> <img class="propertyImg" src="<?php echo $photocrh_cover; ?>" alt="" /> </a>
                                                    <?php
                                                    if (!empty($products)) {
                                                        ?>
                                                        <div class="box_menu box_menu_left">
                                                            <h4><?php echo $type['title']; ?></h4>
                                                            <ul class="deroulant">
                                                                <?php
                                                                foreach ($products as $kp => $product) {
                                                                    echo '<li><a title="' . $product['title'] . '" href="' . $seo->getLinkProduct($product['id_product']) . '">' . $product['title'] . '</a></li>';
                                                                } // endforeach
                                                                ?>
                                                            </ul>
                                                        </div>
                                                        <?php
                                                    } // endif
                                                    ?>
                                                </div>
                                            </div>
                                        </div>
                                        <?php
                                    } else {
                                        ?>
                                        <div class="col-lg-3 col-md-3 col-sm-6 <?php
                                        if ($nbr1 == 4) {
                                            echo'col_der';
                                            $nbr1 = 0;
                                        }
                                        ?>">
                                            <div class="propertyItem">
                                                <div class="propertyContent"> <a class="propertyType"><?php echo $type['title']; ?></a> <a class="propertyImgLink"> <img class="propertyImg" src="<?php echo $photocrh_cover; ?>" alt="" /> </a>
                                                    <?php
                                                    if (!empty($products)) {
                                                        ?>
                                                        <div class="box_menu box_menu_left">
                                                            <h4><?php echo $type['title']; ?></h4>
                                                            <ul class="deroulant">
                                                                <?php
                                                                foreach ($products as $kp => $product) {
                                                                    echo '<li><a title="' . $product['title'] . '" href="' . $seo->getLinkProduct($product['id_product']) . '">' . $product['title'] . '</a></li>';
                                                                } // endforeach
                                                                ?>
                                                            </ul>
                                                        </div>
                                                        <?php
                                                    } // endif
                                                    ?>
                                                </div>
                                            </div>
                                        </div>
                                        <?php
                                    }
                                    ?>

                                    <?php
                                } // endif
                            } // endforeach
                        } // endif
                    } else {
                        if (!empty($this->types['categories_list'])) {
                            $nbr = 0;
                            foreach ($this->types['categories_list'] as $kt => $type) {
                                if ( $type['id_category'] == 111) break;
                                $products = Genius_Model_Product::getProductsWithinCategories(array($type['id_category']));
                                $ids_products = array();
                                if (!empty($products)) {
                                    foreach ($products as $kp => $pro) {
                                        $ids_products[] = $pro['id_product'];
                                    }
                                }

                                $photocover = Genius_Model_Category::getCategoryImageCoverById($type['id_category']);
                                $ppath = (!empty($photocover)) ? $photocover['path_folder'] . '/' . $photocover['filename'] . '-cover-' . $photocover['id_image'] . '.' . $photocover['format'] : '';

                                $photocrh_cover = THEMES_DEFAULT_URL . 'images/non_dispo.png';
                                if (file_exists(UPLOAD_PATH . 'images/' . $ppath) && is_file(UPLOAD_PATH . 'images/' . $ppath)) {
                                    $photocrh_cover = UPLOAD_URL . 'images/' . $ppath;
                                }

                                $marques_products = Genius_Model_Product::getProductsMarques($this->id_category_group, $ids_products);
                                if (count($marques_products) > 0) {
                                    $nbr++;
                                    if (in_array($type['id_category'], $accessoires)) {
                                        ?>
                                        <div class="col-lg-3 col-md-3 col-sm-6  <?php
                                        if ($nbr == 4) {
                                            echo'col_der';
                                            $nbr = 0;
                                        }
                                        ?>">
                                            <div class="propertyItem uniform_height">
                                                <!--Bloc pastille-->
                                                <?php if (!empty($type['pastille'])): ?>
                                                    <div class="pastille"><img src="<?php echo THEMES_DEFAULT_URL?>images/pastille/pastille-<?php echo $type['modele_pastille']?>.png"><?php echo $type['pastille'] ?></div>
                                                <?php endif; ?>
                                                <!--Fin Bloc pastille-->
                                                <div class="propertyContent"> <a class="propertyType" ><?php echo $type['title'];?></a> <a class="propertyImgLink"> <img class="propertyImg" src="<?php echo $photocrh_cover; ?>" alt="<?php echo $type['title']; ?>" /> </a>
                                                    <div class="box_menu box_menu_left">
                                                        <h4><?php echo $type['title']; ?></h4>
                                                        <ul class="deroulant">
                                                            <?php
                                                            if (!empty($marques_products)) {
                                                                foreach ($marques_products as $kmp => $marque) {
                                                                    $products = Genius_Model_Product::getProductsByCategoryIds($marque['id_category'], $type['id_category']);
                                                                    if (count($products) > 0) {
                                                                        foreach ($products as $kp => $product) {
                                                                            echo '<li><a title="' . $product['title'] . '" href="' . $seo->getLinkProduct($product['id_product']) . '">' . $product['title'] . '</a></li>';
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                            ?>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <?php
                                    } else {
                                        ?>
                                        <?php if ($type['id_category']!=121 && $type['id_category']!=123 && $type['id_category']!=137){?>
                                            <div class="col-lg-3 col-md-3 col-sm-6  <?php
                                            if ($nbr == 4) {
                                                echo'col_der';
                                                $nbr = 0;
                                            }
                                            if ($type['id_category'] == 85){
                                                $type['title'] = $this->translate("Destockage PC");
                                            }else{
                                                $type['title'] = $type['title'];
                                            }
                                            ?>">
                                                <div class="propertyItem uniform_height">
                                                    <!--Bloc pastille-->
                                                    <?php if (!empty($type['pastille'])): ?>
                                                        <div class="pastille"><img src="<?php echo THEMES_DEFAULT_URL?>images/pastille/pastille-<?php echo $type['modele_pastille']?>.png"><?php echo $type['pastille'] ?></div>
                                                    <?php endif; ?>
                                                    <!--Fin Bloc pastille-->
                                                    <div class="propertyContent"> <a class="propertyType color_micro" ><?php echo $type['title'];?></a> <a class="propertyImgLink" href="<?php echo $seo->getLinkGroupMarque(15,$this->id_category_group,$type['id_category']);?>"> <img class="propertyImg" src="<?php echo $photocrh_cover; ?>" alt="<?php echo $type['title']; ?>" /> </a>
                                                        <?php if (1==0):?>
                                                            <div class="box_menu box_menu_left">
                                                                <h4><?php echo $type['title']; ?></h4>
                                                                <ul>
                                                                    <?php
                                                                    if (!empty($marques_products)) {
                                                                        foreach ($marques_products as $kmp => $marque) {
                                                                            $products = Genius_Model_Product::getProductsByCategoryIds($marque['id_category'], $type['id_category']);
                                                                            if (count($products) > 0) {
                                                                                echo '
								  <li>
									  <a>' . $marque['title'] . '</a>
									  <ul>
								  ';
                                                                                foreach ($products as $kp => $product) {
                                                                                    echo '<li><a title="' . $product['title'] . '" href="' . $seo->getLinkProduct($product['id_product']) . '">' . $product['title'] . '</a></li>';
                                                                                }
                                                                                echo '    
									  </ul>
								  </li>                                                        
								  ';
                                                                            }
                                                                        }
                                                                    }
                                                                    ?>
                                                                </ul>
                                                            </div>
                                                        <?php endif;?>
                                                        <?php if ($type['id_category'] == 87){?>
                                                            <ul class="list-group view_marque">
                                                                <?php
                                                                if (!empty($marques_products)) {
                                                                    foreach ($marques_products as $kmp => $marque) {
                                                                        $products = Genius_Model_Product::getProductsByCategoryIds($marque['id_category'], $type['id_category']);

                                                                        ?>
                                                                        <li class="list-group-item">
                                                                            <a title="<?php echo $marque['title']?>" href="<?php echo $seo->getLinkGroupMarque(15,$this->id_category_group,$marque['id_category']);?>"> &raquo;&nbsp;&nbsp;&nbsp;<?php echo $marque['title'];?></a>
                                                                        </li>
                                                                        <?php
                                                                    }
                                                                }
                                                                ?>
                                                            </ul>
                                                        <?php }else{?>
                                                            <ul class="list-group view_marque">
                                                                <?php
                                                                if (!empty($marques_products)) {
                                                                    foreach ($marques_products as $kmp => $marque) {
                                                                        $products = Genius_Model_Product::getProductsByCategoryIds($marque['id_category'], $type['id_category']);
                                                                        if (count($products) > 0) {
                                                                            foreach ($products as $kp => $product) {
                                                                                ?>
                                                                                <li class="list-group-item">
                                                                                    <a title="<?php echo $product['title']?>" href="<?php echo $seo->getLinkProduct($product['id_product']);?>"> &raquo;&nbsp;&nbsp;&nbsp;<?php echo $product['title'];?></a>
                                                                                </li>
                                                                                <?php
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                                ?>
                                                            </ul>
                                                        <?php }?>

                                                    </div>
                                                </div>
                                            </div>
                                            <?php
                                        }
                                    }
                                    ?>

                                    <?php
                                } // endif
                            } // endforeach
                        } // endif
                    }
                    ?>
                    <!--<div class="col-lg-3 col-md-3 col-sm-6">
                  <div class="propertyItem">
                    <div class="propertyContent"><a class="propertyType" href="#"><?php echo $this->translate("Accessoires & produits associés") ?></a><a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/pieces.jpg" alt="" /></a>
                      <div class="box_menu box_menu_left">
                        <h4><?php echo $this->translate("Accessoires & produits associés") ?></h4>
                        <ul>
                <?php
                    if (!empty($this->types['categories_list'])) {
                        foreach ($this->types['categories_list'] as $kt => $type) {
                            if ($type['id_category'] == 101) {
                                $products = Genius_Model_Product::getProductsWithinCategories(array($type['id_category']));
                                $ids_products = array();
                                if (!empty($products)) {
                                    foreach ($products as $kp => $pro) {
                                        $ids_products[] = $pro['id_product'];
                                    }
                                }
                                ?>
                                                                          <li><a>1</a></li>
                            <?php
                            }
                        }
                    }
                    ?>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>-->
                    <?php if (1==0):?>
                        <div class="col-lg-3 col-md-3 col-sm-6">
                            <div class="propertyItem">
                                <div class="propertyContent"><a class="propertyType" href="/page/reparationservices"><?php echo $this->translate("Réparation et services") ?></a><a href="/page/reparationservices" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/reparation.jpg" alt="" /></a> </div>
                            </div>
                        </div>
                    <?php endif;?>
                </div>
            </div>

            <div class="row desc_rubrique">
                <?php
                echo $description;
                ?>
            </div>
            <!-- end row -->
            <div class="spacer"></div>
        </div>

</section>


<!-- start widgets section -->
<section class="genericSection2">
    <div class="container">
        <div class="row">
            <div class="hbigline1">&nbsp;</div>
        </div>
    </div>
    <?php echo $this->render('statics/carousel.phtml'); ?>
</section>

<script src = "<?php echo URL_DEFAULT_CSS; ?>geo/js/js10.js"></script>
<script src = "<?php echo URL_DEFAULT_CSS; ?>geo/js/jsui.js"></script>

<script type="text/javascript">



    $(document).ready(function () {

        $(function() {

            $("#euro-search").autocomplete({
                minLength: 2,
                source: location.origin + '/search/auto',
                focus: function (event, ui) {
                    $("#euro-search").val(ui.item.value);
                    return false;
                },
                select: function (event, ui) {
                    console.log(ui.item.value);
                    return false;
                }
            })
                .data("ui-autocomplete")._renderItem = function (ul, item) {
                var inner_html = '<a href="' + item.label.h + '\">' +
                    '<div class="list_item_container">' +
                    '<div class="image-autocomplete">' +
                    '<img src="' + item.desc + '"></div>' +
                    '<div id="title-autocomplete">' + item.value + '</div>' +
                    '<div id="description-autocomplete">' + item.label.label + '</div>' +
                    '</div>' +
                    '</div>' +
                    '</a>';
                return $("<li></li>")
                    .data("ui-autocomplete-item", item)
                    .append(inner_html)
                    .appendTo(ul);
            };
        });



        $('[data-toggle="tooltip"], .tooltip').tooltip({ html:true });


        setTimeout(configurator, 0);
        setTimeout(configurator2, 0);
        setTimeout(helper_configurator, 0);

        setTimeout(first_help, 0);
        setTimeout(second_help, 0);
        setTimeout(first_help_free, 0);
        setTimeout(first_star, 0);
        setTimeout(second_help_border, 0);

        function first_help() {
            $("#first-config-help").show();
        }

        function configurator() {
            $("#configurator").show();
        }
        function configurator2() {
            $("#accordion").show();
        }

        function helper_configurator() {
            $("#helper_configurator").show();
        }

        function second_help() {
            $("#second-config-help").show();
        }

        function second_help_border() {
            $("#second_border").css({
                'color': '#F8CC49',
                'font-size' :'1.2em',
                'transition' :'color 0s , font-size 0s'
            });
        }

        function first_star() {
            $("#first-star").show();
        }

        function first_help_free() {
            $("#first-free").css({
                'font-weight': 'bolder',
                'color': '#F8CC49',
                'font-size' :'1.2em',
                'transition' :'color 0s , font-size 0s'
            });
        }

        $('a[href=#top]').click(function(){
            $('html, body').animate({scrollTop:0}, 'slow');
            return false;
        });

        var counterPannier = <?php echo isset($this->choice ) ?$this->choice :0?>;

        if(counterPannier > 0)
        {
            $(".iconepannier").show( "fast" );
            $(".first-panel- ").removeClass('first-panel-').addClass('panel- panel-d ').css('border-top','none');
        }

        var valuePannier = $("#pannierValue").text();



        $("#close-modal-panier").live("click", function(e) {
            e.preventDefault();
            $('#modal-font-panier').hide();
            $('#modal-box-panier').hide();
        });
        $("#close-modal-panier-time").live("click", function(e) {
            e.preventDefault();
            $('#modal-font-panier').hide();
            $('#modal-box-panier').hide();
        });


        $(".add-demande").live("click", function(e) {

            var scanner1d = $("#scanner1d:checked").length;
            var scanner2d = $("#scanner2d:checked").length ;
            var scanneremb = $("#scannerembarque:checked").length ;

            var condition = ( (scanner1d === 1) || (scanner2d === 1)|| (scanneremb === 1) || (scanner1d === 2) || (scanner2d === 2)|| (scanneremb === 2)) ;

            console.log(condition);
            console.log(scanner1d);
            console.log(scanner2d);
            console.log(scanneremb);

            //var condition = true ;

            if(  condition === false)
            {
                e.preventDefault();

                var id  = $(this).attr('id');

                //j('[data-toggle="tooltip"], .tooltip').tooltip("hide",{ html:true });

                $.get( "/configurateur/choice?product="+id)
                    .done(function( data ) {

                        if(data.count > 0)
                        {
                            $(".iconepannier").show( "fast" );
                            $(".first-panel- ").removeClass('first-panel-').addClass('panel- panel-d ').css('border-top','none');
                        }

                        data.count = parseInt(data.count);

                        updatedValue = data.count.toString();

                        $("#pannierValue").text(updatedValue);

                        if(data.state === 1){

                            console.log(data.description)
                            console.log(data.carac)

                            $("#panier_img").attr( 'src',data.image );
                            $("#panier_product").text(data.article );
                            $("#panier_description").html(data.description+'' ).text();
                            $("#panier_caracteristique").text(data.carac ).html();

                            var product = ""
                            var description = ""
                            var carac = ""



                            $('#modal-font-panier').show();
                            $('#modal-box-panier').show('slow');

                            //$(".flashMessageSucess").show( "medium" ).delay(1000).hide('slow');
                        }
                        else{
                            $(".flashMessageError").show( "medium" ).delay(1000).hide('slow');
                        }
                    });
            }
        });
        $(".add-product").live("click", function(e) {

            var scanner1d = $("#scanner1d:checked").length;
            var scanner2d = $("#scanner2d:checked").length ;
            var scanneremb = $("#scannerembarque:checked").length ;

            var condition = ( (scanner1d === 1) || (scanner2d === 1)|| (scanneremb === 1) || (scanner1d === 2) || (scanner2d === 2)|| (scanneremb === 2)) ;

            console.log(condition);
            console.log(scanner1d);
            console.log(scanner2d);
            console.log(scanneremb);

            //var condition = true ;

            if(  condition === false)
            {
                e.preventDefault();

                var id  = $(this).attr('id');

                //j('[data-toggle="tooltip"], .tooltip').tooltip("hide",{ html:true });

                $.get( "/configurateur/choice?product="+id)
                    .done(function( data ) {

                        if(data.count > 0)
                        {
                            $(".iconepannier").show( "fast" );
                            $(".first-panel- ").removeClass('first-panel-').addClass('panel- panel-d ').css('border-top','none');
                        }

                        data.count = parseInt(data.count);

                        updatedValue = data.count.toString();

                        $("#pannierValue").text(updatedValue);

                        if(data.state === 1){

                            console.log(data.description)
                            console.log(data.carac)

                            $("#panier_img").attr( 'src',data.image );
                            $("#panier_product").text(data.article );
                            $("#panier_description").html(data.description+'' ).text();
                            $("#panier_caracteristique").text(data.carac ).html();

                            var product = ""
                            var description = ""
                            var carac = ""



                            $('#modal-font-panier').show();
                            $('#modal-box-panier').show('slow');

                            //$(".flashMessageSucess").show( "medium" ).delay(1000).hide('slow');
                        }
                        else{
                            $(".flashMessageError").show( "medium" ).delay(1000).hide('slow');
                        }
                    });
            }
        });


        $(".add-picture_product").live("click", function(e) {

            var scanner1d = $("#scanner1d:checked").length;
            var scanner2d = $("#scanner2d:checked").length ;
            var scanneremb = $("#scannerembarque:checked").length ;

            var condition = ( (scanner1d === 1) || (scanner2d === 1)|| (scanneremb === 1) || (scanner1d === 2) || (scanner2d === 2)|| (scanneremb === 2)) ;

            console.log(condition);
            console.log(scanner1d);
            console.log(scanner2d);
            console.log(scanneremb);

            //var condition = true ;

            if(  condition === false)
            {
                e.preventDefault();

                var id  = $(this).attr('id');

                //j('[data-toggle="tooltip"], .tooltip').tooltip("hide",{ html:true });

                $.get( "/configurateur/choice?product="+id)
                    .done(function( data ) {

                        if(data.count > 0)
                        {
                            $(".iconepannier").show( "fast" );
                            $(".first-panel- ").removeClass('first-panel-').addClass('panel- panel-d ').css('border-top','none');
                        }

                        data.count = parseInt(data.count);

                        updatedValue = data.count.toString();

                        $("#pannierValue").text(updatedValue);

                        if(data.state === 1){

                            console.log(data.description)
                            console.log(data.carac)

                            $("#panier_img").attr( 'src',data.image );
                            $("#panier_product").text(data.article );
                            $("#panier_description").html(data.description+'' ).text();
                            $("#panier_caracteristique").text(data.carac ).html();

                            var product = ""
                            var description = ""
                            var carac = ""



                            $('#modal-font-panier').show();
                            $('#modal-box-panier').show('slow');

                            //$(".flashMessageSucess").show( "medium" ).delay(1000).hide('slow');
                        }
                        else{
                            $(".flashMessageError").show( "medium" ).delay(1000).hide('slow');
                        }
                    });
            }
        });
    });

    var j = jQuery.noConflict();

    j(function() {

        j("#euro-search").autocomplete({
            minLength: 2,
            source: location.origin + '/search/auto',
            focus: function (event, ui) {
                j("#euro-search").val(ui.item.value);
                return false;
            },
            select: function (event, ui) {
                console.log(ui.item.value);
                return false;
            }
        })
            .data("ui-autocomplete")._renderItem = function (ul, item) {
            var inner_html = '<a href="' + item.label.h + '\">' +
                '<div class="list_item_container">' +
                '<div class="image-autocomplete">' +
                '<img src="' + item.desc + '"></div>' +
                '<div id="title-autocomplete">' + item.value + '</div>' +
                '<div id="description-autocomplete">' + item.label.label + '</div>' +
                '</div>' +
                '</div>' +
                '</a>';
            return j("<li></li>")
                .data("ui-autocomplete-item", item)
                .append(inner_html)
                .appendTo(ul);
        };
    });
</script>




<style>
ul.view_marque{
	margin-top:10px;
}
ul.view_marque li{
	padding: 5px 15px 5px 5px!important;
	border: none!important;
}
ul.view_marque li:hover{
	background: #efefef;
	}
ul.view_marque li a{
	color:#686868;
	font-size: 13px;
}
.uniform_height{
	height:460px!important;
	overflow: hidden;
}
.color_micro{
	background:#004FAE!important;
	width: 100%;
	font-size:11px;
    display: block;
	text-align: center;
    position: inherit!important;
	margin-bottom: 10px;
    font-family: sans-serif!important;
}
	#banniere{margin:0px auto;}
	#banniere img{
		width:100%;
		height:auto;
	}
</style>
