<br>
<p>
    Experts depuis 25 ans dans la <b>reprise d’équipements informatiques</b> et engagés dans une démarche « écolo-nomique »,
    nous recyclons tout matériel ancien en le réparant ou en récupérant ses pièces détachées.
</p>

<p>
    Nous pouvons <b>valoriser votre parc informatique</b>.
</p>


<p>Les matériels suivants en particulier sont susceptibles de nous intéresser :</p>

<ul style="padding-left: 20px">
    <li style="list-style: square"><b>Imprimantes étiquettes</b></li>
    <li style="list-style: square"><b>Terminaux mobiles / scanners lecteurs code-barre</b></li>
    <li style="list-style: square">Lots importants de PC ou de clients légers </li>
</ul>

La démarche est simple et rapide !
<br>
<ol style="padding-left: 20px">
    <li style="padding-top: 8px"><b>Remplissez le formulaire</b>  ci-contre</li>
    <li style="padding-top: 8px">Si votre matériel nous intéresse, vous recevrez très rapidement <b>une offre de rachat</b> et organiserons avec notre transporteur l’enlèvement du matériel sur site</li>
    <li style="padding-top: 8px">Il sera audité par nos techniciens experts dès son arrivée</li>
    <li style="padding-top: 8px">Vous pourrez choisir entre :</li>
</ol>
<ul style="padding-left: 40px">
    <li style="list-style: square"><b>Bon d’achat</b> à valoir chez Eurocomputer afin de financer votre nouveau matériel</li>
    <u>ou</u>
    <li style="list-style: square"><b>Rachat pur</b> après réception de facture</li>
</ul>
<p>
    En revendant votre matériel, votre stock sera valorisé et nous lui offrirons une seconde vie !
</p>