<?php
$menus = Genius_Model_Menu::getAllMenus();
$seo = new Genius_Class_Seo();
?>
<!-- start subheader -->

<!-- start subheader -->

<section class="subHeader page">
    <div class="container">
        <h1><?php echo $this->translate("Reprise") ?></h1>
    </div>
    <!-- end subheader container -->
</section>
<!-- end subheader section -->

<!-- start recent properties -->


<section class="" style="padding-top: 26px;">
    <div class="container ">
        <div class="page_title2 hidden invisible">
            <div class="pagenation">
                <div class="padding-top">&nbsp;<a href="/">Home</a>
                    <i>/</i> <?php echo $this->translate("Reprise") ?></i></div>
                <?php echo $this->render('statics/moteur_v1.phtml'); ?>
            </div>
        </div>


        <div class="row" >
                <img width="100%" height="auto" src="<?php echo UPLOAD_URL.'images/geo/pages/reprise.jpg' ?>">
        </div>

        <div class="row" style="padding: 40px"
        >
            <div class="col-lg-12">
                <div class="row" style="padding: 10px 20px 10px 20px; background-color:#ffffff;
                -webkit-box-shadow: 3px 0px 31px 0px rgba(0,0,0,0.25);
                -moz-box-shadow: 3px 0px 31px 0px rgba(0,0,0,0.25);
                box-shadow: 3px 0px 31px 0px rgba(0,0,0,0.25);
                margin-top: -105px;
">
                    <div class="col-lg-6 lightbold" style="font-size:13px; line-height: 1.7em">
                        <h1 style="font-size: 1.5em ; color: #666666; font-weight: bolder; ">
                            REVENDRE VOTRE MATERIEL
                        </h1>
                        <div style="width: 10%;border-bottom: 3px solid #666666;margin-top: -30px">
                            &nbsp;
                        </div>
                        <?php include('reprise_description.phtml') ?>

                    </div>
                    <div class="col-lg-6"  style="font-size:13px; line-height: 1.7em">
                        <h1 style="font-size: 1.5em ; color: #666666; font-weight: bolder; ">
                            DEMANDE DE REPRISE
                        </h1>
                        <div style="width: 10%;border-bottom: 3px solid #666666;margin-top: -30px">
                            &nbsp;
                        </div>
                        <br>
                        <?php include('reprise_formu.phtml') ?>

                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- end container -->
</section>

<section>
    <div class="container">
        <div class="row" style="background-color: #fff;">
            <div class="col-lg-12 col-md-6 col-sm-6 texte_reparation">
                <?php include('reprisemoredata.phtml') ?>
            </div>
        </div>
    </div>
</section>

<br><br><br>


<!-- start widgets section -->
<section class="genericSection2">
    <div class="container">
        <div class="row">
            <div class="hbigline1">&nbsp;</div>
        </div>
    </div>
    <?php echo $this->render('statics/carousel.phtml'); ?>
</section>
<style>
    .lightbold > p > b{
        color:#666666;
    }
    .lightbold > ul > li > b{
        color:#666666;
    }
    .lightbold > ol > li > b{
        color:#666666;
    }
    ul.view_marque {
        margin-top: 10px;
    }

    ul.view_marque li {
        padding: 5px 15px 5px 5px !important;
        border: none !important;
    }

    ul.view_marque li:hover {
        background: #efefef;
    }

    ul.view_marque li a {
        color: #686868;
        font-size: 13px;
    }

    .uniform_height {
        height: 429px !important;
    }

    .color_tracabilite {
        background: #BD56B5 !important;
        width: 100%;
        font-size: 11px;
        display: block;
        text-align: center;
        position: inherit !important;
        margin-bottom: 10px;
        font-family: sans-serif !important;
    }

    #banniere {
        margin: 0px auto;
    }

    #banniere img {
        width: 100%;
        height: auto;
    }
</style>